In [260]:
import pandas as pd
from tqdm.auto import tqdm

In [261]:
df_train = pd.read_csv("../dataset/original/entity-resolution_advanced-topics-training_data.csv")

In [262]:
df_train.head(100)

,record_id,name,type,address,phone,email,modification,linked_id
0,10111147-T1,ArDIA ENTERPRISESmLTD.,entity,NaN,4.102971e+12,imquires@zoho.vo,typo,10111147
1,12172071-T0,ANDRÃ‰ ALMEIDA BLANCO,officer,la Rua Pelotas; 209; apartamento 72; Bloco A; ...,NaN,NaN,typo,12172071
2,10104491-T1,MOONTA HOLDINGS LTD.,entity,NaN,6.501346e+10,NaN,typo,10104491
3,10068808,SPRINGFIELD INVESTMENTS GROUP LIMITED,entity,NaN,NaN,consulting@zoho.de,original,10068808
4,13011715,GRIGORY UVAROV,officer,127273; MOSCOW; OTRADNAJA STREET; HOUSE 2; NO....,NaN,NaN,original,13011715
5,10105687,ODIN GROUP INVESTMENTS S.A.,entity,NaN,4.966891e+10,info@outlook.cz,original,10105687
6,10016805-T2,CAPRI SOLUTIONS LIMITED,entity,NaN,NaN,help@CAPRI.SOLUTIONS.LxMITED.de,typo,10016805
7,12133421,Crossmatch S.A.,officer,"Akara building 24 De Castro Street, Wickham Ca...",NaN,CrossmatchSA@aol.gov,original,12133421
8,12126772,LAURENCE POUNTNEY LTD,officer,Akara Building 24 De Castro St; Wickham Cay I;...,NaN,support@LAURENCE.POUNTNEY.LTD.gov,original,12126772
9,11002523,"BREIT, MARCUS",intermediary,NaN,4.401803e+11,NaN,original,11002523
10,10046375-NV0,AFCCOTRADE INTERNATIONAL CORP.,entity,3 Place des Bergues; 1201 Geneva; Switzerland,3.910993e+09,NaN,new_value,10046375
11,10002433-NV0,COMMTECH FOUNDATION INC.,entity,1441 Brickell Avenue 1200 Four Seasons Tower M...,NaN,consulting@yahoo.it,new_value,10002433
12,10164485,BROTHERHOOD FOUNDATION..,entity,NaN,1.468006e+10,BROTHERHOODFOUNDATION@protonmail.co.uk,original,10164485
13,12076657-T2,YURY VALENTINOVICH TSKHOVREBOV,officer,10u-1-74; PiOwPECT MARSHALA JUKOVA; MOSCOW; RU...,NaN,NaN,typo,12076657
14,12188364,LI GUOBANG,officer,ROOM 102; BUILDING 37; NO.18; TAIPINGJIAO 4 RO...,NaN,GUOBANG@icloud.com,original,12188364
15,10151690,ZUCEAN LIMITED,entity,NaN,1.505045e+10,NaN,original,10151690
16,10117892-T4,LONGXI INVESTMENT LTD.,entity,NaN,3.325880e+11,info@outlook.com,typo,10117892
17,12170030-M1,REFIK ARIF,officer,Korkadi sokak Panorama Villalari; No: 17-C; D ...,NaN,REFIKARIF@hotmail.gov,missing,12170030
18,10049607-T0,UNICORN IfVESTMENT CORPORATION,entity,NaN,4.921217e+10,NaN,typo,10049607
19,10045048-M0,"SANDRO BOTTICELLI, CORP.",entity,NaN,NaN,NaN,missing,10045048
20,12220469-M2,"ALI AHMED DARRAT, NAJIB AHMED DARRAT, AHMED AA...",officer,NaN,NaN,NaN,missing,12220469
21,10134642-T0,ALiMh LIMITED,entity,NaN,4.206024e+11,NaN,typo,10134642
22,12148122-T4,GUSTAVO SOTO MONTIEL,officer,Calle 50 y 74 San Francisco; Edificio P.H. 909...,4.209600e+11,NaN,typo,12148122
23,12178730-T0,Investec Trustees (Jersey) Limited as the Nomi...,officer,P.O. BOX 344; ONE THE ESPLANAiE; ST. HELIER; J...,NaN,NaN,typo,12178730
24,12204453,CHEN QINGTIAN,officer,ROOM 203; NO. 31; RENJI ROAD(W); YUEXIU; GUANG...,4.120383e+12,CHENQINGTIAN@zoho.co.uk,original,12204453
25,12214184,SANTIAGO PEÃ‘A DURINI,officer,Shyris 1548 entre Suecia y NNUU; Quito; Ecuador,1.393705e+10,info@outlook.gov,original,12214184
26,13012085,Lio Wen Tong,officer,Flat F; 40/F.; Block 7; Island Harbourview; 11...,NaN,NaN,original,13012085
27,10105689-NV0,GEFION INC.,entity,FAB LEATHERS LIMITED; P42/1; HIDE ROAD; CALCUL...,NaN,consulting@GEFION.INC.cz,new_value,10105689
28,12188232,WANG HONG JUN,officer,NO.8-3-301; YOU AI DONG DAO; HE DONG QU; TIANJ...,NaN,WANGHONGJUN@yahoo.de,original,12188232
29,10022235-M2,SPIRIT RIDE S.A.,entity,NaN,NaN,NaN,missing,10022235
...,...,...,...,...,...,...,...,...
70,10032198-M0,LARGO INVESTMENTS S. A.,entity,NaN,NaN,NaN,missing,10032198
71,10020963,PROSPEROUS STAR DEVELOPMENT LTD.,entity,NaN,4.991590e+10,NaN,original,10020963
72,10162772,KOPF VENTURES S.A.,entity,NaN,NaN,NaN,original,10162772
73,10006504-NV1,PAMOUR SECURITIES INC.,entity,20; Spyrou Kyprianou Avenue; CHAPO CENTRAL; 3r...,3.965309e+09,help@aol.ch,new_value,10006504
74,12117042,Kingslea Limited,officer,3rd Floor; Wolvertron Place; Market Square; St...,NaN,support@gmail.de,original,12117042
75,10178835,ROXBY INVESTMENTS LIMITED,entity,NaN,NaN,consulting@ROXBY.INVESTMENTS.LIMITED.cz,original,10178835
76,10103917-T1,NICE TECHNOLOGY LTD.,entity,NaN,1.714927e+10,NaN,typo,10103917
77,12104064-NV1,FENG BAOXI,officer,Corso Nizza 51; Cuneo; Italy,3.990234e+09,NaN,new_value,12104064
78,10148701,HASSI CONSULTANT LTD.,entity,NaN,4.203923e+11,sales@protonmail.ch,original,10148701
79,10156652,WIND SHINE GROUP LIMITED,entity,NaN,4.964416e+10,NaN,original,10156652
80,10065083,LYNDHURST FINANCE S.A.,entity,NaN,4.982944e+10,NaN,original,10065083
81,12167861-M0,ZHOU QINGSHENG,officer,NaN,NaN,NaN,missing,12167861
82,13007497,NARIJAUSKAS JUOZAS,officer,Blusiu 13; Klaipeda; Lithuania,3.311388e+11,NARIJAUSKASJUOZAS@zoho.ch,original,13007497
83,10009407,HERMES EQUITIES CORP.,entity,NaN,4.109246e+12,NaN,original,10009407
84,10176669,ZENNER INTERNATIONAL S.A.,entity,NaN,3.990020e+09,ZENNERINTERNATIONALSA@aol.co.uk,original,10176669
85,10184357-T2,PHISOcw LTD.,entity,NaN,NaN,supportsPHqSOCA.LTD.gov,typo,10184357
86,12013640,D & P MANAGEMENT LIMITED,officer,NaN,4.120080e+12,contact@D.P.MANAGEMENT.LIMITED.gov,original,12013640
87,12193316,SANTIAGO GRAPPIOLO,officer,Paso del Cuello 2434; CP 10001; Montevideo; Ur...,4.122123e+12,NaN,original,12193316
88,12124452,GEORGIA KYRIAKOU,officer,"6 LEROS - 3048 ZAKAKI, LIMASSOL - CYPRUS",NaN,GEORGIAKYRIAKOU@hotmail.de,original,12124452
89,10154784-T2,Crispin Assets Ltd,entity,NaN,3.362663e+11,info@Crispin.Assets.Ltd.de,typo,10154784
90,12206355,LUO GUANGQING,officer,ROOM 1802; COLLEGE INTERNATIONAL MANSION; No.1...,4.495163e+11,NaN,original,12206355
91,10119041-T0,Gutcher Business S.A.,entity,NaN,4.170864e+12,NaN,typo,10119041
92,12012320,HORACIO BONAVIA,officer,NaN,NaN,NaN,original,12012320
93,10205664,MILAN STAR LIMITED,entity,NaN,3.310810e+11,help@icloud.de,original,10205664
94,12186625-T2,"HE, SUNG-LIEN",officer,NO.8; LANE 8; ZHU'AN 3RD ROAD; BAOSHAN TOWNSHI...,3.809250e+11,NaN,typo,12186625
95,10176419-NV0,SLATE LIMITED,entity,NaN,NaN,NaN,new_value,10176419
96,12161963-M0,Cosign Nominees Limited,officer,NaN,NaN,NaN,missing,12161963
97,10035108-NV0,FIVEK LTD.,entity,Room 602; No. 53; Lane 137; Xi Wan Road; Haish...,4.201219e+11,NaN,new_value,10035108
98,12004656-M2,CORPORATE CONSULTING GROUP INC.,officer,"#25 Mason Complex Stoney Ground The Valley , A...",NaN,NaN,missing,12004656
99,10086864-T0,GALAXY POWER BIO-TECHNOyOGY ENTERPRISES LIMITED,entity,NaN,6.984126e+10,NaN,typo,10086864

In [113]:
df_train.name = df_train.name.astype(str)

In [256]:
n = df_train.loc[0,'name']
for (rid, row) in tqdm(zip(df_train.record_id, df_train.name)):
    """
    if len(n)>3 and len(row)>3:
        if n[0] != row[0] and n[1] != row[1] and n[2] != row[2]:
            pass
        else:
            dist = editdistance.eval(n, row)
            if dist < 5:
                print(f"{rid} - {row} - {dist}")
    else:
        if editdistance.eval(n, row) < 5:
                print(f"{rid} - {row} - {dist}")
    """
    if editdistance.eval(n, row) < 5:
                print(f"{rid} - {row} - {dist}")

HBox(children=(IntProgress(value=1, bar_style='info', max=1), HTML(value='')))

10111147-T1 - ArDIA ENTERPRISESmLTD. - 23
10203352-M0 - EDINA ENTERPRISES LTD. - 23
10144404 - ORDIN ENTERPRISES LTD. - 23
12135009 - ALDIA ENTERPRISES LTD. - 23
10111147-M2 - ALDIA ENTERPRISES LTD. - 23
10138278-M1 - ORDIN ENTERPRISES LTD. - 23
10111147 - ALDIA ENTERPRISES LTD. - 23
10102816-NV2 - ARDIS ENTERPRISES LTD. - 23
10111147-M0 - ALDIA ENTERPRISES LTD. - 23
10111147-T2 - ALDIA ENTERPRISES LTD. - 23
10138278-M2 - ORDIN ENTERPRISES LTD. - 23
10111147-M1 - ALDIA ENTERPRISES LTD. - 23
10138278-M0 - ORDIN ENTERPRISES LTD. - 23
10144404-NV1 - ORDIN ENTERPRISES LTD. - 23
10138278 - ORDIN ENTERPRISES LTD. - 23
10102816-M0 - ARDIS ENTERPRISES LTD. - 23
10123421 - ATRIA ENTERPRISES LTD. - 23
10102816 - ARDIS ENTERPRISES LTD. - 23
10203352 - EDINA ENTERPRISES LTD. - 23
10102816-NV0 - ARDIS ENTERPRISES LTD. - 23
10123421-NV1 - ATRIA ENTERPRISES LTD. - 23
10102816-NV1 - ARDIS ENTERPRISES LTD. - 23
10144404-NV2 - ORDIN ENTERPRISES LTD. - 23
10144404-NV0 - ORDIN ENTERPRISES LTD. - 23
10090247 - ADCO ENTERPRISES LTD. - 23
10123421-NV0 - ATRIA ENTERPRISES LTD. - 23

In [115]:
df_train[df_train.linked_id == 10111147]

,record_id,name,type,address,phone,email,modification,linked_id
0,10111147-T1,ArDIA ENTERPRISESmLTD.,entity,NaN,4.102971e+12,imquires@zoho.vo,typo,10111147
81089,10111147-M2,ALDIA ENTERPRISES LTD.,entity,NaN,NaN,NaN,missing,10111147
115734,10111147,ALDIA ENTERPRISES LTD.,entity,NaN,4.102971e+12,inquires@zoho.it,original,10111147
169096,10111147-M0,ALDIA ENTERPRISES LTD.,entity,NaN,NaN,NaN,missing,10111147
270623,10111147-T2,ALDIA ENTERPRISES LTD.,entity,NaN,4.102971e+12,inquires@zhho.it,typo,10111147
303571,10111147-M1,ALDIA ENTERPRISES LTD.,entity,NaN,4.102971e+12,inquires@zoho.it,missing,10111147

In [116]:
df_train[df_train.record_id == '12135009']

,record_id,name,type,address,phone,email,modification,linked_id
64901,12135009,ALDIA ENTERPRISES LTD.,officer,AKARA BLDG.; 24 DE CASTRO STREET WICKHAMS CAY ...,NaN,NaN,original,12135009

In [233]:
col = df_train.name.str.lower()
col

0                                    ardia enterprisesmltd.
1                                      andrÃ© almeida blanco
2                                      moonta holdings ltd.
3                     springfield investments group limited
4                                            grigory uvarov
5                               odin group investments s.a.
6                                   capri solutions limited
7                                           crossmatch s.a.
8                                     laurence pountney ltd
9                                             breit, marcus
10                           afccotrade international corp.
11                                 commtech foundation inc.
12                                 brotherhood foundation..
13                           yury valentinovich tskhovrebov
14                                               li guobang
15                                           zucean limited
16                                   longxi investment ltd.
17                                               refik arif
18                           unicorn ifvestment corporation
19                                 sandro botticelli, corp.
20        ali ahmed darrat, najib ahmed darrat, ahmed aa...
21                                            alimh limited
22                                     gustavo soto montiel
23        investec trustees (jersey) limited as the nomi...
24                                            chen qingtian
25                                     santiago peÃ±a durini
26                                             lio wen tong
27                                              gefion inc.
28                                            wang hong jun
29                                         spirit ride s.a.
                                ...
691410                                          sasha naido
691411                               unica lighting limited
691412                            stirling trustees limited
691413                      clarity capital management inc.
691414                                        liaw, lih-ing
691415                          voltweb investments limited
691416                       pcveril propertibs corporatiwn
691417                                     beatrice chasima
691418                      hanborough investors group inc.
691419                                    canno invest incc
691420                      szarp power investmmnts limited
691421                                          eli israeli
691422                            carrel properties limited
691423                              chelco nosinbes limited
691424                              ho yee investments ltd.
691425                                 arts &nmusic limited
691426                                    beadswell limited
691427                              kallang trading limited
691428                           new growth technology ltd.
691429                               bradcliffe corporation
691430                         multi sound investments ltd.
691431                                  viton business s.a.
691432                                        taryn limited
691433                        bos nominees (jersey) limited
691434                         experta ag   (zurich client)
691435                                    guy paul cosemans
691436                            anthony chiang & partners
691437                                  dennison group inc.
691438                      harvest top enterprises limited
691439                                    unthony pickering
Name: name, Length: 691440, dtype: object

In [244]:
blacklist = [' ltd ', ' ltd.', ' ltd', 'enterprises', 'enterprise', ' limited', ' limited ', ' inc ', ' inc. ', ' inc.', 
            ' s.a. ', ' s.a.', 'international', 'holdings', 'investments', ' corp.', ' corp. ', 'corp. ', ' investment ', 
             ' investment', 'investment ', ' management ', 'management ', ' management', 'development', ' group ', ' group',
             'group ', ' trading', ' trading ', 'trading ', ' services', 'services ', ' services', ' holding', ' holding ', 
             'holding ']
for w in tqdm(blacklist):
    col = col.str.replace(w, ' ')
col

HBox(children=(IntProgress(value=0, max=28), HTML(value='')))

0                                              ardia  mltd.
1                                      andrÃ© almeida blanco
2                                                 moonta
3                                            springfield
4                                            grigory uvarov
5                                                   odin
6                                          capri solutions
7                                               crossmatch
8                                        laurence pountney
9                                             breit, marcus
10                                            afccotrade
11                                     commtech foundation
12                                 brotherhood foundation..
13                           yury valentinovich tskhovrebov
14                                               li guobang
15                                                  zucean
16                                                  longxi
17                                               refik arif
18                                unicorn ifvestment ration
19                                      sandro botticelli,
20        ali ahmed darrat, najib ahmed darrat, ahmed aa...
21                                                   alimh
22                                     gustavo soto montiel
23        investec trustees (jersey)  as the nominee for...
24                                            chen qingtian
25                                     santiago peÃ±a durini
26                                             lio wen tong
27                                                  gefion
28                                            wang hong jun
29                                             spirit ride
                                ...
691410                                          sasha naido
691411                                      unica lighting
691412                                   stirling trustees
691413                                     clarity capital
691414                                        liaw, lih-ing
691415                                           voltweb
691416                            pcveril propertibs ratiwn
691417                                     beatrice chasima
691418                                hanborough investors
691419                                        canno invest
691420                             szarp power investmmnts
691421                                          eli israeli
691422                                   carrel properties
691423                                     chelco nosinbes
691424                                            ho yee
691425                                        arts &nmusic
691426                                           beadswell
691427                                     kallang trading
691428                               new growth technology
691429                                    bradcliffe ration
691430                                       multi sound
691431                                      viton business
691432                                               taryn
691433                               bos nominees (jersey)
691434                         experta ag   (zurich client)
691435                                    guy paul cosemans
691436                            anthony chiang & partners
691437                                            dennison
691438                                       harvest top
691439                                    unthony pickering
Name: name, Length: 691440, dtype: object

In [249]:
punct_black_list = ["'", ".", ",", "(",")"]
for p in tqdm(punct_black_list):
    col = col.str.replace(p, ' ')
col

HBox(children=(IntProgress(value=0, max=5), HTML(value='')))

0                                              ardia  mltd
1                                      andrÃ© almeida blanco
2                                                 moonta
3                                            springfield
4                                            grigory uvarov
5                                                   odin
6                                          capri solutions
7                                               crossmatch
8                                        laurence pountney
9                                             breit  marcus
10                                            afccotrade
11                                     commtech foundation
12                                 brotherhood foundation
13                           yury valentinovich tskhovrebov
14                                               li guobang
15                                                  zucean
16                                                  longxi
17                                               refik arif
18                                unicorn ifvestment ration
19                                      sandro botticelli
20        ali ahmed darrat  najib ahmed darrat  ahmed aa...
21                                                   alimh
22                                     gustavo soto montiel
23        investec trustees  jersey   as the nominee for...
24                                            chen qingtian
25                                     santiago peÃ±a durini
26                                             lio wen tong
27                                                  gefion
28                                            wang hong jun
29                                             spirit ride
                                ...
691410                                          sasha naido
691411                                      unica lighting
691412                                   stirling trustees
691413                                     clarity capital
691414                                        liaw  lih-ing
691415                                           voltweb
691416                            pcveril propertibs ratiwn
691417                                     beatrice chasima
691418                                hanborough investors
691419                                        canno invest
691420                             szarp power investmmnts
691421                                          eli israeli
691422                                   carrel properties
691423                                     chelco nosinbes
691424                                            ho yee
691425                                        arts &nmusic
691426                                           beadswell
691427                                     kallang trading
691428                               new growth technology
691429                                    bradcliffe ration
691430                                       multi sound
691431                                      viton business
691432                                               taryn
691433                               bos nominees  jersey
691434                         experta ag    zurich client
691435                                    guy paul cosemans
691436                            anthony chiang & partners
691437                                            dennison
691438                                       harvest top
691439                                    unthony pickering
Name: name, Length: 691440, dtype: object

In [250]:
col_str = ' '.join(col.tolist())
col_str[:20]

'ardia  mltd  andrÃ© a'

In [251]:
from collections import Counter

In [252]:
split_it = col_str.split() 
c = Counter(split_it)

In [253]:
c.most_common(50)

[('co', 16598),
 ('trading', 16170),
 ('services', 14887),
 ('ration', 14524),
 ('mr', 13374),
 ('company', 13098),
 ('&', 12113),
 ('trust', 11361),
 ('nominees', 11314),
 ('foundation', 10051),
 ('holding', 9222),
 ('properties', 8271),
 ('finance', 8072),
 ('s', 7970),
 ('the', 7909),
 ('capital', 7511),
 ('a', 7195),
 ('global', 7052),
 ('of', 6876),
 ('and', 6094),
 ('de', 6074),
 ('trustees', 5694),
 ('consultants', 5161),
 ('as', 5059),
 ('associates', 4816),
 ('overseas', 4748),
 ('li', 4505),
 ('assets', 4198),
 ('wang', 4107),
 ('business', 3883),
 ('consulting', 3785),
 ('chen', 3645),
 ('property', 3163),
 ('equities', 3145),
 ('c', 3134),
 ('trustee', 3106),
 ('zhang', 3056),
 ('mrs', 2900),
 ('l', 2873),
 ('technology', 2872),
 ('maria', 2820),
 ('financial', 2747),
 ('trade', 2744),
 ('rporated', 2662),
 ('m', 2647),
 ('resources', 2643),
 ('pacific', 2630),
 ('i', 2615),
 ('b', 2535),
 ('marketing', 2510)]