In [2]:
import pandas as pd
import numpy as np
from tqdm.auto import tqdm

In [3]:
df_test = pd.read_csv("../dataset/original/test.csv", escapechar="\\")
sub = pd.read_csv("/Users/alessiorussointroito/Downloads/sub_prova.csv.xls")

In [4]:
df_test['linked_id'] = df_test.record_id.str.split("-")
df_test['linked_id'] = df_test.linked_id.apply(lambda x: x[0])

In [5]:
sub['predicted_record_id'] = sub.predicted_record_id.str.split(" ")

In [6]:
sub = sub.merge(df_test[['record_id', 'linked_id']], how='left', left_on='queried_record_id', right_on="record_id")

In [7]:
sub

,queried_record_id,predicted_record_id,record_id,linked_id
0,10000003-TST-MR,"[10079611, 10079611, 10025651, 10079611, 10079...",10000003-TST-MR,10000003
1,10000008-TST-M,"[10043172, 10043172, 10043172, 10107096, 10007...",10000008-TST-M,10000008
2,10000010-TST-CP,"[10000010, 10192342, 10118218, 10112963, 10112...",10000010-TST-CP,10000010
3,10000013-TST-MR,"[10111503, 10037360, 10037360, 11012344, 11012...",10000013-TST-MR,10000013
4,10000016-TST-MR,"[10012410, 10104833, 10113928, 10008013, 10094...",10000016-TST-MR,10000016
5,10000017-TST-MR,"[10038004, 10038004, 10155088, 10155088, 10155...",10000017-TST-MR,10000017
6,10000018-T4-TST-CP,"[10000018, 10000018, 10000018, 10000018, 10000...",10000018-T4-TST-CP,10000018
7,10000018-TST-M,"[10000018, 10000018, 10000018, 10000018, 10000...",10000018-TST-M,10000018
8,10000020-NV0-TST-CP,"[10000020, 10000020, 10000020, 10151492, 10094...",10000020-NV0-TST-CP,10000020
9,10000020-NV1-TST-M,"[10000020, 10000020, 10000020, 10151492, 10094...",10000020-NV1-TST-M,10000020
10,10000022-TST-CP,"[10000022, 10213858, 10213858, 10138013, 10138...",10000022-TST-CP,10000022
11,10000023-NV2-TST-CP,"[10000023, 10000023, 10000023, 10000023, 10000...",10000023-NV2-TST-CP,10000023
12,10000024-TST-MR,"[10100649, 10100649, 10214082, 10214082, 10214...",10000024-TST-MR,10000024
13,10000025-TST-MR,"[10038568, 10013963, 10188405, 10188405, 10188...",10000025-TST-MR,10000025
14,10000027-M0-TST-M,"[10000027, 10000027, 10000027, 10199071, 10199...",10000027-M0-TST-M,10000027
15,10000027-T0-TST-M,"[10000027, 10000027, 10000027, 10199071, 10199...",10000027-T0-TST-M,10000027
16,10000027-T1-TST-M,"[10000027, 10000027, 10000027, 10199071, 10199...",10000027-T1-TST-M,10000027
17,10000028-TST-MR,"[10069845, 10069845, 10021933, 10021933, 10021...",10000028-TST-MR,10000028
18,10000030-TST-MR,"[10037339, 10037339, 10108191, 10108191, 10017...",10000030-TST-MR,10000030
19,10000031-M2-TST-M,"[10000031, 10000031, 10000031, 10000031, 10000...",10000031-M2-TST-M,10000031
20,10000032-T0-TST-CP,"[10000032, 10133377, 12169459, 12169459, 12169...",10000032-T0-TST-CP,10000032
21,10000032-T1-TST-M,"[10000032, 10000032, 10000032, 10037597, 10037...",10000032-T1-TST-M,10000032
22,10000034-TST-M,"[10119069, 10119069, 10119069, 10119069, 10155...",10000034-TST-M,10000034
23,10000036-NV0-TST-M,"[10000036, 10000036, 10184295, 10184295, 10000...",10000036-NV0-TST-M,10000036
24,10000036-NV1-TST-M,"[10000036, 10000036, 10184295, 10184295, 10000...",10000036-NV1-TST-M,10000036
25,10000036-T0-TST-CP,"[10000036, 10000036, 10184295, 10184295, 10000...",10000036-T0-TST-CP,10000036
26,10000036-TST-M,"[10000036, 10000036, 10184295, 10184295, 10000...",10000036-TST-M,10000036
27,10000037-TST-MR,"[10115101, 10115101, 10115101, 10115101, 10184...",10000037-TST-MR,10000037
28,10000038-TST-MR,"[10136074, 10136074, 10136074, 10201695, 10196...",10000038-TST-MR,10000038
29,10000039-TST-CP,"[10000039, 10000039, 10000039, 10000039, 10137...",10000039-TST-CP,10000039
...,...,...,...,...
266925,13013118-TST-M,"[13013118, 13013118, 12172642, 12152309, 13005...",13013118-TST-M,13013118
266926,13013119-NV0-TST-CP,"[13013119, 13013119, 13013119, 12119080, 12119...",13013119-NV0-TST-CP,13013119
266927,15000601-TST-M,"[12220570, 12220570, 12220570, 12220570, 12220...",15000601-TST-M,15000601
266928,15000801-TST-MR,"[12173945, 13004513, 12033142, 12033142, 12122...",15000801-TST-MR,15000801
266929,15000901-TST-MR,"[12171009, 12171009, 12171009, 12171009, 12171...",15000901-TST-MR,15000901
266930,15001201-NV0,"[15001201, 12182950, 12182950, 12182950, 12156...",15001201-NV0,15001201
266931,15001301-TST-MR,"[12099589, 12099589, 12099589, 12223335, 12223...",15001301-TST-MR,15001301
266932,15001401-M0-TST-CP,"[15001401, 15001401, 15001401, 15001401, 13006...",15001401-M0-TST-CP,15001401
266933,15001401-M2-TST-CP,"[15001401, 15001401, 15001401, 15001401, 13006...",15001401-M2-TST-CP,15001401
266934,15001501-TST-MR,"[12127195, 10155449, 10155449, 10155449, 12212...",15001501-TST-MR,15001501
266935,15001601-T3-TST-CP,"[15001601, 15001601, 15001601, 15001601, 15001...",15001601-T3-TST-CP,15001601
266936,15001801-T0-TST-CP,"[15001801, 15001801, 15001801, 15001801, 12173...",15001801-T0-TST-CP,15001801
266937,15001903-TST-MR,"[15001902, 13010940, 10194204, 10155227, 10213...",15001903-TST-MR,15001903
266938,15002501-M0-TST-M,"[15002501, 12147750, 12147750, 12147750, 12147...",15002501-M0-TST-M,15002501
266939,15003201-TST-MR,"[10136422, 13012749, 13012749, 12218745, 12218...",15003201-TST-MR,15003201
266940,15003301-TST-MR,"[13010454, 12129621, 12129621, 12129621, 12154...",15003301-TST-MR,15003301
266941,15004001-T0-TST-CP,"[15004001, 15004001, 15004001, 15004001, 15004...",15004001-T0-TST-CP,15004001
266942,15004001-T3-TST-M,"[15004001, 15004001, 15004001, 15004001, 15004...",15004001-T3-TST-M,15004001
266943,15004501-TST-MR,"[13009884, 12221762, 12221762, 15003501, 12179...",15004501-TST-MR,15004501
266944,15005002-TST-MR,"[15005001, 15005001, 12157801, 13002420, 13002...",15005002-TST-MR,15005002
266945,15005003-TST-MR,"[13002420, 13002420, 13002420, 13002420, 13002...",15005003-TST-MR,15005003
266946,15005004-TST-M,"[12157087, 12118716, 13002420, 13002420, 13002...",15005004-TST-M,15005004
266947,15005201-TST-MR,"[13006838, 12133298, 12133298, 12133298, 12133...",15005201-TST-MR,15005201
266948,15005401-TST-MR,"[12127195, 12102648, 12102648, 13008843, 13008...",15005401-TST-MR,15005401
266949,15005501-TST-M,"[15005501, 15005501, 15005501, 15005501, 15005...",15005501-TST-M,15005501
266950,15005801-T0-TST-M,"[15005801, 12176471, 12176471, 12176471, 12194...",15005801-T0-TST-M,15005801
266951,15005801-T1-TST-M,"[15005801, 12222620, 12222620, 12222620, 12222...",15005801-T1-TST-M,15005801
266952,15006601-TST-MR,"[12025829, 12025829, 12025829, 12025829, 12190...",15006601-TST-MR,15006601
266953,15006701-TST-CP,"[15006701, 12222118, 12222118, 12222118, 10034...",15006701-TST-CP,15006701
266954,15006801-TST-MR,"[12128834, 12116201, 12116201, 12116201, 12116...",15006801-TST-MR,15006801

In [8]:
def isin_function(pred, linked):
    res = np.empty(len(linked), dtype=int)
    for i in tqdm(range(len(linked))):
        res[i] = np.isin(linked[i], pred[i])
    return res

sub['correct'] = isin_function(sub.predicted_record_id.values, sub.linked_id.values)

HBox(children=(IntProgress(value=0, max=266955), HTML(value='')))

In [9]:
df_train = pd.read_csv("../dataset/original/train.csv", escapechar="\\")

In [10]:
df_train['linked_id'] = df_train.linked_id.astype(int)
df_test['linked_id'] = df_test.linked_id.astype(int)
only_test = set(df_test.linked_id.values) - set(df_train.linked_id.values)

In [11]:
len(only_test)

118112

In [12]:
sub['linked_id'] = sub.linked_id.astype(int)
sub_intrain_too = sub[~sub.linked_id.isin(only_test)]

In [13]:
sub_intrain_too

,queried_record_id,predicted_record_id,record_id,linked_id,correct
2,10000010-TST-CP,"[10000010, 10192342, 10118218, 10112963, 10112...",10000010-TST-CP,10000010,1
6,10000018-T4-TST-CP,"[10000018, 10000018, 10000018, 10000018, 10000...",10000018-T4-TST-CP,10000018,1
7,10000018-TST-M,"[10000018, 10000018, 10000018, 10000018, 10000...",10000018-TST-M,10000018,1
8,10000020-NV0-TST-CP,"[10000020, 10000020, 10000020, 10151492, 10094...",10000020-NV0-TST-CP,10000020,1
9,10000020-NV1-TST-M,"[10000020, 10000020, 10000020, 10151492, 10094...",10000020-NV1-TST-M,10000020,1
10,10000022-TST-CP,"[10000022, 10213858, 10213858, 10138013, 10138...",10000022-TST-CP,10000022,1
11,10000023-NV2-TST-CP,"[10000023, 10000023, 10000023, 10000023, 10000...",10000023-NV2-TST-CP,10000023,1
14,10000027-M0-TST-M,"[10000027, 10000027, 10000027, 10199071, 10199...",10000027-M0-TST-M,10000027,1
15,10000027-T0-TST-M,"[10000027, 10000027, 10000027, 10199071, 10199...",10000027-T0-TST-M,10000027,1
16,10000027-T1-TST-M,"[10000027, 10000027, 10000027, 10199071, 10199...",10000027-T1-TST-M,10000027,1
19,10000031-M2-TST-M,"[10000031, 10000031, 10000031, 10000031, 10000...",10000031-M2-TST-M,10000031,1
20,10000032-T0-TST-CP,"[10000032, 10133377, 12169459, 12169459, 12169...",10000032-T0-TST-CP,10000032,1
21,10000032-T1-TST-M,"[10000032, 10000032, 10000032, 10037597, 10037...",10000032-T1-TST-M,10000032,1
23,10000036-NV0-TST-M,"[10000036, 10000036, 10184295, 10184295, 10000...",10000036-NV0-TST-M,10000036,1
24,10000036-NV1-TST-M,"[10000036, 10000036, 10184295, 10184295, 10000...",10000036-NV1-TST-M,10000036,1
25,10000036-T0-TST-CP,"[10000036, 10000036, 10184295, 10184295, 10000...",10000036-T0-TST-CP,10000036,1
26,10000036-TST-M,"[10000036, 10000036, 10184295, 10184295, 10000...",10000036-TST-M,10000036,1
29,10000039-TST-CP,"[10000039, 10000039, 10000039, 10000039, 10137...",10000039-TST-CP,10000039,1
30,10000040-T0-TST-M,"[10000040, 10000040, 10000040, 10000040, 10026...",10000040-T0-TST-M,10000040,1
35,10000045-TST-CP,"[10000045, 10149680, 10016923, 10016923, 10139...",10000045-TST-CP,10000045,1
36,10000046-TST-M,"[10000046, 10000046, 12131509, 12131509, 10189...",10000046-TST-M,10000046,1
37,10000049-M0-TST-M,"[10000049, 10042161, 10042161, 10042161, 10042...",10000049-M0-TST-M,10000049,1
39,10000051-T0,"[10000051, 10002144, 10191328, 10191328, 10178...",10000051-T0,10000051,1
40,10000051-T1,"[10000051, 10173808, 10178526, 10119601, 10191...",10000051-T1,10000051,1
41,10000051-T2,"[10000051, 10191328, 10105772, 10105772, 10191...",10000051-T2,10000051,1
42,10000053-TST-M,"[10000053, 10000053, 10016191, 10016191, 10000...",10000053-TST-M,10000053,1
43,10000054-NV0-TST-M,"[10000054, 10000054, 10000054, 10000054, 10000...",10000054-NV0-TST-M,10000054,1
46,10000057-TST-CP,"[10000057, 10000057, 10000057, 10114028, 10114...",10000057-TST-CP,10000057,1
47,10000059-TST-M,"[10000059, 10000059, 10000059, 10101989, 10101...",10000059-TST-M,10000059,1
51,10000065-T0-TST-M,"[10000065, 10037661, 10037661, 12195975, 12195...",10000065-T0-TST-M,10000065,1
...,...,...,...,...,...
266900,13013089-NV0-TST-CP,"[13013089, 13013089, 13013089, 13013089, 13013...",13013089-NV0-TST-CP,13013089,1
266901,13013089-T4-TST-CP,"[13013089, 13013089, 13013089, 13013089, 13013...",13013089-T4-TST-CP,13013089,1
266902,13013089-TST-CP,"[13013089, 13013089, 13013089, 13013089, 13013...",13013089-TST-CP,13013089,1
266903,13013092-NV0-TST-M,"[13013092, 13013092, 10197032, 12166772, 12165...",13013092-NV0-TST-M,13013092,1
266904,13013092-TST-CP,"[13013092, 13013092, 12136961, 12136961, 12136...",13013092-TST-CP,13013092,1
266907,13013095-NV0,"[13013095, 12071883, 12071883, 12071883, 11005...",13013095-NV0,13013095,1
266908,13013095-NV1,"[13013095, 11005218, 11005218, 11005218, 12170...",13013095-NV1,13013095,1
266909,13013095-NV2,"[13013095, 11005218, 11005218, 11005218, 12170...",13013095-NV2,13013095,1
266910,13013095-TST-CP,"[13013095, 11005218, 11005218, 11005218, 12170...",13013095-TST-CP,13013095,1
266915,13013105-T0-TST-CP,"[13013105, 13013105, 12223554, 12223554, 12223...",13013105-T0-TST-CP,13013105,1
266916,13013106-TST-M,"[13013106, 12127944, 12127944, 13012135, 13012...",13013106-TST-M,13013106,1
266918,13013114-NV2-TST-M,"[13013114, 13013114, 13013114, 12164673, 12164...",13013114-NV2-TST-M,13013114,1
266919,13013114-TST-CP,"[13013114, 13013114, 13013114, 12164673, 12164...",13013114-TST-CP,13013114,1
266922,13013117-T1-TST-M,"[13013117, 13013117, 13005685, 12149706, 12150...",13013117-T1-TST-M,13013117,1
266923,13013117-TST-M,"[13013117, 13013117, 13005685, 12149706, 12150...",13013117-TST-M,13013117,1
266924,13013118-NV0-TST-CP,"[13013118, 13013118, 12153907, 12153907, 12172...",13013118-NV0-TST-CP,13013118,1
266925,13013118-TST-M,"[13013118, 13013118, 12172642, 12152309, 13005...",13013118-TST-M,13013118,1
266926,13013119-NV0-TST-CP,"[13013119, 13013119, 13013119, 12119080, 12119...",13013119-NV0-TST-CP,13013119,1
266930,15001201-NV0,"[15001201, 12182950, 12182950, 12182950, 12156...",15001201-NV0,15001201,1
266932,15001401-M0-TST-CP,"[15001401, 15001401, 15001401, 15001401, 13006...",15001401-M0-TST-CP,15001401,1
266933,15001401-M2-TST-CP,"[15001401, 15001401, 15001401, 15001401, 13006...",15001401-M2-TST-CP,15001401,1
266935,15001601-T3-TST-CP,"[15001601, 15001601, 15001601, 15001601, 15001...",15001601-T3-TST-CP,15001601,1
266936,15001801-T0-TST-CP,"[15001801, 15001801, 15001801, 15001801, 12173...",15001801-T0-TST-CP,15001801,1
266938,15002501-M0-TST-M,"[15002501, 12147750, 12147750, 12147750, 12147...",15002501-M0-TST-M,15002501,1
266941,15004001-T0-TST-CP,"[15004001, 15004001, 15004001, 15004001, 15004...",15004001-T0-TST-CP,15004001,1
266942,15004001-T3-TST-M,"[15004001, 15004001, 15004001, 15004001, 15004...",15004001-T3-TST-M,15004001,1
266949,15005501-TST-M,"[15005501, 15005501, 15005501, 15005501, 15005...",15005501-TST-M,15005501,1
266950,15005801-T0-TST-M,"[15005801, 12176471, 12176471, 12176471, 12194...",15005801-T0-TST-M,15005801,1
266951,15005801-T1-TST-M,"[15005801, 12222620, 12222620, 12222620, 12222...",15005801-T1-TST-M,15005801,1
266953,15006701-TST-CP,"[15006701, 12222118, 12222118, 12222118, 10034...",15006701-TST-CP,15006701,1

In [14]:
n_rows = sub_intrain_too.shape[0]
n_ones = sub_intrain_too.correct.sum()

n_rows - n_ones

502

In [15]:
sub_intrain_too_wrong = sub_intrain_too[sub_intrain_too.correct == 0]

In [16]:
sub_intrain_too_wrong = sub_intrain_too_wrong.merge(df_test, how='left', on='record_id')

In [17]:
sub_intrain_too_wrong

,queried_record_id,predicted_record_id,record_id,linked_id_x,correct,name,type,address,phone,email,modification,linked_id_y
0,10000510-TST-M,"[10041062, 10041062, 10041062, 10041062, 10041...",10000510-TST-M,10000510,0,SOUND FINANCE LIMITED,entity,NaN,4.205420e+11,NaN,move row,10000510
1,10000641-TST-M,"[10201751, 10201751, 10201751, 10201751, 10201...",10000641-TST-M,10000641,0,A&C LIMITED,entity,NaN,NaN,NaN,move row,10000641
2,10008137-T3-TST-M,"[10044438, 10044438, 10044438, 10201569, 10183...",10008137-T3-TST-M,10008137,0,LALKq INC.,entity,NaN,3.110250e+09,NaN,move row,10008137
3,10008437-T0-TST-M,"[10183961, 10183961, 10169028, 10169028, 10169...",10008437-T0-TST-M,10008437,0,cISyINVESTMENTS iNC.,entity,NaN,4.209616e+11,NaN,move row,10008437
4,10014653-T2-TST-M,"[10168310, 10168310, 12105420, 12045562, 12007...",10014653-T2-TST-M,10014653,0,2f Ckrm.,entity,NaN,1.670215e+10,NaN,move row,10014653
5,10015579-TST-M,"[12090850, 12090850, 10096288, 10096288, 10096...",10015579-TST-M,10015579,0,DALCAN INC.,entity,NaN,4.202455e+11,NaN,move row,10015579
6,10016634-T4-TST-M,"[10045456, 10045456, 10045456, 10045456, 10145...",10016634-T4-TST-M,10016634,0,VOeAp f.A.,entity,NaN,NaN,NaN,move row,10016634
7,10022165-TST-M,"[10103533, 10026718, 10026718, 10038233, 10038...",10022165-TST-M,10022165,0,NATA LIMITED,entity,NaN,4.410934e+11,NaN,move row,10022165
8,10024343-T2-TST-M,"[10179670, 10179670, 12125729, 12125729, 10086...",10024343-T2-TST-M,10024343,0,FAyHOy fOLDINGS LTD.,entity,NaN,3.910990e+09,NaN,move row,10024343
9,10024604-T1-TST-M,"[10197677, 10197677, 10127908, 10209267, 10051...",10024604-T1-TST-M,10024604,0,COlPIs MANAGEMENT S.v.,entity,NaN,3.302186e+11,NaN,move row,10024604
10,10026715-T0,"[10068265, 10068265, 10068265, 10128830, 10128...",10026715-T0,10026715,0,FRtbq LIMITED,entity,NaN,4.903936e+10,NaN,modified copy,10026715
11,10027844-TST-M,"[10095155, 10200858, 10101261, 10101261, 10101...",10027844-TST-M,10027844,0,SORAS S.A.,entity,NaN,4.442040e+11,NaN,move row,10027844
12,10030375-TST-M,"[10017541, 10007872, 10055350, 10017541, 10007...",10030375-TST-M,10030375,0,IMERINA INC.,entity,NaN,4.491173e+11,consulting@protonmail.it,move row,10030375
13,10031808-TST-M,"[10021763, 10054033, 10104282, 10054033, 10054...",10031808-TST-M,10031808,0,IPRON CORP.,entity,NaN,1.480367e+10,NaN,move row,10031808
14,10033104-NV0-TST-M,"[10059434, 10050596, 10100643, 10058583, 10058...",10033104-NV0-TST-M,10033104,0,BAYTOWN PROPERTIES LTD.,entity,Level 5 Development; Bank of Samoa Building; B...,NaN,consulting@protonmail.de,move row,10033104
15,10033104-TST-M,"[10050596, 10059434, 10100643, 10174458, 10174...",10033104-TST-M,10033104,0,BAYTOWN PROPERTIES LTD.,entity,NaN,NaN,NaN,move row,10033104
16,10037204-TST-M,"[10091688, 10170991, 10214241, 10061501, 10109...",10037204-TST-M,10037204,0,SKYMASTER INTERNATIONAL LTD.,entity,NaN,3.357741e+11,info@SKYMASTER.INTERNATIONAL.LTD.gov,move row,10037204
17,10038088-T1-TST-M,"[10077394, 10077394, 10211345, 10211345, 10211...",10038088-T1-TST-M,10038088,0,PENvdD HOLDINGSfINC.,entity,NaN,NaN,NaN,move row,10038088
18,10039345-T1-TST-M,"[10044233, 10035882, 10035882, 10035882, 10035...",10039345-T1-TST-M,10039345,0,LeNbOSgGROUP S.A.,entity,NaN,4.798598e+12,NaN,move row,10039345
19,10039345-TST-M,"[10044233, 10044233, 10031417, 10031417, 10031...",10039345-TST-M,10039345,0,LANCOS GROUP S.A.,entity,NaN,4.198598e+12,NaN,move row,10039345
20,10042543-T1-TST-M,"[10012599, 10011590, 10012599, 10014136, 10014...",10042543-T1-TST-M,10042543,0,NExSOk INVESTMENTS INC.,entity,NaN,3.924573e+09,NaN,move row,10042543
21,10042556-T0-TST-M,"[10035499, 10003618, 10035499, 10003618, 10003...",10042556-T0-TST-M,10042556,0,WINSLAeD hNTERPpISES LIMITED,entity,NaN,3.203825e+11,NaN,move row,10042556
22,10045456-T1-TST-M,"[10040528, 10040528, 10040257, 10040257, 10181...",10045456-T1-TST-M,10045456,0,fBq SkA.,entity,NaN,NaN,NaN,move row,10045456
23,10058463-TST-M,"[10089822, 12222868, 12222868, 12222868, 12222...",10058463-TST-M,10058463,0,LANHILL INVESTMENTS LTD.,entity,NaN,NaN,NaN,move row,10058463
24,10058882-TST-M,"[10017664, 10037456, 10037456, 12224113, 10173...",10058882-TST-M,10058882,0,CEDROS LTD.,entity,NaN,NaN,NaN,move row,10058882
25,10059190-TST-M,"[10108997, 10108997, 10175069, 10091446, 10091...",10059190-TST-M,10059190,0,LION ROCK INTERNATIONAL LIMITED,entity,NaN,4.929858e+10,info@icloud.cz,move row,10059190
26,10059843-T1,"[10147257, 10147257, 10073428, 12192734, 12192...",10059843-T1,10059843,0,GAhcISOj HOLDINGS LIMITED,entity,NaN,3.201587e+11,NaN,modified copy,10059843
27,10059872-TST-M,"[10111414, 10111414, 10111414, 10177857, 10177...",10059872-TST-M,10059872,0,HEMSLEY CONSULTANTS LIMITED,entity,NaN,NaN,NaN,move row,10059872
28,10063048-T1-TST-M,"[10060945, 10060945, 10060945, 10090997, 10090...",10063048-T1-TST-M,10063048,0,DEaOsE jOLDING LTD.,entity,NaN,6.159676e+10,NaN,move row,10063048
29,10067579-T0-TST-M,"[10071484, 10071484, 10171261, 10171261, 10171...",10067579-T0-TST-M,10067579,0,WEBFIELD LIMITED,entity,NaN,NaN,NaN,move row,10067579
...,...,...,...,...,...,...,...,...,...,...,...,...
472,12204935-TST-M,"[12194607, 12000578, 12000578, 12173233, 12156...",12204935-TST-M,12204935,0,GU WEI,officer,Room 1103; Building A5; Shenye Garden; Futian ...,NaN,NaN,move row,12204935
473,12205696-M1-TST-M,"[12190523, 12190523, 12190523, 12192588, 12192...",12205696-M1-TST-M,12205696,0,RICHMOND NOMINEES LIMITED,officer,NaN,NaN,NaN,move row,12205696
474,12206203-T1-TST-M,"[12208958, 13009835, 13009835, 13009835, 13009...",12206203-T1-TST-M,12206203,0,HwANG YUWEI,officer,Room 302; Unit 1; Building 8; Huayuanxincun No...,8.202967e+11,NaN,move row,12206203
475,12206203-TST-M,"[12173928, 12173928, 12105011, 12215318, 12215...",12206203-TST-M,12206203,0,HUANG YUWEI,officer,Room 302; Unit 1; Building 8; Huayuanxincun No...,4.202977e+11,NaN,move row,12206203
476,12207926-TST-M,"[12184016, 12184016, 12184016, 12184016, 12184...",12207926-TST-M,12207926,0,ZHOU JIAN JUN,officer,ROOM 408; BUILDING 1; NING ZHOU YU CUN; JIANG ...,3.959381e+09,ZHOUJIANJUN@hotmail.gov,move row,12207926
477,12208274-TST-M,"[12221259, 13012250, 12221259, 13012250, 13012...",12208274-TST-M,12208274,0,CHENG Hui,officer,Room 3403; 34/F.; China Resources Building; 26...,4.200878e+11,NaN,move row,12208274
478,12208688-M0-TST-M,"[12224899, 12224899, 12224899, 12224899, 12224...",12208688-M0-TST-M,12208688,0,MARKHAM FINANCIAL SERVICES CORP.,officer,NaN,NaN,NaN,move row,12208688
479,12209161-M0-TST-M,"[12215197, 12215197, 12151075, 12151075, 12151...",12209161-M0-TST-M,12209161,0,INTERCON NOMINEES LIMITED,officer,NaN,NaN,NaN,move row,12209161
480,12209893-M1-TST-M,"[12170860, 12170860, 12170860, 12029264, 12029...",12209893-M1-TST-M,12209893,0,Nomihold Securities Inc.,officer,NaN,NaN,NaN,move row,12209893
481,12213080-NV0-TST-M,"[12167447, 12167447, 12147347, 12147347, 12147...",12213080-NV0-TST-M,12213080,0,BEARER,officer,Room1105; Building 5; No. 18; Middle Donghai R...,NaN,NaN,move row,12213080
482,12213082-M1-TST-CP,"[12084750, 12086703, 12084493, 12084493, 12088...",12213082-M1-TST-CP,12213082,0,BEARER,officer,NaN,NaN,NaN,identical copy,12213082
483,12213151-M0,"[12214607, 12214607, 12214607, 12214607, 12214...",12213151-M0,12213151,0,PARTLAW FOUNDATION,officer,NaN,NaN,NaN,modified copy,12213151
484,12213151-M2,"[12214607, 12214607, 12214607, 12214607, 12214...",12213151-M2,12213151,0,PARTLAW FOUNDATION,officer,NaN,NaN,NaN,modified copy,12213151
485,12214901-NV1-TST-M,"[12201241, 12216205, 12216205, 12216205, 12216...",12214901-NV1-TST-M,12214901,0,SCIVIAS TRUST MANAGEMENT LTD.,officer,CANNON'S COURT; 22 VICTORIA STREET; CORPORATIO...,NaN,sales@SCIVIAS.TRUST.MANAGEMENT.LTD.it,move row,12214901
486,12215529-M0-TST-M,"[12152488, 12152488, 12152488, 12202386, 12162...",12215529-M0-TST-M,12215529,0,INTERCON LIMITED,officer,NaN,NaN,NaN,move row,12215529
487,12215845-M1-TST-M,"[10021617, 12006771, 12161345, 12161345, 12161...",12215845-M1-TST-M,12215845,0,TREX LIMITED,officer,NaN,NaN,NaN,move row,12215845
488,12216202-M0-TST-M,"[12214899, 12214899, 12214899, 12216242, 12220...",12216202-M0-TST-M,12216202,0,SCIVIAS TRUST MANAGEMENT LTD,officer,NaN,NaN,NaN,move row,12216202
489,12216799-M0-TST-M,"[12162148, 12153551, 12153551, 12152737, 12152...",12216799-M0-TST-M,12216799,0,FORMIA LIMITED,officer,NaN,NaN,NaN,move row,12216799
490,12217007-M1-TST-M,"[12164165, 12164165, 12216977, 12216977, 12216...",12217007-M1-TST-M,12217007,0,Formia Limited,officer,NaN,NaN,NaN,move row,12217007
491,12217023-M0-TST-M,"[12215965, 12215965, 12215965, 12097242, 12097...",12217023-M0-TST-M,12217023,0,Moscrip Limited,officer,NaN,NaN,NaN,move row,12217023
492,12217275-M0-TST-M,"[12164980, 12165619, 12165619, 12155875, 12155...",12217275-M0-TST-M,12217275,0,BROCK NOMINEES LIMITED,officer,NaN,NaN,NaN,move row,12217275
493,12217491-NV1-TST-M,"[12140952, 12140952, 12140777, 12140777, 12140...",12217491-NV1-TST-M,12217491,0,Bearer,officer,Rincon 531 Of. 502 - Montevideo - Uruguay,NaN,NaN,move row,12217491
494,12218342-M0-TST-M,"[10186308, 10186308, 10186308, 10186308, 12216...",12218342-M0-TST-M,12218342,0,CIVORIET LIMITED,officer,NaN,NaN,NaN,move row,12218342
495,12220603-M1-TST-M,"[12216089, 12216089, 12216089, 12216089, 12216...",12220603-M1-TST-M,12220603,0,MONTAGUE GOLDSMITH INVESTCO ANSTALT,officer,NaN,NaN,NaN,move row,12220603
496,12222050-M0-TST-CP,"[12084750, 12086703, 12084493, 12084493, 12088...",12222050-M0-TST-CP,12222050,0,BEARER,officer,NaN,NaN,NaN,identical copy,12222050
497,12222426-M1-TST-M,"[12214599, 12214599, 12214599, 12224177, 12224...",12222426-M1-TST-M,12222426,0,Aquitaine Nominees Limited,officer,NaN,NaN,NaN,move row,12222426
498,12223090-M0-TST-CP,"[12004095, 12004095, 12203950, 12203950, 12203...",12223090-M0-TST-CP,12223090,0,SERANGOON LIMITED,officer,NaN,NaN,NaN,identical copy,12223090
499,12223590-M2-TST-M,"[12219631, 12219631, 12219631, 12168862, 12168...",12223590-M2-TST-M,12223590,0,BOS NOMINEES (JERSEY) LIMITED,officer,NaN,NaN,NaN,move row,12223590
500,12225127-NV0-TST-M,"[12210286, 12210286, 12210286, 12209771, 12043...",12225127-NV0-TST-M,12225127,0,NWT NOMINEES LIMITED,officer,KENDRIS PRIVATE LTD. CASE POSTALE 2701 5001 AARAU,NaN,NaN,move row,12225127
501,13002934-M1-TST-CP,"[12220238, 12220238, 12220238, 12220238, 12187...",13002934-M1-TST-CP,13002934,0,WANG YING,officer,NaN,NaN,NaN,identical copy,13002934

In [18]:
# predicted
df_train[df_train.linked_id.isin(sub_intrain_too_wrong.loc[3,'predicted_record_id'])]

,record_id,name,type,address,phone,email,modification,linked_id
45220,10169028,CH INVESTMENTS INC.,entity,NaN,4.185382e+12,NaN,original,10169028
96869,10169028-NV2,CH INVESTMENTS INC.,entity,ROOM 407; UNIT 2; BLOCK 6; YU LING GARDEN; MEI...,4.185382e+12,NaN,new_value,10169028
138854,10169028-NV1,CH INVESTMENTS INC.,entity,NaN,4.485355e+11,info@CH.INVESTMENTS.INC.it,new_value,10169028
262217,10006372-NV1,CFI INVESTMENTS INC.,entity,NaN,4.205789e+11,consulting@zoho.it,new_value,10006372
339638,10006372-NV0,CFI INVESTMENTS INC.,entity,NaN,4.205789e+11,consulting@zoho.it,new_value,10006372
404875,10006372,CFI INVESTMENTS INC.,entity,NaN,4.117891e+12,consulting@zoho.it,original,10006372
465677,10183247,COG INVESTMENTS INC.,entity,NaN,NaN,sales@icloud.it,original,10183247
476435,10169028-NV0,CH INVESTMENTS INC.,entity,NaN,4.185382e+12,NaN,new_value,10169028
567916,10183961-NV0,CSU INVESTMENTS INC.,entity,NaN,1.912449e+10,NaN,new_value,10183961
606663,10109926,GTS INVESTMENTS INC.,entity,NaN,4.200224e+11,inquires@zoho.de,original,10109926
652116,10181510,MT INVESTMENTS INC.,entity,NaN,4.203303e+11,NaN,original,10181510
668267,10006372-NV2,CFI INVESTMENTS INC.,entity,NaN,4.117891e+12,contact@outlook.gov,new_value,10006372
688171,10183961,CSU INVESTMENTS INC.,entity,NaN,1.912449e+10,NaN,original,10183961

In [19]:
# real
df_train[df_train.linked_id == 10008437]

,record_id,name,type,address,phone,email,modification,linked_id
31792,10008437-T4,AIS INVESTMENTS INC.,entity,NaN,4.209616e+11,NaN,typo,10008437
97040,10008437,AIS INVESTMENTS INC.,entity,NaN,4.209616e+11,NaN,original,10008437
115868,10008437-T3,AIS INVESTMENTS INC.,entity,NaN,4.002616e+11,NaN,typo,10008437
272568,10008437-T1,kdS INVuSTMENTS INC.,entity,NaN,4.109616e+11,NaN,typo,10008437
489674,10008437-T2,AIS INVESTMENTS INC.,entity,NaN,4.209616e+11,NaN,typo,10008437

# Quanti linked_id non sono nelle top50

In [20]:
scores = pd.read_csv("/Users/alessiorussointroito/Downloads/Telegram Desktop/lgb_predictions_full.csv")

In [21]:
scores.ordered_scores = [eval(x) for x in scores.ordered_scores]
scores.ordered_linked = [eval(x) for x in scores.ordered_linked]
scores.ordered_record = [eval(x) for x in scores.ordered_record]

In [22]:
scores = scores.merge(df_test[['record_id', 'linked_id']], how='left', left_on='queried_record_id', right_on="record_id")

In [23]:
scores['correct'] = isin_function(scores.ordered_linked.values, scores.linked_id.values)

HBox(children=(IntProgress(value=0, max=266955), HTML(value='')))

In [24]:
scores_intrain_too = scores[~scores.linked_id.isin(only_test)]

In [25]:
n_rows = scores_intrain_too.shape[0]
n_ones = scores_intrain_too.correct.sum()

n_rows - n_ones

345

In [26]:
scores_intrain_too_wrong = scores_intrain_too[scores_intrain_too.correct == 0]

In [27]:
scores_intrain_too_wrong = scores_intrain_too_wrong.merge(df_test, how='left', on='record_id')

In [28]:
scores_intrain_too_wrong

,queried_record_id,rec_pred,ordered_linked,ordered_scores,ordered_record,record_id,linked_id_x,correct,name,type,address,phone,email,modification,linked_id_y
0,10000510-TST-M,"[(10041062, 1.4260154893169887, '10041062-T4')...","[10041062, 10041062, 10041062, 10041062, 10041...","[1.4260154893169887, 1.4260154893169887, 1.426...","[10041062-T4, 10041062-T2, 10041062-T0, 100410...",10000510-TST-M,10000510,0,SOUND FINANCE LIMITED,entity,NaN,4.205420e+11,NaN,move row,10000510
1,10000641-TST-M,"[(10097087, -1.7106791052428705, '10097087-NV2...","[10201751, 10201751, 10201751, 10201751, 10201...","[0.2010612301856624, 0.2010612301856624, 0.201...","[10201751, 10201751-M0, 10201751-M1, 10201751-...",10000641-TST-M,10000641,0,A&C LIMITED,entity,NaN,NaN,NaN,move row,10000641
2,10008137-T3-TST-M,"[(10183113, -1.9419071084229058, '10183113-NV0...","[10044438, 10044438, 10044438, 10201569, 10183...","[-0.3114071109322825, -0.3114071109322825, -0....","[10044438, 10044438-M0, 10044438-T1, 10201569-...",10008137-T3-TST-M,10008137,0,LALKq INC.,entity,NaN,3.110250e+09,NaN,move row,10008137
3,10008437-T0-TST-M,"[(10044892, -6.376571856976919, '10044892-T2')...","[10183961, 10183961, 10169028, 10169028, 10169...","[-0.005950306895193134, -0.005950306895193134,...","[10183961, 10183961-NV0, 10169028, 10169028-NV...",10008437-T0-TST-M,10008437,0,cISyINVESTMENTS iNC.,entity,NaN,4.209616e+11,NaN,move row,10008437
4,10014653-T2-TST-M,"[(10137390, -8.959613754079674, '10137390-T1')...","[10168310, 10168310, 12105420, 12045562, 12007...","[-7.372668677219924, -7.372668677219924, -7.79...","[10168310, 10168310-T1, 12105420-T3, 12045562,...",10014653-T2-TST-M,10014653,0,2f Ckrm.,entity,NaN,1.670215e+10,NaN,move row,10014653
5,10015579-TST-M,"[(10096288, -0.1471548713925206, '10096288-M1'...","[12090850, 12090850, 10096288, 10096288, 10096...","[0.08073793588781615, 0.08073793588781615, -0....","[12090850, 12090850-T0, 10096288-M1, 10096288-...",10015579-TST-M,10015579,0,DALCAN INC.,entity,NaN,4.202455e+11,NaN,move row,10015579
6,10016634-T4-TST-M,"[(10145923, -4.6319814807269655, '10145923-T3'...","[10045456, 10045456, 10045456, 10045456, 10145...","[-4.200315028639757, -4.200315028639757, -4.20...","[10045456, 10045456-M0, 10045456-M1, 10045456-...",10016634-T4-TST-M,10016634,0,VOeAp f.A.,entity,NaN,NaN,NaN,move row,10016634
7,10022165-TST-M,"[(10103533, 3.6245821306020045, '10103533'), (...","[10103533, 10026718, 10026718, 10038233, 10038...","[3.6245821306020045, -2.6965656535803717, -2.6...","[10103533, 10026718, 10026718-T0, 10038233-M1,...",10022165-TST-M,10022165,0,NATA LIMITED,entity,NaN,4.410934e+11,NaN,move row,10022165
8,10024343-T2-TST-M,"[(10001533, -6.002704820519322, '10001533'), (...","[10179670, 10179670, 12125729, 12125729, 10086...","[-4.941296771187973, -5.094836155372319, -5.51...","[10179670-M0, 10179670, 12125729-M0, 12125729-...",10024343-T2-TST-M,10024343,0,FAyHOy fOLDINGS LTD.,entity,NaN,3.910990e+09,NaN,move row,10024343
9,10024604-T1-TST-M,"[(12197937, -6.192044424294111, '12197937'), (...","[10197677, 10197677, 10127908, 10209267, 10051...","[-3.924929728342843, -3.924929728342843, -4.53...","[10197677, 10197677-NV0, 10127908, 10209267, 1...",10024604-T1-TST-M,10024604,0,COlPIs MANAGEMENT S.v.,entity,NaN,3.302186e+11,NaN,move row,10024604
10,10026715-T0,"[(10068265, -4.397324468590642, '10068265'), (...","[10068265, 10068265, 10068265, 10128830, 10128...","[-4.397324468590642, -4.397324468590642, -4.39...","[10068265, 10068265-M0, 10068265-M1, 10128830,...",10026715-T0,10026715,0,FRtbq LIMITED,entity,NaN,4.903936e+10,NaN,modified copy,10026715
11,10027844-TST-M,"[(10095155, 0.8231843220573187, '10095155'), (...","[10095155, 10200858, 10101261, 10101261, 10101...","[0.8231843220573187, -2.6358624382697027, -3.2...","[10095155, 10200858, 10101261-T4, 10101261-T2,...",10027844-TST-M,10027844,0,SORAS S.A.,entity,NaN,4.442040e+11,NaN,move row,10027844
12,10030375-TST-M,"[(10021387, -5.258629812238631, '10021387'), (...","[10017541, 10007872, 10055350, 10017541, 10007...","[-3.457967093988446, -3.499531314165354, -3.78...","[10017541-M0, 10007872-NV0, 10055350-NV0, 1001...",10030375-TST-M,10030375,0,IMERINA INC.,entity,NaN,4.491173e+11,consulting@protonmail.it,move row,10030375
13,10031808-TST-M,"[(10021763, 0.26744054729846206, '10021763'), ...","[10021763, 10054033, 10104282, 10054033, 10054...","[0.26744054729846206, -1.6236410276436797, -1....","[10021763, 10054033-M0, 10104282, 10054033-NV1...",10031808-TST-M,10031808,0,IPRON CORP.,entity,NaN,1.480367e+10,NaN,move row,10031808
14,10033104-NV0-TST-M,"[(10060778, -6.171840929039591, '10060778-NV0'...","[10059434, 10050596, 10100643, 10058583, 10058...","[-0.4247645120693663, -2.412013889370496, -3.1...","[10059434, 10050596, 10100643, 10058583, 10058...",10033104-NV0-TST-M,10033104,0,BAYTOWN PROPERTIES LTD.,entity,Level 5 Development; Bank of Samoa Building; B...,NaN,consulting@protonmail.de,move row,10033104
15,10033104-TST-M,"[(10060778, -6.1851160645588745, '10060778-NV0...","[10050596, 10059434, 10100643, 10174458, 10174...","[-1.6189738985097484, -1.9038347233411055, -3....","[10050596, 10059434, 10100643, 10174458-M0, 10...",10033104-TST-M,10033104,0,BAYTOWN PROPERTIES LTD.,entity,NaN,NaN,NaN,move row,10033104
16,10037204-TST-M,"[(10175654, -7.129001646734712, '10175654-T0')...","[10091688, 10170991, 10214241, 10061501, 10109...","[-4.587635305106235, -5.314753215085527, -5.55...","[10091688, 10170991, 10214241-NV1, 10061501, 1...",10037204-TST-M,10037204,0,SKYMASTER INTERNATIONAL LTD.,entity,NaN,3.357741e+11,info@SKYMASTER.INTERNATIONAL.LTD.gov,move row,10037204
17,10038088-T1-TST-M,"[(10053029, -6.845585848657152, '10053029-T0')...","[10077394, 10077394, 10211345, 10211345, 10211...","[-1.4722579941448126, -1.4722579941448126, -1....","[10077394-M0, 10077394, 10211345-T4, 10211345,...",10038088-T1-TST-M,10038088,0,PENvdD HOLDINGSfINC.,entity,NaN,NaN,NaN,move row,10038088
18,10039345-T1-TST-M,"[(10018587, -4.86661264902986, '10018587-T1'),...","[10044233, 10035882, 10035882, 10035882, 10035...","[-4.067385282367649, -4.664806254825586, -4.66...","[10044233-T0, 10035882-M0, 10035882-T3, 100358...",10039345-T1-TST-M,10039345,0,LeNbOSgGROUP S.A.,entity,NaN,4.798598e+12,NaN,move row,10039345
19,10039345-TST-M,"[(10035882, -3.8613460263902986, '10035882-T1'...","[10044233, 10044233, 10031417, 10031417, 10031...","[-1.918826462975707, -1.918826462975707, -2.58...","[10044233-T0, 10044233, 10031417-T4, 10031417-...",10039345-TST-M,10039345,0,LANCOS GROUP S.A.,entity,NaN,4.198598e+12,NaN,move row,10039345
20,10042543-T1-TST-M,"[(10012599, -3.3199543682211585, '10012599'), ...","[10012599, 10011590, 10012599, 10014136, 10014...","[-3.3199543682211585, -5.279584601210808, -5.2...","[10012599, 10011590, 10012599-T0, 10014136-T0,...",10042543-T1-TST-M,10042543,0,NExSOk INVESTMENTS INC.,entity,NaN,3.924573e+09,NaN,move row,10042543
21,10042556-T0-TST-M,"[(10000235, -4.324445851478207, '10000235'), (...","[10035499, 10003618, 10035499, 10003618, 10003...","[-3.419182664728702, -3.419182664728702, -3.41...","[10035499-T1, 10003618-T4, 10035499-T3, 100036...",10042556-T0-TST-M,10042556,0,WINSLAeD hNTERPpISES LIMITED,entity,NaN,3.203825e+11,NaN,move row,10042556
22,10045456-T1-TST-M,"[(10199857, -3.7856779708413657, '10199857-T0'...","[10040528, 10040528, 10040257, 10040257, 10181...","[-1.4199850123644104, -1.4199850123644104, -1....","[10040528-M0, 10040528, 10040257-T3, 10040257-...",10045456-T1-TST-M,10045456,0,fBq SkA.,entity,NaN,NaN,NaN,move row,10045456
23,10058463-TST-M,"[(10129313, -4.231733314355732, '10129313'), (...","[10089822, 12222868, 12222868, 12222868, 12222...","[-2.3566394464854383, -2.71523577631462, -2.71...","[10089822, 12222868-T1, 12222868-M0, 12222868,...",10058463-TST-M,10058463,0,LANHILL INVESTMENTS LTD.,entity,NaN,NaN,NaN,move row,10058463
24,10058882-TST-M,"[(10173619, -2.976466421772776, '10173619'), (...","[10017664, 10037456, 10037456, 12224113, 10173...","[0.07900969287652901, -1.4136015395195642, -1....","[10017664, 10037456-M0, 10037456, 12224113, 10...",10058882-TST-M,10058882,0,CEDROS LTD.,entity,NaN,NaN,NaN,move row,10058882
25,10059190-TST-M,"[(12170782, -6.342248688274179, '12170782'), (...","[10108997, 10108997, 10175069, 10091446, 10091...","[-4.600434573619316, -4.600434573619316, -4.66...","[10108997, 10108997-T0, 10175069, 10091446-T0,...",10059190-TST-M,10059190,0,LION ROCK INTERNATIONAL LIMITED,entity,NaN,4.929858e+10,info@icloud.cz,move row,10059190
26,10059843-T1,"[(10147257, -5.210308091746468, '10147257'), (...","[10147257, 10147257, 10073428, 12192734, 12192...","[-5.210308091746468, -5.210308091746468, -6.34...","[10147257, 10147257-M0, 10073428, 12192734, 12...",10059843-T1,10059843,0,GAhcISOj HOLDINGS LIMITED,entity,NaN,3.201587e+11,NaN,modified copy,10059843
27,10059872-TST-M,"[(10111414, -0.38785363688593694, '10111414'),...","[10111414, 10111414, 10111414, 10177857, 10177...","[-0.38785363688593694, -0.38785363688593694, -...","[10111414, 10111414-M0, 10111414-M1, 10177857,...",10059872-TST-M,10059872,0,HEMSLEY CONSULTANTS LIMITED,entity,NaN,NaN,NaN,move row,10059872
28,10063048-T1-TST-M,"[(10041851, -9.048653323506224, '10041851-T1')...","[10060945, 10060945, 10060945, 10090997, 10090...","[-4.451727768873904, -4.451727768873904, -4.45...","[10060945, 10060945-M1, 10060945-M0, 10090997,...",10063048-T1-TST-M,10063048,0,DEaOsE jOLDING LTD.,entity,NaN,6.159676e+10,NaN,move row,10063048
29,10067579-T0-TST-M,"[(10097445, -3.810181344972152, '10097445'), (...","[10071484, 10071484, 10171261, 10171261, 10171...","[-1.6316069675275178, -1.6316069675275178, -1....","[10071484-T0, 10071484-T1, 10171261-NV1, 10171...",10067579-T0-TST-M,10067579,0,WEBFIELD LIMITED,entity,NaN,NaN,NaN,move row,10067579
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
315,12167446-NV0-TST-M,"[(12084939, -0.9190804045580855, '12084939-M0'...","[12086703, 12084750, 12090283, 12086074, 12086...","[0.30433006004028856, 0.30433006004028856, 0.3...","[12086703, 12084750, 12090283, 12086074, 12086...",12167446-NV0-TST-M,12167446,0,BEARER,officer,BNP PARIBAS WEALTH MANAGEMENT MONACO AVE D'OST...,NaN,NaN,move row,12167446
316,12173678-TST-M,"[(13007569, 2.7773164956312297, '13007569'), (...","[13007569, 12186040, 12203059, 12186040, 12201...","[2.7773164956312297, 1.081000499819812, -0.346...","[13007569, 12186040-M0, 12203059-NV0, 12186040...",12173678-TST-M,12173678,0,WANG LI,officer,NO.60-6-101; LIQUN XIJIE; XINGQING QU; YINCHUA...,4.437665e+11,NaN,move row,12173678
317,12173980-TST-M,"[(12174927, 2.7790546552244915, '12174927'), (...","[12174927, 12173998, 12175856, 12044170, 12044...","[2.7790546552244915, 1.2449484663510737, 0.668...","[12174927, 12173998, 12175856, 12044170, 12044...",12173980-TST-M,12173980,0,CHARITABLE AND GOODWILL FOUNDATION,officer,Mossfon Bldb; 54th Street; Panama; Rep. of Panama,NaN,NaN,move row,12173980
318,12175992-M0-TST-CP,"[(12181846, -1.3409694685538789, '12181846'), ...","[12177326, 12194613, 12194613, 12194613, 12113...","[0.582473054224707, 0.035988721176715414, 0.03...","[12177326-M0, 12194613-M0, 12194613-M1, 121946...",12175992-M0-TST-CP,12175992,0,MINERVA NOMINEES LIMITED,officer,NaN,NaN,NaN,identical copy,12175992
319,12176156-M1-TST-CP,"[(12222238, -1.3294514767033412, '12222238'), ...","[12084750, 12086703, 12084493, 12084493, 12088...","[0.30433006004028856, 0.30433006004028856, 0.0...","[12084750, 12086703, 12084493-M0, 12084493, 12...",12176156-M1-TST-CP,12176156,0,BEARER,officer,NaN,NaN,NaN,identical copy,12176156
320,12176156-TST-M,"[(12084277, -1.2449848753380732, '12084277-M0'...","[12086703, 12084750, 12090283, 12087126, 12084...","[-0.331525339218771, -0.331525339218771, -0.33...","[12086703, 12084750, 12090283, 12087126, 12084...",12176156-TST-M,12176156,0,BEARER,officer,NaN,3.352337e+11,NaN,move row,12176156
321,12176186-M1-TST-M,"[(12222238, -1.3294514767033412, '12222238'), ...","[12084750, 12086703, 12084493, 12084493, 12088...","[0.30433006004028856, 0.30433006004028856, 0.0...","[12084750, 12086703, 12084493-M0, 12084493, 12...",12176186-M1-TST-M,12176186,0,BEARER,officer,NaN,NaN,NaN,move row,12176186
322,12176186-T0,"[(12222238, -1.3294514767033412, '12222238'), ...","[12084750, 12086703, 12084493, 12084493, 12088...","[0.30433006004028856, 0.30433006004028856, 0.0...","[12084750, 12086703, 12084493-M0, 12084493, 12...",12176186-T0,12176186,0,BEARER,officer,NaN,NaN,NaN,modified copy,12176186
323,12176186-T1,"[(12041058, -0.4076575007892698, '12041058-T2'...","[12027390, 12025079, 12025497, 12025497, 12001...","[1.7797815395296825, 1.4052018814200316, 1.386...","[12027390-T0, 12025079-T1, 12025497-M0, 120254...",12176186-T1,12176186,0,BsARnR,officer,NaN,NaN,NaN,modified copy,12176186
324,12176186-T2,"[(12066452, 0.8904900889083488, '12066452-T0')...","[12086074, 12086074, 12086074, 12066452, 12084...","[1.4052018814200316, 1.4052018814200316, 1.405...","[12086074, 12086074-M1, 12086074-M0, 12066452-...",12176186-T2,12176186,0,BrAREx,officer,NaN,NaN,NaN,modified copy,12176186
325,12176186-T3,"[(12222238, -1.3294514767033412, '12222238'), ...","[12084750, 12086703, 12084493, 12084493, 12088...","[0.30433006004028856, 0.30433006004028856, 0.0...","[12084750, 12086703, 12084493-M0, 12084493, 12...",12176186-T3,12176186,0,BEARER,officer,NaN,NaN,NaN,modified copy,12176186
326,12176186-T4,"[(12222238, -1.3294514767033412, '12222238'), ...","[12084750, 12086703, 12084493, 12084493, 12088...","[0.30433006004028856, 0.30433006004028856, 0.0...","[12084750, 12086703, 12084493-M0, 12084493, 12...",12176186-T4,12176186,0,BEARER,officer,NaN,NaN,NaN,modified copy,12176186
327,12176188-TST-M,"[(12085984, -2.146428897807208, '12085984'), (...","[12066456, 12066456, 12109754, 12070233, 12070...","[-0.29508152997183507, -0.29508152997183507, -...","[12066456-M0, 12066456, 12109754-M2, 12070233-...",12176188-TST-M,12176188,0,BEARER,officer,NaN,4.114238e+12,NaN,move row,12176188
328,12178176-M0-TST-CP,"[(12185117, -0.43935537430601923, '12185117-M1...","[12190523, 12190523, 12190523, 12192588, 12192...","[0.10819357797849166, 0.10819357797849166, 0.1...","[12190523-NV1, 12190523-NV0, 12190523-M0, 1219...",12178176-M0-TST-CP,12178176,0,RICHMOND NOMINEES LIMITED,officer,NaN,NaN,NaN,identical copy,12178176
329,12185117-NV0-TST-M,"[(12185076, -0.9773909022784651, '12185076'), ...","[12179362, 12197158, 12197158, 12192637, 12178...","[0.9990979607640849, 0.16850045505636116, 0.16...","[12179362, 12197158-T0, 12197158, 12192637, 12...",12185117-NV0-TST-M,12185117,0,RICHMOND NOMINEES LIMITED,officer,12519 89TH COURT N E KIRKLAND WA 98034-2607,3.933453e+09,NaN,move row,12185117
330,12188348-T1-TST-M,"[(12194437, -0.6736003726229356, '12194437-NV0...","[12194437, 12194437, 12194437, 12194437, 12104...","[-0.17118489057964675, -0.33740299159860604, -...","[12194437-NV1, 12194437-NV2, 12194437-NV0, 121...",12188348-T1-TST-M,12188348,0,Lb PENl,officer,NO.9 iINZHUANG XIANG; RENMIN WpSTcROAD; ZHUCHE...,NaN,NaN,move row,12188348
331,12188348-TST-M,"[(12184243, -1.5214177110423182, '12184243'), ...","[12194437, 12194437, 12194437, 12194437, 12184...","[0.7856276864910066, 0.7421213491477605, 0.068...","[12194437-NV1, 12194437-NV2, 12194437, 1219443...",12188348-TST-M,12188348,0,LI PENG,officer,NO.9 XINZHUANG XIANG; RENMIN WEST ROAD; ZHUCHE...,NaN,NaN,move row,12188348
332,12201206-M0-TST-M,"[(12121269, -0.6670816866224668, '12121269-M2'...","[12162148, 12153551, 12153551, 12152737, 12152...","[-0.05566723384403045, -0.1478995933262812, -0...","[12162148, 12153551-M0, 12153551, 12152737-NV0...",12201206-M0-TST-M,12201206,0,FORMIA LIMITED,officer,NaN,NaN,NaN,move row,12201206
333,12203079-TST-M,"[(12171302, -3.7126105564362404, '12171302-T1'...","[12120137, 12120137, 12120137, 12210871, 12207...","[0.8177454473141661, 0.8177454473141661, -0.31...","[12120137-M0, 12120137-M1, 12120137, 12210871-...",12203079-TST-M,12203079,0,SUN YI,officer,RM. 2505; 411 BUILDING; WANGJING XINCHENG; ZHA...,NaN,NaN,move row,12203079
334,12204935-TST-M,"[(12194607, 0.5306223960064443, '12194607'), (...","[12194607, 12000578, 12000578, 12173233, 12156...","[0.5306223960064443, -1.4204359851043413, -1.4...","[12194607, 12000578-M1, 12000578-M0, 12173233,...",12204935-TST-M,12204935,0,GU WEI,officer,Room 1103; Building A5; Shenye Garden; Futian ...,NaN,NaN,move row,12204935
335,12205696-M1-TST-M,"[(12185117, -0.43935537430601923, '12185117-M1...","[12190523, 12190523, 12190523, 12192588, 12192...","[0.10819357797849166, 0.10819357797849166, 0.1...","[12190523-NV1, 12190523-NV0, 12190523-M0, 1219...",12205696-M1-TST-M,12205696,0,RICHMOND NOMINEES LIMITED,officer,NaN,NaN,NaN,move row,12205696
336,12206203-T1-TST-M,"[(12208958, -3.19313386956619, '12208958'), (1...","[12208958, 13009835, 13009835, 13009835, 13009...","[-3.19313386956619, -3.6423602580006085, -3.64...","[12208958, 13009835-T4, 13009835, 13009835-T0,...",12206203-T1-TST-M,12206203,0,HwANG YUWEI,officer,Room 302; Unit 1; Building 8; Huayuanxincun No...,8.202967e+11,NaN,move row,12206203
337,12206203-TST-M,"[(12202503, -4.973986373064909, '12202503'), (...","[12173928, 12173928, 12105011, 12215318, 12215...","[-1.4839298850027933, -1.4839298850027933, -1....","[12173928-M0, 12173928-M1, 12105011, 12215318-...",12206203-TST-M,12206203,0,HUANG YUWEI,officer,Room 302; Unit 1; Building 8; Huayuanxincun No...,4.202977e+11,NaN,move row,12206203
338,12207926-TST-M,"[(12188509, -3.920705719791938, '12188509'), (...","[12184016, 12184016, 12184016, 12184016, 12184...","[-2.2850279736014794, -2.2850279736014794, -2....","[12184016-M1, 12184016-M0, 12184016-NV0, 12184...",12207926-TST-M,12207926,0,ZHOU JIAN JUN,officer,ROOM 408; BUILDING 1; NING ZHOU YU CUN; JIANG ...,3.959381e+09,ZHOUJIANJUN@hotmail.gov,move row,12207926
339,12208274-TST-M,"[(12221259, -2.536255796128103, '12221259-NV0'...","[12221259, 13012250, 12221259, 13012250, 13012...","[-2.536255796128103, -2.655498254996226, -2.66...","[12221259-NV0, 13012250-M0, 12221259-NV1, 1301...",12208274-TST-M,12208274,0,CHENG Hui,officer,Room 3403; 34/F.; China Resources Building; 26...,4.200878e+11,NaN,move row,12208274
340,12213080-NV0-TST-M,"[(12167412, -0.14787137307772258, '12167412'),...","[12167447, 12167447, 12147347, 12147347, 12147...","[0.47042333109676965, 0.47042333109676965, 0.4...","[12167447, 12167447-T1, 12147347-NV2, 12147347...",12213080-NV0-TST-M,12213080,0,BEARER,officer,Room1105; Building 5; No. 18; Middle Donghai R...,NaN,NaN,move row,12213080
341,12213082-M1-TST-CP,"[(12222238, -1.3294514767033412, '12222238'), ...","[12084750, 12086703, 12084493, 12084493, 12088...","[0.30433006004028856, 0.30433006004028856, 0.0...","[12084750, 12086703, 12084493-M0, 12084493, 12...",12213082-M1-TST-CP,12213082,0,BEARER,officer,NaN,NaN,NaN,identical copy,12213082
342,12215529-M0-TST-M,"[(12153637, -1.1615253953453992, '12153637-T0'...","[12152488, 12152488, 12152488, 12202386, 12162...","[-0.029666674921833457, -0.029666674921833457,...","[12152488-M1, 12152488-M2, 12152488-M0, 122023...",12215529-M0-TST-M,12215529,0,INTERCON LIMITED,officer,NaN,NaN,NaN,move row,12215529
343,12216799-M0-TST-M,"[(12121269, -0.6670816866224668, '12121269-M2'...","[12162148, 12153551, 12153551, 12152737, 12152...","[-0.05566723384403045, -0.1478995933262812, -0...","[12162148, 12153551-M0, 12153551, 12152737-NV0...",12216799-M0-TST-M,12216799,0,FORMIA LIMITED,officer,NaN,NaN,NaN,move row,12216799
344,12217491-NV1-TST-M,"[(12036153, -0.34522984946433105, '12036153'),...","[12140952, 12140952, 12140777, 12140777, 12140...","[0.7366438254205903, 0.7366438254205903, 0.470...","[12140952, 12140952-T1, 12140777, 12140777-T0,...",12217491-NV1-TST-M,12217491,0,Bearer,officer,Rincon 531 Of. 502 - Montevideo - Uruguay,NaN,NaN,move row,12217491

# Wrong in top10 but not in top50

In [29]:
sub_wrong = sub_intrain_too_wrong[~sub_intrain_too_wrong.record_id.isin(set(scores_intrain_too_wrong.record_id.values))]

In [30]:
sub_wrong

,queried_record_id,predicted_record_id,record_id,linked_id_x,correct,name,type,address,phone,email,modification,linked_id_y
109,12000392-M1-TST-M,"[12215197, 12215197, 12151075, 12151075, 12151...",12000392-M1-TST-M,12000392,0,INTERCON NOMINEES LIMITED,officer,NaN,NaN,NaN,move row,12000392
125,12001357-M1-TST-M,"[12199447, 12199447, 12199447, 12199447, 12204...",12001357-M1-TST-M,12001357,0,BOS Secretaries (Jersey) Limited,officer,NaN,NaN,NaN,move row,12001357
137,12006107-NV0-TST-M,"[12006102, 12006102, 12017273, 12073800, 12072...",12006107-NV0-TST-M,12006107,0,AL PORTADOR,officer,NaN,NaN,PORTADOR@icloud.cz,move row,12006107
138,12006473-M0-TST-M,"[12215256, 12215256, 12215256, 12222533, 12222...",12006473-M0-TST-M,12006473,0,HARPO S.A.,officer,NaN,NaN,NaN,move row,12006473
139,12006473-M2-TST-M,"[12215256, 12215256, 12215256, 12222533, 12222...",12006473-M2-TST-M,12006473,0,HARPO S.A.,officer,NaN,NaN,NaN,move row,12006473
140,12006653-M0,"[12006965, 12078048, 12018002, 12018002, 12094...",12006653-M0,12006653,0,GAIRNS LTD.,officer,NaN,NaN,NaN,modified copy,12006653
149,12011094-M0-TST-M,"[12160315, 12160315, 12034991, 12034991, 12034...",12011094-M0-TST-M,12011094,0,FINISTERE SECRETARIES LIMITED,officer,NaN,NaN,NaN,move row,12011094
150,12012121-NV2-TST-M,"[11001105, 12175515, 10210966, 10210966, 10210...",12012121-NV2-TST-M,12012121,0,VOYAGEUR FOUNDATION,officer,NaN,4.208922e+11,NaN,move row,12012121
161,12014060-M0-TST-CP,"[12118208, 12165137, 12165137, 12195856, 12195...",12014060-M0-TST-CP,12014060,0,Minerva Services Limited,officer,NaN,NaN,NaN,identical copy,12014060
163,12016529-M0-TST-CP,"[12061160, 12035620, 12035620, 12083000, 12083...",12016529-M0-TST-CP,12016529,0,THE BAERER,officer,NaN,NaN,NaN,identical copy,12016529
178,12017696-M0-TST-CP,"[12074240, 12074859, 12075020, 12007701, 12007...",12017696-M0-TST-CP,12017696,0,KASTEL LIMITED,officer,NaN,NaN,NaN,identical copy,12017696
179,12017696-M1-TST-M,"[12074240, 12074859, 12075020, 12007701, 12007...",12017696-M1-TST-M,12017696,0,KASTEL LIMITED,officer,NaN,NaN,NaN,move row,12017696
185,12020788-M0-TST-CP,"[12065858, 12065858, 12156004, 12156004, 12156...",12020788-M0-TST-CP,12020788,0,BROTHERHOOD FOUNDATION,officer,NaN,NaN,NaN,identical copy,12020788
188,12024573-NV0-TST-M,"[12064265, 12094933, 12060369, 12060369, 12051...",12024573-NV0-TST-M,12024573,0,TO THE BEARER,officer,NaN,NaN,THEBEARER@gmail.co.uk,move row,12024573
191,12025245-M1-TST-M,"[13001083, 13001083, 13004803, 13004803, 13009...",12025245-M1-TST-M,12025245,0,TAY YEW BENG PETER,officer,NaN,NaN,NaN,move row,12025245
200,12027619-M0-TST-M,"[12218179, 12218179, 12218179, 12180568, 12180...",12027619-M0-TST-M,12027619,0,MF CORPORATE SERVICES (NIUE) PTE LTD.,officer,NaN,NaN,NaN,move row,12027619
208,12031006-M0,"[12031250, 12031014, 12024667, 12024667, 12031...",12031006-M0,12031006,0,THE BEARER,officer,NaN,NaN,NaN,modified copy,12031006
209,12031006-M1,"[12031250, 12031014, 12024667, 12024667, 12031...",12031006-M1,12031006,0,THE BEARER,officer,NaN,NaN,NaN,modified copy,12031006
210,12031006-M2,"[12031250, 12031014, 12024667, 12024667, 12031...",12031006-M2,12031006,0,THE BEARER,officer,NaN,NaN,NaN,modified copy,12031006
225,12032844-M0-TST-CP,"[12002708, 12002708, 12002708, 12088962, 12088...",12032844-M0-TST-CP,12032844,0,ROLIKA INC.,officer,NaN,NaN,NaN,identical copy,12032844
237,12038690-NV0-TST-M,"[12040711, 12040711, 12040711, 12040711, 12013...",12038690-NV0-TST-M,12038690,0,WTG MANAGERS LIMITED,officer,NaN,NaN,support@WTG.MANAGERS.LIMITED.it,move row,12038690
248,12041599-M2-TST-M,"[12216089, 12216089, 12216089, 12216089, 12216...",12041599-M2-TST-M,12041599,0,MONTAGUE GOLDSMITH INVESTCO ANSTALT,officer,NaN,NaN,NaN,move row,12041599
258,12044645-M0-TST-M,"[12197058, 12197058, 12197058, 12200883, 12196...",12044645-M0-TST-M,12044645,0,FIRST COURT LIMITED,officer,NaN,NaN,NaN,move row,12044645
261,12045505-M1-TST-CP,"[12036501, 12040382, 12040382, 12063988, 12063...",12045505-M1-TST-CP,12045505,0,Bearer,officer,NaN,NaN,NaN,identical copy,12045505
295,12048594-NV2-TST-M,"[12071403, 12063988, 12063988, 12047265, 12047...",12048594-NV2-TST-M,12048594,0,Bearer,officer,P.O. BOX 957; OFFSHORE INCORPORATIONS CENTRE; ...,NaN,NaN,move row,12048594
299,12060369-M1-TST-CP,"[12062636, 12071834, 12036505, 12012585, 12064...",12060369-M1-TST-CP,12060369,0,TO THE BEARER,officer,NaN,NaN,NaN,identical copy,12060369
300,12063877-M1-TST-M,"[12062636, 12071834, 12036505, 12012585, 12064...",12063877-M1-TST-M,12063877,0,TO THE BEARER,officer,NaN,NaN,NaN,move row,12063877
304,12071836-M0,"[12062636, 12071834, 12036505, 12012585, 12064...",12071836-M0,12071836,0,TO THE BEARER,officer,NaN,NaN,NaN,modified copy,12071836
305,12071836-M1,"[12062636, 12071834, 12036505, 12012585, 12064...",12071836-M1,12071836,0,TO THE BEARER,officer,NaN,NaN,NaN,modified copy,12071836
306,12071836-M2,"[12062636, 12071834, 12036505, 12012585, 12064...",12071836-M2,12071836,0,TO THE BEARER,officer,NaN,NaN,NaN,modified copy,12071836
...,...,...,...,...,...,...,...,...,...,...,...,...
459,12193719-M1,"[12087367, 12087367, 12017082, 12017082, 12183...",12193719-M1,12193719,0,FENCHURCH TRUST LIMITED,officer,NaN,NaN,NaN,modified copy,12193719
460,12193945-M0-TST-M,"[10196869, 12175112, 12175112, 12175112, 12175...",12193945-M0-TST-M,12193945,0,KENLEY FINANCE CORP.,officer,NaN,NaN,NaN,move row,12193945
461,12194007-M0-TST-CP,"[12137869, 12137869, 12163460, 12163460, 12163...",12194007-M0-TST-CP,12194007,0,AMOS SERVICES S.A.,officer,NaN,NaN,NaN,identical copy,12194007
462,12194592-M1-TST-CP,"[12177326, 12194613, 12194613, 12194613, 12113...",12194592-M1-TST-CP,12194592,0,MINERVA NOMINEES LIMITED,officer,NaN,NaN,NaN,identical copy,12194592
463,12197418-NV1-TST-M,"[12193459, 12193459, 12179269, 12192340, 12192...",12197418-NV1-TST-M,12197418,0,MOHUL NOMINEES LIMITED,officer,NO. 401; UNIT 6; BUILDING 22; YANGJING XILI; C...,NaN,NaN,move row,12197418
464,12197423-M0,"[12104408, 12104408, 12177147, 12177147, 12177...",12197423-M0,12197423,0,FIDELIS NOMINEES LIMITED,officer,NaN,NaN,NaN,modified copy,12197423
465,12197423-M1,"[12104408, 12104408, 12177147, 12177147, 12177...",12197423-M1,12197423,0,FIDELIS NOMINEES LIMITED,officer,NaN,NaN,NaN,modified copy,12197423
466,12198514-M0-TST-CP,"[12026156, 12116648, 12116648, 12116648, 12175...",12198514-M0-TST-CP,12198514,0,MINERVA SERVICES LIMITED,officer,NaN,NaN,NaN,identical copy,12198514
467,12198804-M2,"[12002293, 12002293, 12002293, 12002293, 12214...",12198804-M2,12198804,0,WARREN TRUSTEES LIMITED,officer,NaN,NaN,NaN,modified copy,12198804
468,12199173-M0-TST-M,"[12200153, 12185501, 12185501, 12200153, 12199...",12199173-M0-TST-M,12199173,0,MAYFAIR NOMINEES LIMITED,officer,NaN,NaN,NaN,move row,12199173
470,12201240-M1,"[12214899, 12214899, 12214899, 12216242, 12220...",12201240-M1,12201240,0,SCIVIAS TRUST MANAGEMENT LTD,officer,NaN,NaN,NaN,modified copy,12201240
478,12208688-M0-TST-M,"[12224899, 12224899, 12224899, 12224899, 12224...",12208688-M0-TST-M,12208688,0,MARKHAM FINANCIAL SERVICES CORP.,officer,NaN,NaN,NaN,move row,12208688
479,12209161-M0-TST-M,"[12215197, 12215197, 12151075, 12151075, 12151...",12209161-M0-TST-M,12209161,0,INTERCON NOMINEES LIMITED,officer,NaN,NaN,NaN,move row,12209161
480,12209893-M1-TST-M,"[12170860, 12170860, 12170860, 12029264, 12029...",12209893-M1-TST-M,12209893,0,Nomihold Securities Inc.,officer,NaN,NaN,NaN,move row,12209893
483,12213151-M0,"[12214607, 12214607, 12214607, 12214607, 12214...",12213151-M0,12213151,0,PARTLAW FOUNDATION,officer,NaN,NaN,NaN,modified copy,12213151
484,12213151-M2,"[12214607, 12214607, 12214607, 12214607, 12214...",12213151-M2,12213151,0,PARTLAW FOUNDATION,officer,NaN,NaN,NaN,modified copy,12213151
485,12214901-NV1-TST-M,"[12201241, 12216205, 12216205, 12216205, 12216...",12214901-NV1-TST-M,12214901,0,SCIVIAS TRUST MANAGEMENT LTD.,officer,CANNON'S COURT; 22 VICTORIA STREET; CORPORATIO...,NaN,sales@SCIVIAS.TRUST.MANAGEMENT.LTD.it,move row,12214901
487,12215845-M1-TST-M,"[10021617, 12006771, 12161345, 12161345, 12161...",12215845-M1-TST-M,12215845,0,TREX LIMITED,officer,NaN,NaN,NaN,move row,12215845
488,12216202-M0-TST-M,"[12214899, 12214899, 12214899, 12216242, 12220...",12216202-M0-TST-M,12216202,0,SCIVIAS TRUST MANAGEMENT LTD,officer,NaN,NaN,NaN,move row,12216202
490,12217007-M1-TST-M,"[12164165, 12164165, 12216977, 12216977, 12216...",12217007-M1-TST-M,12217007,0,Formia Limited,officer,NaN,NaN,NaN,move row,12217007
491,12217023-M0-TST-M,"[12215965, 12215965, 12215965, 12097242, 12097...",12217023-M0-TST-M,12217023,0,Moscrip Limited,officer,NaN,NaN,NaN,move row,12217023
492,12217275-M0-TST-M,"[12164980, 12165619, 12165619, 12155875, 12155...",12217275-M0-TST-M,12217275,0,BROCK NOMINEES LIMITED,officer,NaN,NaN,NaN,move row,12217275
494,12218342-M0-TST-M,"[10186308, 10186308, 10186308, 10186308, 12216...",12218342-M0-TST-M,12218342,0,CIVORIET LIMITED,officer,NaN,NaN,NaN,move row,12218342
495,12220603-M1-TST-M,"[12216089, 12216089, 12216089, 12216089, 12216...",12220603-M1-TST-M,12220603,0,MONTAGUE GOLDSMITH INVESTCO ANSTALT,officer,NaN,NaN,NaN,move row,12220603
496,12222050-M0-TST-CP,"[12084750, 12086703, 12084493, 12084493, 12088...",12222050-M0-TST-CP,12222050,0,BEARER,officer,NaN,NaN,NaN,identical copy,12222050
497,12222426-M1-TST-M,"[12214599, 12214599, 12214599, 12224177, 12224...",12222426-M1-TST-M,12222426,0,Aquitaine Nominees Limited,officer,NaN,NaN,NaN,move row,12222426
498,12223090-M0-TST-CP,"[12004095, 12004095, 12203950, 12203950, 12203...",12223090-M0-TST-CP,12223090,0,SERANGOON LIMITED,officer,NaN,NaN,NaN,identical copy,12223090
499,12223590-M2-TST-M,"[12219631, 12219631, 12219631, 12168862, 12168...",12223590-M2-TST-M,12223590,0,BOS NOMINEES (JERSEY) LIMITED,officer,NaN,NaN,NaN,move row,12223590
500,12225127-NV0-TST-M,"[12210286, 12210286, 12210286, 12209771, 12043...",12225127-NV0-TST-M,12225127,0,NWT NOMINEES LIMITED,officer,KENDRIS PRIVATE LTD. CASE POSTALE 2701 5001 AARAU,NaN,NaN,move row,12225127
501,13002934-M1-TST-CP,"[12220238, 12220238, 12220238, 12220238, 12187...",13002934-M1-TST-CP,13002934,0,WANG YING,officer,NaN,NaN,NaN,identical copy,13002934

In [159]:
sub_wrong_rec_id = set(sub_wrong.queried_record_id.values)

In [75]:
# predicted
df_train[df_train.linked_id == 10088906]

Empty DataFrame
Columns: [record_id, name, type, address, phone, email, modification, linked_id]
Index: []

In [74]:
# real
df_train[df_train.linked_id == 10088906]

Empty DataFrame
Columns: [record_id, name, type, address, phone, email, modification, linked_id]
Index: []

In [60]:
# Score 
scores[scores.queried_record_id == '12031006-M0']

,queried_record_id,rec_pred,ordered_linked,ordered_scores,ordered_record,record_id,linked_id,correct
163935,12031006-M0,"[(12024667, 0.24268749747488363, '12024667-NV0...","[12031250, 12031014, 12024667, 12024667, 12031...","[0.6699830898429368, 0.39499585136731535, 0.24...","[12031250, 12031014, 12024667-NV0, 12024667-NV...",12031006-M0,12031006,1

In [ ]:
# TODO per togliere questo caso: quando un record del test ha il name non nullo e tutti gli altri campi Nan, mettiamo
# nelle topN tutti i record del train che hanno quello stesso name. Per ognuno di questi record ci possono essere
# molti record del train che hanno lo stesso nome. Prima di tutto prenderne almeno uno di ciascun linked_id, che non
# è già tra quelli tirati fuori dall'ibrido

In [63]:
df_train['name'] = df_train.name.str.lower()
df_test['name'] = df_test.name.str.lower()

## Quanti sono i record del test che hanno solo il campo Name diverso da Nan

In [50]:
df_test['n_nan'] = df_test.isna().sum(axis=1)

In [76]:
df_test[(df_test.n_nan == 3) & (~df_test.linked_id.isin(only_test))]

,record_id,name,type,address,phone,email,modification,linked_id,n_nan
105971,10186890-T1-TST-M,mothvold invest limited,entity,NaN,NaN,NaN,move row,10186890,3
105977,13004225-M2-TST-M,cinthia julie alcindor,officer,NaN,NaN,NaN,move row,13004225,3
105980,10196995-M2-TST-M,arcadia investments holdings inc.,entity,NaN,NaN,NaN,move row,10196995,3
105982,10009201-M2-TST-M,dopro inc.,entity,NaN,NaN,NaN,move row,10009201,3
105985,12207314-M1-TST-M,chen bing,officer,NaN,NaN,NaN,move row,12207314,3
105991,10205585-TST-M,alvinson international trading s.a.,entity,NaN,NaN,NaN,move row,10205585,3
105994,12176916-M1-TST-M,liu xiao jing,officer,NaN,NaN,NaN,move row,12176916,3
105995,12008112-TST-M,maria lorena polit estrella,officer,NaN,NaN,NaN,move row,12008112,3
105998,10173542-M2-TST-M,the granite international foundation,entity,NaN,NaN,NaN,move row,10173542,3
106017,10047528-T1-TST-M,zoel invest s.a.,entity,NaN,NaN,NaN,move row,10047528,3
106020,12159553-M0-TST-M,galit hershkovitz,officer,NaN,NaN,NaN,move row,12159553,3
106026,11003085-NV0-TST-M,"gonzalez-campo, carlos",intermediary,NaN,NaN,NaN,move row,11003085,3
106030,10043983-M2-TST-M,mavi international investment s.a.,entity,NaN,NaN,NaN,move row,10043983,3
106031,10213158-M1-TST-M,alamein enterprises gmbh,entity,NaN,NaN,NaN,move row,10213158,3
106032,10045101-M0-TST-M,sea way shipping & enterprises limited,entity,NaN,NaN,NaN,move row,10045101,3
106041,10075555-M0-TST-M,irdine limited,entity,NaN,NaN,NaN,move row,10075555,3
106045,12099010-M0-TST-M,si lun,officer,NaN,NaN,NaN,move row,12099010,3
106049,10028458-T2-TST-M,raidway company inc.,entity,NaN,NaN,NaN,move row,10028458,3
106052,11010011-M0-TST-M,agustin gold,intermediary,NaN,NaN,NaN,move row,11010011,3
106055,10056410-M1-TST-M,charlotte manor limited,entity,NaN,NaN,NaN,move row,10056410,3
106068,10077208-M0-TST-M,joy sky international ltd.,entity,NaN,NaN,NaN,move row,10077208,3
106073,10203005-M2-TST-M,fordmax limited,entity,NaN,NaN,NaN,move row,10203005,3
106075,12178777-M2-TST-M,tan kang seng,officer,NaN,NaN,NaN,move row,12178777,3
106092,10086445-M1-TST-M,qualinvest corp.,entity,NaN,NaN,NaN,move row,10086445,3
106093,10149052-TST-M,kellera group s.a.,entity,NaN,NaN,NaN,move row,10149052,3
106101,10197776-NV0-TST-M,vulcan industrial holding limited,entity,NaN,NaN,NaN,move row,10197776,3
106104,10162213-M0-TST-M,"albayda overseas, s.a.",entity,NaN,NaN,NaN,move row,10162213,3
106107,10135371-M2-TST-M,wooderson assets ltd.,entity,NaN,NaN,NaN,move row,10135371,3
106108,10051588-NV1-TST-M,visual points inc.,entity,NaN,NaN,NaN,move row,10051588,3
106111,10074006-NV1-TST-M,egmont & cie limited,entity,NaN,NaN,NaN,move row,10074006,3
...,...,...,...,...,...,...,...,...,...
266846,10030998-M1,backhouse capital corp.,entity,NaN,NaN,NaN,modified copy,10030998,3
266850,12098249-M0,mrs ross donna,officer,NaN,NaN,NaN,modified copy,12098249,3
266851,10081579-M1,la rosa group ltd.,entity,NaN,NaN,NaN,modified copy,10081579,3
266857,10114979-M1,unistar international enterprises ltd.,entity,NaN,NaN,NaN,modified copy,10114979,3
266858,10068070-T2,beachcliffe properties bimited,entity,NaN,NaN,NaN,modified copy,10068070,3
266859,10199163-M0,american dream in wuhan ltd.,entity,NaN,NaN,NaN,modified copy,10199163,3
266870,10041575-M2,banos s.a.,entity,NaN,NaN,NaN,modified copy,10041575,3
266873,10133960-M0,nadariya services limited,entity,NaN,NaN,NaN,modified copy,10133960,3
266881,10004816-M0,wrangell s.a.,entity,NaN,NaN,NaN,modified copy,10004816,3
266882,10017650-M0,milverton ltd.,entity,NaN,NaN,NaN,modified copy,10017650,3
266884,10085059-M1,sagitta investment corp.,entity,NaN,NaN,NaN,modified copy,10085059,3
266887,12126220-M0,alchemie technology rdl limited,officer,NaN,NaN,NaN,modified copy,12126220,3
266895,12212930-M0,jurisankdo consultants inc.,officer,NaN,NaN,NaN,modified copy,12212930,3
266900,10146923-M0,"tigerlin international trade co., ltd.",entity,NaN,NaN,NaN,modified copy,10146923,3
266911,10014272-NV1,sarasota enterprises limited,entity,NaN,NaN,NaN,modified copy,10014272,3
266912,10011333-T0,fincorp investments corporation,entity,NaN,NaN,NaN,modified copy,10011333,3
266913,10016901-T2,"million happy rubber co., ltd.",entity,NaN,NaN,NaN,modified copy,10016901,3
266914,10092243-M0,dreamtime limited,entity,NaN,NaN,NaN,modified copy,10092243,3
266916,10159469-T2,oxy web solutions limited,entity,NaN,NaN,NaN,modified copy,10159469,3
266925,12113533-M1,mr loh kim kang david,officer,NaN,NaN,NaN,modified copy,12113533,3
266926,12098099-M0,zhang yingxue,officer,NaN,NaN,NaN,modified copy,12098099,3
266927,10134220-M2,rathwell properties ltd.,entity,NaN,NaN,NaN,modified copy,10134220,3
266930,10011333-T3,fijcorp investments corporation,entity,NaN,NaN,NaN,modified copy,10011333,3
266932,12111566-M2,dang nguyen hanh dung,officer,NaN,NaN,NaN,modified copy,12111566,3
266933,10131090-M2,multifoods holding group ltd.,entity,NaN,NaN,NaN,modified copy,10131090,3
266936,11012912-M0,"lalonde, donald drew",intermediary,NaN,NaN,NaN,modified copy,11012912,3
266937,12147786-M0,golden alliance management ltd.,officer,NaN,NaN,NaN,modified copy,12147786,3
266943,11003379-T2,mr. az rjedecko,intermediary,NaN,NaN,NaN,modified copy,11003379,3
266944,10121215-M1,farren group properties limited,entity,NaN,NaN,NaN,modified copy,10121215,3
266947,10063178-NV0,gold jumbo holdings ltd.,entity,NaN,NaN,NaN,modified copy,10063178,3

# Perché alcuni record del test che hanno solo il name vengono predetti bene?

In [ ]:
# Per ciascun record del test che ha solo il name != nan, guardiamo quanti record del train hanno lo stesso nome
# Usare ...name.str.contains(x_name) ci mette troppo, forse è meglio guardare il numero di 1 nella similarity

In [134]:
df_test = df_test.sort_values(by='record_id').reset_index(drop=True)
df_test_3nan = df_test[df_test.n_nan == 3]

In [136]:
df_train = df_train.sort_values(by='record_id').reset_index(drop=True)

In [123]:
from scipy import *
from scipy.sparse import *
import os

In [124]:
# Forse è meglio usare la cosine similarity?
sim_path = '../dataset/original/similarities'
sim_name = load_npz(os.path.join(sim_path, 'jaccard_uncleaned_name_300k_original_2ngrams.npz'))

In [156]:
def n_same_name(name_3nan_idx, sim_name):
    res = np.empty(len(name_3nan_idx), dtype=int)
    for i in tqdm(range(len(name_3nan_idx))):
        res[i] = np.argwhere(sim_name[name_3nan_idx[i]] >= 0.99).shape[0]
    return res

In [157]:
df_test_3nan['n_samename_intrain'] = n_same_name(df_test_3nan.index, sim_name)

HBox(children=(IntProgress(value=0, max=45349), HTML(value='')))

/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [169]:
df_test_3nan[df_test_3nan.record_id.isin(sub_wrong_rec_id)] # sono quelle che sbagliamo nelle top10 ma che ci sono nelle top50

,record_id,name,type,address,phone,email,modification,linked_id,n_nan,n_samename_intrain
158262,12000392-M1-TST-M,intercon nominees limited,officer,NaN,NaN,NaN,move row,12000392,3,57
158577,12001357-M1-TST-M,bos secretaries (jersey) limited,officer,NaN,NaN,NaN,move row,12001357,3,40
159643,12006473-M0-TST-M,harpo s.a.,officer,NaN,NaN,NaN,move row,12006473,3,66
159644,12006473-M2-TST-M,harpo s.a.,officer,NaN,NaN,NaN,move row,12006473,3,66
159686,12006653-M0,gairns ltd.,officer,NaN,NaN,NaN,modified copy,12006653,3,58
160210,12011094-M0-TST-M,finistere secretaries limited,officer,NaN,NaN,NaN,move row,12011094,3,15
160846,12014060-M0-TST-CP,minerva services limited,officer,NaN,NaN,NaN,identical copy,12014060,3,58
161398,12016529-M0-TST-CP,the baerer,officer,NaN,NaN,NaN,identical copy,12016529,3,81
161649,12017696-M0-TST-CP,kastel limited,officer,NaN,NaN,NaN,identical copy,12017696,3,91
161650,12017696-M1-TST-M,kastel limited,officer,NaN,NaN,NaN,move row,12017696,3,91
162034,12020788-M0-TST-CP,brotherhood foundation,officer,NaN,NaN,NaN,identical copy,12020788,3,76
162719,12025245-M1-TST-M,tay yew beng peter,officer,NaN,NaN,NaN,move row,12025245,3,28
163290,12027619-M0-TST-M,mf corporate services (niue) pte ltd.,officer,NaN,NaN,NaN,move row,12027619,3,23
163935,12031006-M0,the bearer,officer,NaN,NaN,NaN,modified copy,12031006,3,163
163936,12031006-M1,the bearer,officer,NaN,NaN,NaN,modified copy,12031006,3,163
163937,12031006-M2,the bearer,officer,NaN,NaN,NaN,modified copy,12031006,3,163
164304,12032844-M0-TST-CP,rolika inc.,officer,NaN,NaN,NaN,identical copy,12032844,3,51
166031,12041599-M2-TST-M,montague goldsmith investco anstalt,officer,NaN,NaN,NaN,move row,12041599,3,37
166866,12044645-M0-TST-M,first court limited,officer,NaN,NaN,NaN,move row,12044645,3,113
167145,12045505-M1-TST-CP,bearer,officer,NaN,NaN,NaN,identical copy,12045505,3,236
168735,12060369-M1-TST-CP,to the bearer,officer,NaN,NaN,NaN,identical copy,12060369,3,76
169131,12063877-M1-TST-M,to the bearer,officer,NaN,NaN,NaN,move row,12063877,3,76
170226,12071836-M0,to the bearer,officer,NaN,NaN,NaN,modified copy,12071836,3,76
170227,12071836-M1,to the bearer,officer,NaN,NaN,NaN,modified copy,12071836,3,76
170228,12071836-M2,to the bearer,officer,NaN,NaN,NaN,modified copy,12071836,3,76
170229,12071836-T0,to the bearer,officer,NaN,NaN,NaN,modified copy,12071836,3,76
170231,12071836-T2,to the bearer,officer,NaN,NaN,NaN,modified copy,12071836,3,76
170675,12074799-M0-TST-CP,kastel limited,officer,NaN,NaN,NaN,identical copy,12074799,3,91
171099,12077507-M0-TST-CP,livingston group s.a.,officer,NaN,NaN,NaN,identical copy,12077507,3,90
171108,12077590-M1-TST-M,livingston group s.a.,officer,NaN,NaN,NaN,move row,12077590,3,90
...,...,...,...,...,...,...,...,...,...,...
235172,12190662-M2-TST-CP,balchan secretaries limited,officer,NaN,NaN,NaN,identical copy,12190662,3,27
235671,12191396-M1-TST-CP,beneficence foundation,officer,NaN,NaN,NaN,identical copy,12191396,3,50
236118,12192089-M0-TST-M,fenchurch trust limited,officer,NaN,NaN,NaN,move row,12192089,3,51
237132,12193719-M1,fenchurch trust limited,officer,NaN,NaN,NaN,modified copy,12193719,3,51
237292,12193945-M0-TST-M,kenley finance corp.,officer,NaN,NaN,NaN,move row,12193945,3,13
237330,12194007-M0-TST-CP,amos services s.a.,officer,NaN,NaN,NaN,identical copy,12194007,3,41
237712,12194592-M1-TST-CP,minerva nominees limited,officer,NaN,NaN,NaN,identical copy,12194592,3,85
239564,12197423-M0,fidelis nominees limited,officer,NaN,NaN,NaN,modified copy,12197423,3,57
239565,12197423-M1,fidelis nominees limited,officer,NaN,NaN,NaN,modified copy,12197423,3,57
240226,12198514-M0-TST-CP,minerva services limited,officer,NaN,NaN,NaN,identical copy,12198514,3,52
240402,12198804-M2,warren trustees limited,officer,NaN,NaN,NaN,modified copy,12198804,3,32
240658,12199173-M0-TST-M,mayfair nominees limited,officer,NaN,NaN,NaN,move row,12199173,3,37
242020,12201240-M1,scivias trust management ltd,officer,NaN,NaN,NaN,modified copy,12201240,3,45
247096,12208688-M0-TST-M,markham financial services corp.,officer,NaN,NaN,NaN,move row,12208688,3,26
247376,12209161-M0-TST-M,intercon nominees limited,officer,NaN,NaN,NaN,move row,12209161,3,57
247893,12209893-M1-TST-M,nomihold securities inc.,officer,NaN,NaN,NaN,move row,12209893,3,27
249991,12213151-M0,partlaw foundation,officer,NaN,NaN,NaN,modified copy,12213151,3,22
249993,12213151-M2,partlaw foundation,officer,NaN,NaN,NaN,modified copy,12213151,3,22
251745,12215845-M1-TST-M,trex limited,officer,NaN,NaN,NaN,move row,12215845,3,41
251990,12216202-M0-TST-M,scivias trust management ltd,officer,NaN,NaN,NaN,move row,12216202,3,45
252537,12217007-M1-TST-M,formia limited,officer,NaN,NaN,NaN,move row,12217007,3,52
252551,12217023-M0-TST-M,moscrip limited,officer,NaN,NaN,NaN,move row,12217023,3,16
252742,12217275-M0-TST-M,brock nominees limited,officer,NaN,NaN,NaN,move row,12217275,3,89
253455,12218342-M0-TST-M,civoriet limited,officer,NaN,NaN,NaN,move row,12218342,3,17
254970,12220603-M1-TST-M,montague goldsmith investco anstalt,officer,NaN,NaN,NaN,move row,12220603,3,37
255858,12222050-M0-TST-CP,bearer,officer,NaN,NaN,NaN,identical copy,12222050,3,300
256085,12222426-M1-TST-M,aquitaine nominees limited,officer,NaN,NaN,NaN,move row,12222426,3,23
256510,12223090-M0-TST-CP,serangoon limited,officer,NaN,NaN,NaN,identical copy,12223090,3,62
256813,12223590-M2-TST-M,bos nominees (jersey) limited,officer,NaN,NaN,NaN,move row,12223590,3,59
259917,13002934-M1-TST-CP,wang ying,officer,NaN,NaN,NaN,identical copy,13002934,3,23

In [181]:
mask = ~df_test_3nan.record_id.isin(sub_wrong_rec_id) & (~df_test_3nan.linked_id.isin(only_test)) & (df_test_3nan.name != 'bearer')
df_test_3nan[mask].sort_values(by='n_samename_intrain', ascending=False)

,record_id,name,type,address,phone,email,modification,linked_id,n_nan,n_samename_intrain
163962,12031088-T1-TST-M,the bearer,officer,NaN,NaN,NaN,move row,12031088,3,163
161477,12016856-M0-TST-M,the bearer,officer,NaN,NaN,NaN,move row,12016856,3,163
163963,12031088-TST-CP,the bearer,officer,NaN,NaN,NaN,identical copy,12031088,3,163
161775,12018433-M2-TST-M,the bearer,officer,NaN,NaN,NaN,move row,12018433,3,163
163989,12031248-M0-TST-CP,the bearer,officer,NaN,NaN,NaN,identical copy,12031248,3,163
161478,12016856-M1-TST-CP,the bearer,officer,NaN,NaN,NaN,identical copy,12016856,3,163
162561,12024667-TST-M,the bearer,officer,NaN,NaN,NaN,move row,12024667,3,163
195835,12130088-M1-TST-M,charitable and goodwill foundation,officer,NaN,NaN,NaN,move row,12130088,3,145
158505,12001153-M2-TST-CP,charitable and goodwill foundation,officer,NaN,NaN,NaN,identical copy,12001153,3,145
166320,12043049-TST-CP,charitable and goodwill foundation,officer,NaN,NaN,NaN,identical copy,12043049,3,145
166319,12043049-T3-TST-CP,charitable and goodwill foundation,officer,NaN,NaN,NaN,identical copy,12043049,3,145
164503,12034384-M2-TST-CP,charitable and goodwill foundation,officer,NaN,NaN,NaN,identical copy,12034384,3,145
252396,12216799-M0-TST-M,formia limited,officer,NaN,NaN,NaN,move row,12216799,3,134
242000,12201206-M0-TST-M,formia limited,officer,NaN,NaN,NaN,move row,12201206,3,134
199094,12135307-M0-TST-CP,north atlantic services limited,officer,NaN,NaN,NaN,identical copy,12135307,3,127
186832,12116371-M2,mayo secretaries limited,officer,NaN,NaN,NaN,modified copy,12116371,3,118
186831,12116371-M1,mayo secretaries limited,officer,NaN,NaN,NaN,modified copy,12116371,3,118
198994,12135159-M0-TST-M,mayo secretaries limited,officer,NaN,NaN,NaN,move row,12135159,3,118
186830,12116371-M0,mayo secretaries limited,officer,NaN,NaN,NaN,modified copy,12116371,3,118
226700,12178176-M0-TST-CP,richmond nominees limited,officer,NaN,NaN,NaN,identical copy,12178176,3,114
245030,12205696-M1-TST-M,richmond nominees limited,officer,NaN,NaN,NaN,move row,12205696,3,114
198907,12135030-M0-TST-M,mayo nominees limited,officer,NaN,NaN,NaN,move row,12135030,3,113
239318,12197058-M0-TST-CP,first court limited,officer,NaN,NaN,NaN,identical copy,12197058,3,113
251537,12215529-M0-TST-M,intercon limited,officer,NaN,NaN,NaN,move row,12215529,3,101
226877,12178420-M1-TST-CP,mohul nominees limited,officer,NaN,NaN,NaN,identical copy,12178420,3,100
161925,12019831-M1-TST-M,caversham secretaries limited,officer,NaN,NaN,NaN,move row,12019831,3,92
163816,12030585-M1-TST-M,caversham secretaries limited,officer,NaN,NaN,NaN,move row,12030585,3,92
223065,12172359-M0-TST-M,caversham secretaries limited,officer,NaN,NaN,NaN,move row,12172359,3,92
161924,12019831-M0-TST-M,caversham secretaries limited,officer,NaN,NaN,NaN,move row,12019831,3,92
159810,12007701-TST-CP,kastel limited,officer,NaN,NaN,NaN,identical copy,12007701,3,91
...,...,...,...,...,...,...,...,...,...,...
49469,10071552-T3-TST-M,sun hero rnternational limined (with chinese c...,entity,NaN,NaN,NaN,move row,10071552,3,0
129325,10186568-T0-TST-M,kadnex holdings limited,entity,NaN,NaN,NaN,move row,10186568,3,0
129441,10186739-T2-TST-M,yeateo inveytments limited,entity,NaN,NaN,NaN,move row,10186739,3,0
129571,10186917-T4-TST-M,sohal hootings group ltd.,entity,NaN,NaN,NaN,move row,10186917,3,0
49681,10071860-T1-TST-M,goodwin developments limited,entity,NaN,NaN,NaN,move row,10071860,3,0
48973,10070812-T4-TST-M,sabella wnveztmeat limited,entity,NaN,NaN,NaN,move row,10070812,3,0
48969,10070808-T1-TST-M,berkeley square properties limitsd,entity,NaN,NaN,NaN,move row,10070808,3,0
237352,12194038-T0,elenco doldings inc.,officer,NaN,NaN,NaN,modified copy,12194038,3,0
237355,12194038-T2,elenco holdinvs inc.,officer,NaN,NaN,NaN,modified copy,12194038,3,0
237356,12194038-T3,elenco moldings inc.,officer,NaN,NaN,NaN,modified copy,12194038,3,0
129712,10187159-T0-TST-M,"lvye inteanational to., ltj",entity,NaN,NaN,NaN,move row,10187159,3,0
49611,10071763-T3,jempro holding inc.,entity,NaN,NaN,NaN,modified copy,10071763,3,0
49682,10071860-TST-M,goodwin developments limited,entity,NaN,NaN,NaN,move row,10071860,3,0
128565,10185479-T2-TST-M,rockby limited,entity,NaN,NaN,NaN,move row,10185479,3,0
128894,10185935-T0-TST-M,xopapj se,entity,NaN,NaN,NaN,move row,10185935,3,0
50654,10073257-T0-TST-M,rillowbrook holdings limited,entity,NaN,NaN,NaN,move row,10073257,3,0
128619,10185544-T0-TST-M,tswwbahamas inqorporated,entity,NaN,NaN,NaN,move row,10185544,3,0
128693,10185650-T0,yexar sedvzces ltd.,entity,NaN,NaN,NaN,modified copy,10185650,3,0
128702,10185659-T3-TST-M,genesisdot. com iecr,entity,NaN,NaN,NaN,move row,10185659,3,0
50402,10072916-T0-TST-M,dr hayer foundatyon ltd.,entity,NaN,NaN,NaN,move row,10072916,3,0
128752,10185721-T0-TST-M,sunningdale ihj.,entity,NaN,NaN,NaN,move row,10185721,3,0
128941,10186012-T0,union standard group inteknational holdings li...,entity,NaN,NaN,NaN,modified copy,10186012,3,0
129068,10186176-T1-TST-M,acyas limjted,entity,NaN,NaN,NaN,move row,10186176,3,0
128944,10186012-T2,union standard group intdpnationalgholdings li...,entity,NaN,NaN,NaN,modified copy,10186012,3,0
128945,10186012-T3,union stavdard group international holdings li...,entity,NaN,NaN,NaN,modified copy,10186012,3,0
128953,10186021-T1-TST-M,infumode group inc.,entity,NaN,NaN,NaN,move row,10186021,3,0
49964,10072254-T2-TST-M,csiwtelecoms limited,entity,NaN,NaN,NaN,move row,10072254,3,0
49916,10072182-T4-TST-M,qxian leader investment limiped,entity,NaN,NaN,NaN,move row,10072182,3,0
49846,10072088-T0-TST-M,good ezsence investment & developxent ltd.,entity,NaN,NaN,NaN,move row,10072088,3,0
167892,12049273-T2,"min,yin-fong",officer,NaN,NaN,NaN,modified copy,12049273,3,0

In [184]:
df_train[df_train.name.str.contains('formia limited')].drop_duplicates('linked_id')

,record_id,name,type,address,phone,email,modification,linked_id
166181,10093454,formia limited,entity,NaN,3.933220e+09,NaN,original,10093454
408441,12001174,formia limited,officer,NaN,1.640642e+10,NaN,original,12001174
414516,12013996,formia limited,officer,NaN,4.937070e+10,NaN,original,12013996
415451,12015313,formia limited,officer,NaN,4.996329e+10,NaN,original,12015313
431163,12045426,formia limited,officer,NaN,4.961758e+10,contact@zoho.gov,original,12045426
443753,12084516,formia limited,officer,NaN,3.956898e+09,help@FORMIA.LIMITED.com,original,12084516
463035,12104721,formia limited,officer,24 DE CASTRO STR.; WICKHAMS CAY 1; ROAD TOWN; ...,4.998790e+10,NaN,original,12104721
463773,12105133,formia limited,officer,"25 APHRODITE STREET, NICOSIA CYPRUS",NaN,consulting@icloud.gov,original,12105133
464931,12105784,formia limited,officer,24 DE CASTRO STREET; WICKHAMS CAY 1; AKARA BUI...,4.922246e+10,NaN,original,12105784
491243,12121269,formia limited,officer,5 THEM. DERVIS STREET ELENION BUILDING; 2ND FL...,3.964310e+09,NaN,original,12121269
496820,12124767,formia limited,officer,AKARA BUILDING; 24 DE CASTRO STR; WICKHAMS CAY...,NaN,NaN,original,12124767
497062,12124911,formia limited,officer,AKARA BUILDING; 24 DE CASTRO STREET; ROAD TOWN...,3.348021e+11,NaN,original,12124911
509465,12132137,formia limited,officer,AKARA BLDG.; 24 DE CASTRO STREET; WICKHAMS CAY...,4.207923e+11,NaN,original,12132137
511207,12133240,formia limited,officer,Akara Building; 24 De Castro Str.; Wickhamns C...,3.965546e+09,NaN,original,12133240
512172,12133766,formia limited,officer,Akara Building; 24 De Castro Str.; Wickhams Ca...,3.319008e+11,NaN,original,12133766
512269,12133821,formia limited,officer,Akara Building; 24 De Castro Street; Wickhmas ...,1.257911e+10,support@Formia.Limited.cz,original,12133821
512325,12133852,formia limited,officer,Akara Building; 24 De Castro Str.; Wickhams Ca...,1.640627e+10,contact@aol.it,original,12133852
515001,12135428,formia limited,officer,AKARA BUILDING; 24 CASTRO STREET; WICKHAMS CAY...,1.097417e+10,NaN,original,12135428
515867,12135968,formia limited,officer,Akara Building 24 DeVastro Street WickhamsCay ...,1.764084e+10,sales@Formia.Limited.com,original,12135968
517617,12137053,messers formia limited,officer,Akara Building; 24 De Castro Street; Wickhams ...,4.959280e+10,NaN,original,12137053
534620,12147526,formia limited,officer,ELIZABETH AVENUE AND SHIRLEY STREET; UNION COU...,3.969251e+09,sales@FORMIA.LIMITED.com,original,12147526
543098,12152482,formia limited,officer,FRANCIS RACHEL STREET; SUITE 13; OLIAJI TRADE ...,3.921103e+09,NaN,original,12152482
543199,12152625,formia limited,officer,FRANCIS RACHEL STREET; OLIAJI TRADE CENTRE SUI...,3.975424e+09,info@FORMIA.LIMITED.gov,original,12152625
543205,12152628,formia limited,officer,FRANCIS RACHEL STREET; SUITE 13; OLIAJI TRADE ...,NaN,NaN,original,12152628
543264,12152664-T0,formia limited,officer,Francis Rachel Street; Suite 13; Oliaji Trade ...,2.496698e+11,contact@FORMIA.LIMITED.it,typo,12152664
543410,12152737,formia limited,officer,FRANCIS RACHEL STREET SUITE 13 OLIAJI TRADE CE...,NaN,NaN,original,12152737
543817,12152988,formia limited,officer,Consulco House 25; Aphrodite Street; P.O. Box ...,3.990239e+09,NaN,original,12152988
544603,12153473,formia limited,officer,Francis Rachel Street; Suite 13; First Floor; ...,4.493241e+11,inquires@outlook.de,original,12153473
544735,12153551,formia limited,officer,Francis Rachel Street; Suite 13; Oliaji Trade ...,1.838156e+10,consulting@FORMIA.LIMITED.de,original,12153551
549378,12156254,formia limited,officer,"DE CASTRO STREET WICKHAMS CAY 1 AKARA BLDG., R...",4.208661e+11,NaN,original,12156254
...,...,...,...,...,...,...,...,...
627518,12201426,formia limited,officer,SUITE 13; OLIAJI TRADE CENTRE; FIRST FLOOR FRA...,4.156682e+12,NaN,original,12201426
628280,12201849,formia limited,officer,SUITE 13; FIRST FLOOR OLIAJO TRADE CENTRE; FRA...,NaN,NaN,original,12201849
628389,12201905-NV0,formia limited,officer,SUITE 13; FIRST FLOOR; OLIAJI TRADE,4.201249e+11,sales@icloud.gov,new_value,12201905
628454,12201932,formia limited,officer,Suite 13; first floor; Oliaji Trade Center; Fr...,3.314557e+11,NaN,original,12201932
628490,12201965,formia limited,officer,SUITE 13; FIRST FLOOR; OLIAJI; TRADE CENTRE; F...,4.201990e+11,NaN,original,12201965
628855,12202166,formia limited.,officer,SUITE 13; FIRST FLOOR; OLIAJI; TRADE CENTRE; F...,NaN,NaN,original,12202166
651293,12215304,formia limited,officer,SUITE 13; FIRST FLOOR; OLIAJI TRADE CENTRE; FR...,NaN,sales@aol.it,original,12215304
651458,12215376,formia limited,officer,Suite 13; First Floor; Oliaji Trade Centre; Fr...,NaN,help@FORMIA.LIMITED.it,original,12215376
651704,12215530,formia limited,officer,Suite 13; Oliaji Trade Centre; 1 st Floor; Fra...,NaN,NaN,original,12215530
651727,12215542,formia limited,officer,Suite 13; Oliaji Trade Centre; First Floor; Fr...,3.906296e+09,info@Formia.Limited.cz,original,12215542
652037,12215733,formia limited,officer,SUITE 13 OLIAJI TRADE CENTER FRANIS RACHELL ST...,NaN,NaN,original,12215733
652249,12215838,formia limited,officer,SUITE 13; FIRST FLOOR; OLAIJI TRADE CENTRE; FR...,4.913593e+10,NaN,original,12215838
652448,12215964,formia limited,officer,SUITE 13; FIRST FLOOR; OLIAJI TRADE CENTRE; FR...,NaN,contact@hotmail.co.uk,original,12215964
652460,12215970,formia limited,officer,SUITE 13; FIRST FLOOR; OLIAJI TRADE CENTRE; FR...,NaN,NaN,original,12215970
652556,12216021-NV0,formia limited,officer,"Arsenales 1228, Vicente López Provincia de Bue...",NaN,NaN,new_value,12216021
654038,12216799,formia limited,officer,Suite 13; First Floor; Oliaji Trade Centre Cen...,4.207791e+11,NaN,original,12216799
654353,12216975,formia limited,officer,Suite 13; First Floor; Oliaji Trade Centre; Fr...,NaN,NaN,original,12216975
654358,12216977,formia limited,officer,Suite 13; First Floor; Oliaji Trade Centre; Fr...,NaN,NaN,original,12216977
654414,12217007,formia limited,officer,Suite 13; First Floor; Oliajji Trade Centre; F...,4.116914e+12,NaN,original,12217007
654421,12217011,formia limited,officer,Suite 13; Fisrt Floor; Oliaji Trade Centre; Fr...,1.294939e+10,NaN,original,12217011
654483,12217039,formia limited,officer,Suite 13; Oliaji Trade Centre; First Floor; Ma...,4.200754e+11,help@FORMIA.LIMITED.com,original,12217039
654698,12217156,formia limited,officer,Suite 13; First Floor; Oliaji Trade Centre Cen...,1.085062e+10,consulting@zoho.it,original,12217156
655086,12217415,formia limited,officer,Suite 13; First Floor; Oliaji trade Centre; Fr...,4.427251e+11,NaN,original,12217415
655173,12217481,formia limited,officer,Suite 13; Fisrt Floor; Oliaji Trade Centre; Fr...,4.997544e+10,NaN,original,12217481
655176,12217483,formia limited,officer,SUITE 13; FRANCIS RACHEL STREET; OLIAJI TRADE ...,4.162345e+12,contact@yahoo.com,original,12217483
655208,12217499,formia limited,officer,Suite 13; Oliaji Trade Centre; First Floor; Fr...,3.911234e+09,NaN,original,12217499
655298,12217535,formia limited,officer,SUITE 13; OLIAJI TRADE CENTRE; FRANCIS RACHEL ...,4.442065e+11,NaN,original,12217535
658038,12219135,formia limited,officer,uite 13; First Floor; Oliaji Trade centre; Fra...,4.172961e+12,inquires@FORMIA.LIMITED.gov,original,12219135
661641,12221209,formia limited,officer,Suite 13; First Floor; Oliaji Trade Center Fra...,NaN,help@FORMIA.LIMITED.de,original,12221209
661791,12221309,formia limited,officer,Suite 13; First Floor; Oliaji Trade Centre; Fr...,4.487988e+11,help@icloud.com,original,12221309