In [1]:
import pandas as pd
import numpy as np
from tqdm.auto import tqdm

In [2]:
s = pd.read_csv("../lgb_predictions.csv")
s

,queried_record_id,rec_pred,ordered_linked,ordered_scores,ordered_record
0,10000003-TST-MR,"[(10010930, -9.257270041531807, '10010930'), (...","[10127532, 10127532, 10127532, 10127532, 10127...","[-9.16486731510361, -9.16486731510361, -9.1648...","['10127532-M1', '10127532', '10127532-M0', '10..."
1,10000008-TST-M,"[(10043172, 1.4372028433655306, '10043172-NV0'...","[10043172, 10043172, 10043172, 10107096, 10135...","[1.4372028433655306, 1.4372028433655306, 1.437...","['10043172-NV0', '10043172-M2', '10043172', '1..."
2,10000010-TST-CP,"[(10000010, 7.540006760334157, '10000010'), (1...","[10000010, 10192342, 12194552, 12194552, 12194...","[7.540006760334157, -4.190882268753726, -5.701...","['10000010', '10192342', '12194552-T1', '12194..."
3,10000013-TST-MR,"[(10153043, -3.3628909944191347, '10153043'), ...","[10153043, 10154534, 10147826, 10147826, 10147...","[-3.3628909944191347, -3.7838719061451003, -4....","['10153043', '10154534', '10147826', '10147826..."
4,10000016-TST-MR,"[(10147072, -2.6520293768791405, '10147072-T0'...","[10147072, 10147072, 10104833, 10012410, 10113...","[-2.6520293768791405, -2.6520293768791405, -3....","['10147072-T0', '10147072', '10104833', '10012..."
5,10000017-TST-MR,"[(10094323, -3.073918357969311, '10094323-T0')...","[10155088, 10155088, 10155088, 10062221, 10062...","[-2.4603870175722458, -2.4603870175722458, -2....","['10155088', '10155088-M1', '10155088-M2', '10..."
6,10000018-T4-TST-CP,"[(10000018, 7.498662877065813, '10000018-T4'),...","[10000018, 10000018, 10000018, 10000018, 10000...","[7.7508457993581725, 7.498662877065813, 7.3780...","['10000018-T0', '10000018-T4', '10000018-T3', ..."
7,10000018-TST-M,"[(10000018, 7.498662877065813, '10000018-T1'),...","[10000018, 10000018, 10000018, 10000018, 10000...","[8.031932312272719, 7.498662877065813, 7.37804...","['10000018-T0', '10000018-T1', '10000018-T3', ..."
8,10000020-NV0-TST-CP,"[(10000020, 3.303681326474439, '10000020'), (1...","[10000020, 10000020, 10000020, 10151492, 10094...","[3.303681326474439, 3.303681326474439, 3.30368...","['10000020', '10000020-NV0', '10000020-NV2', '..."
9,10000020-NV1-TST-M,"[(10000020, 6.9544746513158575, '10000020'), (...","[10000020, 10000020, 10000020, 10151492, 10094...","[6.9544746513158575, 3.1177701468306704, 3.117...","['10000020', '10000020-NV0', '10000020-NV2', '..."
10,10000022-TST-CP,"[(10000022, 7.816988049961335, '10000022'), (1...","[10000022, 10213858, 10213858, 10184573, 10046...","[7.816988049961335, -2.615097078753, -2.615097...","['10000022', '10213858-T0', '10213858', '10184..."
11,10000023-NV2-TST-CP,"[(10000023, 6.610937892873162, '10000023'), (1...","[10000023, 10000023, 10000023, 10000023, 10000...","[6.610937892873162, 6.610937892873162, 6.61093...","['10000023', '10000023-M1', '10000023-NV1', '1..."
12,10000024-TST-MR,"[(10100649, 3.5046931753835646, '10100649'), (...","[10100649, 10100649, 10214082, 10214082, 10214...","[3.5046931753835646, -0.36343866436934824, -5....","['10100649', '10100649-T0', '10214082-NV1', '1..."
13,10000025-TST-MR,"[(10038568, 4.337164684617, '10038568'), (1221...","[10038568, 12015628, 13012970, 13012990, 13012...","[4.337164684617, -8.403803345687871, -9.177581...","['10038568', '12015628', '13012970-M0', '13012..."
14,10000027-M0-TST-M,"[(10000027, 7.2813890966503765, '10000027'), (...","[10000027, 10000027, 10000027, 10199071, 10199...","[7.2813890966503765, 7.2813890966503765, 6.601...","['10000027', '10000027-T2', '10000027-T3', '10..."
15,10000027-T0-TST-M,"[(10000027, 7.2813890966503765, '10000027'), (...","[10000027, 10000027, 10000027, 10199071, 10199...","[7.2813890966503765, 7.2813890966503765, 6.601...","['10000027', '10000027-T2', '10000027-T3', '10..."
16,10000027-T1-TST-M,"[(10000027, 7.2813890966503765, '10000027'), (...","[10000027, 10000027, 10000027, 10199071, 10199...","[7.2813890966503765, 7.2813890966503765, 6.693...","['10000027', '10000027-T2', '10000027-T3', '10..."
17,10000028-TST-MR,"[(10132222, -9.818708384647271, '10132222'), (...","[10021933, 10021933, 10021933, 10093718, 10190...","[-7.976158046209574, -7.976158046209574, -7.97...","['10021933-M0', '10021933-NV0', '10021933', '1..."
18,10000030-TST-MR,"[(10037339, 3.9916365963611327, '10037339'), (...","[10037339, 10037339, 10108191, 10108191, 10034...","[3.9916365963611327, 0.8684033700316135, -0.37...","['10037339', '10037339-T0', '10108191', '10108..."
19,10000031-M2-TST-M,"[(10000031, 1.021607162411545, '10000031'), (1...","[10000031, 10000031, 10000031, 10000031, 10000...","[1.021607162411545, 1.021607162411545, 1.02160...","['10000031', '10000031-M0', '10000031-M1', '10..."
20,10000032-T0-TST-CP,"[(10000032, 6.806167281324907, '10000032-T0'),...","[10000032, 10000032, 10000032, 10000032, 10133...","[6.806167281324907, 5.736340495161974, -1.4163...","['10000032-T0', '10000032', '10000032-M1', '10..."
21,10000032-T1-TST-M,"[(10000032, 6.571180986169107, '10000032'), (1...","[10000032, 10000032, 10000032, 10037597, 10037...","[6.571180986169107, 2.0311736912373277, 2.0311...","['10000032', '10000032-M0', '10000032-M1', '10..."
22,10000034-TST-M,"[(10071366, -1.3599937789113583, '10071366'), ...","[10213815, 10213815, 10208443, 10071366, 10071...","[-0.28949473720108776, -0.28949473720108776, -...","['10213815', '10213815-T1', '10208443', '10071..."
23,10000036-NV0-TST-M,"[(10000036, 7.357723325322819, '10000036-T0'),...","[10000036, 10000036, 10184295, 10184295, 10184...","[7.357723325322819, 7.357723325322819, 0.40880...","['10000036-T0', '10000036-T2', '10184295-M1', ..."
24,10000036-NV1-TST-M,"[(10000036, 7.286054820342851, '10000036-T0'),...","[10000036, 10000036, 10184295, 10184295, 10184...","[7.286054820342851, 7.286054820342851, -0.5562...","['10000036-T0', '10000036-T2', '10184295', '10..."
25,10000036-T0-TST-CP,"[(10000036, 7.357723325322819, '10000036-T0'),...","[10000036, 10000036, 10184295, 10184295, 10184...","[7.357723325322819, 7.357723325322819, 0.40880...","['10000036-T0', '10000036-T2', '10184295-M1', ..."
26,10000036-TST-M,"[(10000036, 7.357723325322819, '10000036-T0'),...","[10000036, 10000036, 10184295, 10184295, 10184...","[7.357723325322819, 7.357723325322819, 0.40880...","['10000036-T0', '10000036-T2', '10184295-M1', ..."
27,10000037-TST-MR,"[(10045833, -8.879981752592654, '10045833'), (...","[10115101, 10120582, 10115101, 10115101, 10097...","[0.42988207128793793, 0.22143225130650612, -1....","['10115101-T4', '10120582', '10115101', '10115..."
28,10000038-TST-MR,"[(10136074, -3.2039696461266924, '10136074-NV0...","[10136074, 10136074, 10136074, 10136074, 10047...","[-3.2039696461266924, -3.2039696461266924, -3....","['10136074-NV0', '10136074-NV2', '10136074', '..."
29,10000039-TST-CP,"[(10000039, 7.3122601183258675, '10000039'), (...","[10000039, 10000039, 10000039, 10000039, 12103...","[7.3122601183258675, 7.3122601183258675, 5.748...","['10000039', '10000039-T2', '10000039-T1', '10..."
...,...,...,...,...,...
266925,13013118-TST-M,"[(13013118, 1.5793532925379852, '13013118-M0')...","[13013118, 13013118, 13012970, 13013008, 13012...","[1.5793532925379852, 1.5793532925379852, -8.99...","['13013118-M0', '13013118-NV0', '13012970-M0',..."
266926,13013119-NV0-TST-CP,"[(13013119, 6.280596372077049, '13013119-NV0')...","[13013119, 13013119, 13013119, 12119080, 12119...","[6.280596372077049, 2.6715084897515835, 1.0587...","['13013119-NV0', '13013119', '13013119-NV1', '..."
266927,15000601-TST-M,"[(15007401, -9.015842090645792, '15007401-M0')...","[13012970, 13013008, 13012990, 13012883, 13012...","[-8.502919062017646, -8.550898205156232, -8.72...","['13012970-M0', '13013008-M0', '13012990-M0', ..."
266928,15000801-TST-MR,"[(12160217, -9.107455931931765, '12160217'), (...","[12170250, 12170250, 12170250, 12211310, 12211...","[-8.315910657575868, -8.315910657575868, -8.31...","['12170250-T0', '12170250', '12170250-T3', '12..."
266929,15000901-TST-MR,"[(15007401, -9.015842090645792, '15007401-M0')...","[13012970, 13013008, 13012990, 13012883, 13012...","[-8.502919062017646, -8.550898205156232, -8.72...","['13012970-M0', '13013008-M0', '13012990-M0', ..."
266930,15001201-NV0,"[(15001201, 3.486057713983367, '15001201'), (1...","[15001201, 12172071, 12223857, 13005835, 13001...","[3.486057713983367, -9.177803972359037, -9.177...","['15001201', '12172071-T0', '12223857', '13005..."
266931,15001301-TST-MR,"[(11008337, 3.108315427552664, '11008337'), (1...","[11008337, 12223335, 12098992, 12098992, 12098...","[3.108315427552664, -8.944724511174797, -8.953...","['11008337', '12223335-NV0', '12098992-T2', '1..."
266932,15001401-M0-TST-CP,"[(15001401, 1.073936271568702, '15001401-M2'),...","[15001401, 15001401, 15001401, 15001401, 12146...","[1.073936271568702, 1.073936271568702, 1.07393...","['15001401-M2', '15001401-M1', '15001401-M0', ..."
266933,15001401-M2-TST-CP,"[(15001401, 1.073936271568702, '15001401-M2'),...","[15001401, 15001401, 15001401, 15001401, 12146...","[1.073936271568702, 1.073936271568702, 1.07393...","['15001401-M2', '15001401-M1', '15001401-M0', ..."
266934,15001501-TST-MR,"[(12127195, -3.7931629136357308, '12127195'), ...","[12127195, 12218955, 12218955, 12218955, 12218...","[-3.7931629136357308, -4.6209148006731855, -4....","['12127195', '12218955-T2', '12218955-T1', '12..."
266935,15001601-T3-TST-CP,"[(15001601, 7.466391189801397, '15001601-T3'),...","[15001601, 15001601, 15001601, 15001601, 15001...","[7.466391189801397, 6.730525470129731, 6.54421...","['15001601-T3', '15001601-T1', '15001601-T0', ..."
266936,15001801-T0-TST-CP,"[(15001801, 6.875714061206527, '15001801'), (1...","[15001801, 15001801, 15001801, 15001801, 12100...","[6.875714061206527, 6.875714061206527, 6.87571...","['15001801', '15001801-M0', '15001801-M1', '15..."
266937,15001903-TST-MR,"[(15001902, -1.7613907534122795, '15001902'), ...","[15001902, 12167028, 12128125, 12121833, 12099...","[-1.7613907534122795, -8.2811005795159, -8.286...","['15001902', '12167028', '12128125', '12121833..."
266938,15002501-M0-TST-M,"[(15002501, 3.2124274583113333, '15002501'), (...","[15002501, 13012970, 13013008, 13012990, 13012...","[3.2124274583113333, -8.992301271551884, -9.04...","['15002501', '13012970-M0', '13013008-M0', '13..."
266939,15003201-TST-MR,"[(13010083, -8.720605842392274, '13010083'), (...","[13010083, 12086914, 12141685, 12129683, 12197...","[-8.469807953172287, -8.469807953172287, -8.54...","['13010083-T1', '12086914-T2', '12141685', '12..."
266940,15003301-TST-MR,"[(12064635, -5.717136831089519, '12064635'), (...","[13002874, 13002874, 13002874, 13000481, 13000...","[-4.526188239770021, -4.526188239770021, -4.52...","['13002874-T3', '13002874', '13002874-T4', '13..."
266941,15004001-T0-TST-CP,"[(15004001, 6.589366858894488, '15004001-T0'),...","[15004001, 15004001, 15004001, 15004001, 15004...","[6.589366858894488, 6.589366858894488, 6.58936...","['15004001-T0', '15004001-T2', '15004001-M0', ..."
266942,15004001-T3-TST-M,"[(15004001, 5.284533012935136, '15004001-M0'),...","[15004001, 15004001, 15004001, 15004001, 15004...","[5.284533012935136, 5.284533012935136, 5.28453...","['15004001-M0', '15004001-T0', '15004001-T2', ..."
266943,15004501-TST-MR,"[(13010816, -8.662835125783134, '13010816'), (...","[13010816, 13010816, 12176384, 12176384, 12176...","[-8.662835125783134, -8.662835125783134, -8.74...","['13010816', '13010816-T1', '12176384-M0', '12..."
266944,15005002-TST-MR,"[(15005001, -2.649078876842355, '15005001-T0')...","[15005001, 15005001, 13012970, 13013008, 13012...","[-2.649078876842355, -2.649078876842355, -8.58...","['15005001-T0', '15005001', '13012970-M0', '13..."
266945,15005003-TST-MR,"[(13007239, -8.961372763501547, '13007239'), (...","[12122083, 12122083, 12122083, 12200274, 12131...","[-2.074059655096109, -2.074059655096109, -2.07...","['12122083-NV0', '12122083-NV1', '12122083', '..."
266946,15005004-TST-M,"[(12122083, -4.6222325875799815, '12122083'), ...","[12122083, 12122083, 12122083, 12200274, 12131...","[-4.6222325875799815, -4.6222325875799815, -4....","['12122083', '12122083-NV0', '12122083-NV1', '..."
266947,15005201-TST-MR,"[(13006838, -4.154421507721986, '13006838'), (...","[11003591, 13006838, 12133298, 12133298, 12133...","[-3.6088763568827313, -4.154421507721986, -5.1...","['11003591', '13006838', '12133298-M1', '12133..."
266948,15005401-TST-MR,"[(12183230, -9.260644266394058, '12183230-M0')...","[13012970, 13013008, 13012990, 13012883, 13012...","[-8.582948427365226, -8.630927570503811, -8.80...","['13012970-M0', '13013008-M0', '13012990-M0', ..."
266949,15005501-TST-M,"[(15005501, 6.661652513823077, '15005501-T2'),...","[15005501, 15005501, 15005501, 15005501, 15005...","[6.661652513823077, 6.661652513823077, 6.66165...","['15005501-T2', '15005501-T4', '15005501-T0', ..."
266950,15005801-T0-TST-M,"[(15005801, 2.4939280292831105, '15005801'), (...","[15005801, 13012990, 13012861, 13012821, 13012...","[2.4939280292831105, -8.706783415183724, -8.77...","['15005801', '13012990-M0', '13012861-M2', '13..."
266951,15005801-T1-TST-M,"[(15005801, 1.95007556792964, '15005801'), (12...","[15005801, 13012970, 13012990, 13013008, 12155...","[1.95007556792964, -9.187733113850484, -9.1961...","['15005801', '13012970-M0', '13012990-M0', '13..."
266952,15006601-TST-MR,"[(12153758, -8.665527227751145, '12153758'), (...","[12153758, 13012990, 13012861, 13012821, 13012...","[-8.665527227751145, -8.706783415183724, -8.77...","['12153758', '13012990-M0', '13012861-M2', '13..."
266953,15006701-TST-CP,"[(15006701, 7.501240700219417, '15006701'), (1...","[15006701, 12190659, 12190659, 12190659, 12190...","[7.501240700219417, -9.220973696417577, -9.220...","['15006701', '12190659-NV1', '12190659-NV2', '..."
266954,15006801-TST-MR,"[(15007401, -9.192189550049576, '15007401-M0')...","[13012970, 13013008, 13012990, 13012883, 13012...","[-8.688199544850056, -8.736178687988641, -8.90...","['13012970-M0', '13013008-M0', '13012990-M0', ..."

In [3]:
s.ordered_scores = [eval(x) for x in s.ordered_scores]
s.ordered_linked = [eval(x) for x in s.ordered_linked]
s.ordered_record = [eval(x) for x in s.ordered_record]

# Get test label

In [151]:
test = pd.read_csv("../dataset/original/test.csv", escapechar="\\")

In [152]:
test['split_name'] = test.record_id.str.split("-")
test['linked_id'] = test.split_name.apply(lambda x: x[0])

In [153]:
test.linked_id = test.linked_id.astype(int)

In [154]:
# get only test records

In [155]:
train = pd.read_csv("../dataset/original/train.csv", escapechar="\\")
train = train.sort_values(by='record_id').reset_index(drop=True)
test = test.sort_values(by='record_id').reset_index(drop=True)
train.linked_id = train.linked_id.astype(int)
train_linked = set(train.linked_id.values)
test_linked = set(test.linked_id.values)
only_test = test_linked - train_linked

In [156]:
only_test

{11010048,
 11010049,
 11010050,
 11010055,
 11010058,
 11010063,
 11010067,
 11010070,
 11010081,
 11010082,
 11010083,
 12058657,
 11010097,
 11010102,
 11010104,
 11010106,
 11010112,
 11010114,
 11010120,
 11010121,
 11010123,
 11010125,
 11010127,
 11010129,
 11010144,
 11010145,
 11010146,
 11010148,
 11010150,
 11010151,
 11010152,
 11010155,
 11010156,
 11010158,
 11010166,
 11010169,
 11010173,
 11010179,
 11010180,
 11010186,
 11010189,
 11010190,
 11010192,
 11010194,
 11010200,
 11010201,
 11010205,
 11010206,
 11010207,
 11010209,
 11010212,
 11010218,
 11010225,
 11010226,
 11010237,
 11010242,
 11010245,
 11010248,
 11010249,
 12058826,
 11010253,
 11010256,
 12058833,
 11010268,
 11010271,
 11010272,
 11010274,
 11010286,
 11010289,
 11010290,
 11010296,
 11010301,
 11010306,
 11010308,
 12058886,
 11010311,
 11010313,
 12058889,
 11010315,
 12058893,
 11010319,
 12058895,
 11010321,
 11010322,
 11010323,
 11010331,
 11010332,
 11010336,
 11010337,
 11010339,
 11010342,
 12058919,
 11010348,
 11010354,
 11010357,
 11010358,
 11010370,
 11010373,
 11010376,
 11010381,
 11010385,
 11010386,
 11010393,
 11010394,
 12058971,
 11010402,
 11010404,
 11010405,
 11010407,
 11010409,
 11010412,
 11010415,
 11010426,
 11010435,
 11010436,
 11010438,
 11010440,
 12059019,
 11010447,
 11010448,
 11010452,
 11010453,
 11010454,
 11010456,
 11010458,
 11010467,
 11010468,
 11010470,
 11010471,
 11010472,
 11010473,
 11010482,
 11010485,
 11010486,
 11010488,
 11010490,
 11010493,
 11010495,
 11010503,
 11010508,
 11010511,
 11010512,
 11010514,
 11010518,
 11010520,
 11010521,
 11010523,
 11010524,
 11010525,
 11010527,
 11010528,
 11010530,
 11010533,
 11010535,
 11010536,
 11010538,
 11010542,
 11010543,
 11010546,
 11010547,
 11010550,
 11010557,
 11010558,
 11010560,
 11010561,
 11010564,
 11010565,
 11010566,
 11010567,
 12059141,
 11010570,
 11010582,
 11010583,
 11010584,
 11010585,
 11010594,
 11010597,
 11010601,
 11010603,
 11010604,
 11010607,
 11010612,
 11010615,
 11010616,
 11010620,
 11010621,
 11010622,
 11010626,
 11010628,
 11010629,
 11010630,
 11010633,
 11010638,
 11010640,
 11010642,
 11010643,
 11010645,
 11010647,
 11010648,
 11010649,
 11010650,
 11010652,
 11010657,
 11010660,
 11010663,
 11010664,
 11010665,
 12059243,
 11010670,
 11010672,
 11010676,
 11010679,
 11010684,
 11010685,
 11010687,
 11010690,
 11010695,
 11010703,
 11010715,
 11010720,
 11010721,
 12059299,
 11010729,
 11010735,
 11010737,
 11010739,
 11010745,
 11010747,
 11010751,
 12059328,
 11010753,
 11010757,
 12059337,
 11010762,
 11010764,
 12059342,
 11010767,
 12059343,
 12059350,
 11010775,
 11010776,
 12140184,
 11010805,
 11010807,
 11010809,
 11010812,
 11010813,
 12059389,
 12140188,
 11010822,
 11010823,
 11010824,
 11010829,
 11010830,
 12059409,
 11010834,
 11010838,
 11010843,
 11010856,
 11010857,
 11010859,
 11010861,
 12059439,
 11010866,
 11010867,
 11010870,
 11010871,
 11010874,
 11010876,
 11010878,
 11010879,
 11010882,
 11010885,
 11010887,
 11010892,
 11010893,
 11010896,
 11010901,
 11010903,
 11010904,
 11010906,
 11010908,
 11010914,
 11010915,
 11010919,
 11010923,
 11010929,
 11010932,
 11010934,
 11010937,
 11010941,
 11010942,
 11010944,
 11010946,
 11010949,
 11010951,
 11010958,
 11010959,
 11010968,
 11010971,
 11010973,
 11010981,
 11010983,
 11010986,
 11010994,
 11010995,
 11010997,
 11011001,
 11011003,
 11011005,
 11011006,
 11011013,
 11011024,
 11011031,
 11011032,
 11011033,
 11011034,
 11011043,
 11011046,
 11011048,
 11011049,
 12059631,
 11011057,
 11011059,
 12059637,
 12059638,
 11011066,
 11011070,
 11011074,
 11011078,
 11011081,
 11011082,
 11011084,
 11011085,
 11011087,
 12059671,
 11011099,
 11011101,
 11011111,
 11011114,
 11011118,
 11011119,
 11011128,
 11011129,
 11011131,
 11011136,
 11011137,
 11011140,
 11011145,
 11011147,
 11011148,
 11011150,
 11011160,
 11011161,
 12059748,
 12059752,
 11011178,
 11011179,
 11011182,
 11011183,
 11011184,
 12059761,
 11011187,
 11011191,
 12059768,
 12059773,
 12059774,
 11011199,
 11011204,
 11011216,
 13004489,
 11011222,
 11011224,
 11011227,
 11011228,
 11011230,
 11011233,
 11011234,
 11011237,
 11011239,
 11011242,
 11011248,
 11011254,
 11011255,
 11011256,
 12059835,
 11011262,
 12059839,
 11011268,
 11011269,
 11011271,
 11011272,
 11011275,
 11011278,
 11011282,
 11011288,
 11011289,
 11011292,
 11011297,
 11011303,
 12059880,
 12059881,
 11011311,
 11011312,
 11011315,
 11011317,
 11011319,
 11011322,
 11011325,
 11011326,
 11011329,
 11011334,
 11011336,
 11011337,
 11011341,
 11011350,
 11011351,
 11011353,
 11011359,
 11011363,
 11011366,
 11011367,
 11011369,
 11011371,
 11011375,
 11011379,
 11011381,
 11011382,
 11011385,
 12059962,
 11011389,
 11011390,
 11011394,
 11011398,
 11011403,
 11011404,
 11011407,
 11011410,
 11011411,
 11011416,
 11011417,
 11011421,
 11011422,
 12059997,
 11011425,
 11011427,
 11011429,
 12060007,
 11011435,
 12060013,
 11011438,
 11011443,
 12060019,
 11011445,
 11011447,
 11011460,
 11011461,
 11011462,
 11011468,
 11011473,
 11011474,
 11011480,
 11011486,
 11011487,
 11011493,
 11011495,
 11011498,
 11011501,
 11011503,
 11011506,
 11011507,
 11011513,
 12060093,
 11011518,
 12060094,
 12060095,
 12060096,
 11011526,
 11011527,
 11011530,
 11011531,
 11011534,
 11011541,
 11011545,
 11011546,
 11011551,
 11011553,
 11011558,
 11011559,
 11011564,
 11011567,
 11011568,
 11011569,
 11011571,
 11011575,
 11011578,
 11011581,
 11011582,
 11011583,
 11011584,
 11011591,
 11011592,
 11011598,
 11011604,
 12060180,
 11011613,
 11011617,
 11011622,
 11011626,
 11011630,
 11011631,
 11011639,
 11011644,
 12060222,
 11011647,
 11011648,
 11011649,
 11011650,
 12060223,
 11011653,
 11011654,
 11011656,
 11011658,
 11011660,
 11011663,
 12060245,
 11011670,
 12060248,
 11011673,
 11011678,
 11011680,
 12060256,
 11011683,
 12060259,
 12060260,
 12060266,
 11011695,
 11011696,
 11011698,
 11011699,
 11011701,
 12060277,
 11011703,
 12060278,
 11011706,
 12060287,
 11011716,
 11011721,
 12060303,
 11011728,
 11011738,
 11011739,
 11011742,
 11011749,
 11011755,
 11011758,
 11011764,
 11011765,
 12060344,
 11011770,
 11011771,
 11011772,
 11011774,
 11011775,
 11011777,
 11011781,
 11011782,
 11011783,
 11011788,
 11011790,
 11011791,
 11011794,
 11011798,
 11011799,
 11011803,
 11011811,
 11011812,
 11011815,
 11011818,
 11011828,
 11011829,
 11011832,
 11011833,
 11011834,
 11011836,
 11011837,
 11011838,
 11011839,
 12060414,
 11011842,
 11011843,
 11011851,
 11011852,
 12060430,
 11011856,
 11011861,
 11011863,
 11011872,
 11011873,
 11011874,
 11011875,
 11011876,
 11011879,
 11011883,
 11011885,
 11011887,
 11011888,
 11011892,
 11011894,
 11011897,
 11011902,
 11011914,
 11011915,
 11011916,
 11011918,
 11011935,
 11011941,
 11011949,
 11011951,
 11011952,
 11011953,
 11011960,
 12060537,
 12060538,
 11011968,
 11011977,
 11011978,
 11011979,
 11011980,
 11011983,
 11011985,
 11011987,
 11011993,
 11011996,
 11011999,
 12060576,
 11012004,
 11012012,
 12060589,
 11012018,
 12060594,
 11012021,
 11012025,
 11012028,
 11012033,
 11012037,
 11012039,
 11012040,
 11012043,
 11012045,
 11012048,
 11012049,
 11012054,
 11012056,
 11012058,
 11012059,
 11012064,
 11012076,
 12060652,
 11012083,
 11012087,
 11012099,
 11012100,
 11012103,
 11012104,
 11012107,
 11012117,
 11012118,
 11012120,
 11012130,
 11012139,
 11012142,
 11012145,
 11012147,
 11012154,
 11012155,
 11012157,
 11012158,
 12060736,
 12060737,
 11012163,
 11012164,
 12060743,
 11012170,
 12060746,
 11012172,
 12060747,
 11012175,
 11012180,
 11012187,
 11012190,
 11012193,
 11012197,
 11012198,
 11012199,
 11012200,
 11012203,
 11012207,
 11012211,
 11012212,
 11012215,
 12060794,
 11012220,
 11012223,
 12060799,
 11012225,
 12060800,
 11012227,
 11012228,
 11012229,
 12060801,
 12060804,
 12060807,
 12060809,
 12060810,
 11012235,
 12060813,
 12060815,
 11012242,
 11012244,
 11012248,
 11012251,
 11012252,
 11012253,
 12060831,
 11012256,
 12060837,
 11012263,
 11012264,
 12060840,
 12060841,
 11012267,
 12060844,
 11012269,
 11012270,
 11012271,
 12060845,
 11012273,
 12060846,
 11012275,
 11012276,
 12060852,
 11012278,
 11012282,
 11012284,
 11012287,
 11012291,
 11012292,
 12060873,
 12060876,
 11012302,
 11012305,
 11012313,
 11012314,
 11012319,
 11012320,
 11012322,
 11012327,
 11012329,
 11012335,
 11012336,
 11012347,
 11012348,
 12060926,
 11012352,
 11012361,
 11012369,
 11012374,
 11012375,
 11012376,
 12060950,
 11012378,
 11012381,
 11012382,
 11012383,
 12060959,
 11012386,
 11012393,
 11012394,
 11012395,
 11012400,
 11012404,
 11012406,
 11012407,
 11012410,
 11012421,
 11012422,
 11012423,
 12061001,
 11012426,
 11012427,
 11012430,
 11012433,
 11012435,
 11012436,
 11012443,
 11012445,
 11012446,
 11012448,
 11012449,
 11012450,
 11012452,
 11012454,
 12061030,
 11012455,
 11012457,
 12061031,
 11012463,
 11012464,
 11012466,
 11012467,
 11012476,
 11012482,
 11012487,
 11012489,
 11012496,
 11012498,
 11012501,
 11012505,
 11012506,
 11012510,
 11012518,
 11012519,
 11012521,
 11012523,
 11012524,
 12061104,
 11012535,
 11012539,
 11012551,
 11012553,
 11012555,
 11012557,
 11012561,
 11012562,
 11012575,
 11012583,
 11012586,
 11012597,
 11012602,
 11012613,
 11012618,
 11012619,
 11012620,
 11012621,
 12061195,
 11012624,
 11012626,
 11012629,
 11012630,
 11012632,
 11012633,
 11012636,
 11012639,
 11012640,
 11012641,
 12061219,
 11012645,
 11012646,
 11012647,
 12061223,
 11012649,
 12061227,
 11012656,
 11012657,
 11012660,
 11012663,
 11012665,
 11012668,
 11012669,
 11012670,
 11012671,
 11012672,
 11012682,
 11012689,
 11012692,
 11012694,
 11012697,
 11012699,
 11012700,
 11012708,
 11012709,
 11012710,
 11012722,
 12061298,
 11012724,
 11012727,
 11012729,
 11012732,
 11012733,
 11012736,
 11012737,
 11012741,
 11012742,
 11012744,
 11012747,
 11012748,
 11012749,
 11012753,
 11012767,
 11012776,
 11012779,
 11012780,
 11012784,
 11012793,
 11012803,
 11012807,
 11012811,
 11012814,
 11012819,
 11012820,
 11012821,
 11012826,
 11012828,
 11012830,
 11012832,
 11012834,
 11012835,
 11012839,
 11012840,
 11012846,
 11012850,
 11012851,
 11012852,
 11012856,
 11012857,
 11012858,
 11012859,
 11012862,
 11012864,
 11012865,
 11012870,
 11012871,
 12061447,
 11012876,
 11012879,
 11012883,
 11012884,
 11012886,
 11012893,
 11012894,
 11012899,
 11012900,
 11012906,
 11012907,
 12061489,
 11012914,
 11012918,
 11012923,
 11012925,
 12061501,
 12061504,
 11012929,
 12061505,
 12061507,
 11012936,
 11012939,
 11012947,
 11012948,
 11012949,
 11012955,
 11012956,
 12061532,
 12061534,
 11012959,
 11012961,
 11012963,
 11012966,
 11012967,
 11012969,
 11012974,
 11012977,
 12061554,
 12061555,
 11012985,
 11012987,
 11012989,
 11012993,
 11012995,
 11012997,
 11012998,
 11012999,
 11013000,
 11013001,
 11013002,
 11013003,
 11013008,
 11013009,
 12061591,
 11013018,
 11013020,
 11013022,
 11013023,
 11013035,
 11013043,
 11013046,
 11013047,
 11013048,
 11013050,
 11013051,
 ...}

In [157]:
# Expand df
new_df = []
for (q, l, sc) in tqdm(zip(s.queried_record_id, s.ordered_linked, s.ordered_scores)):
        for x in range(len(l)):
            new_df.append((q, l[x], sc[x]))
            
sub = pd.DataFrame(new_df, columns=['queried_record_id', 'predicted_linked_id', 'score'])

HBox(children=(IntProgress(value=1, bar_style='info', max=1), HTML(value='')))

In [158]:
#sub = sub.sort_values(by='queried_record_id')
#test = test.sort_values(by='record_id')

In [159]:
sub = sub.merge(test[['record_id', 'linked_id']], how='left', left_on='queried_record_id', right_on='record_id').drop('record_id', axis=1)

In [160]:
sub.predicted_linked_id = sub.predicted_linked_id.astype(int)
sub.linked_id = sub.linked_id.astype(int)

In [161]:
sub['correct'] = np.where(sub.predicted_linked_id.values == sub.linked_id.values, 1, 0)

# Check scores on only test linked_id

In [17]:
sub.drop_duplicates('queried_record_id').shape

(266955, 5)

In [163]:
sub_only_test = sub[sub.linked_id.isin(only_test)]

In [19]:
sub_only_test.drop_duplicates('queried_record_id')

         queried_record_id  predicted_linked_id     score  linked_id  correct
0          10000003-TST-MR             10127532 -9.164867   10000003        0
50          10000008-TST-M             10043172  1.437203   10000008        0
150        10000013-TST-MR             10153043 -3.362891   10000013        0
200        10000016-TST-MR             10147072 -2.652029   10000016        0
250        10000017-TST-MR             10155088 -2.460387   10000017        0
600        10000024-TST-MR             10100649  3.504693   10000024        0
650        10000025-TST-MR             10038568  4.337165   10000025        0
850        10000028-TST-MR             10021933 -7.976158   10000028        0
900        10000030-TST-MR             10037339  3.991637   10000030        0
1100        10000034-TST-M             10213815 -0.289495   10000034        0
1350       10000037-TST-MR             10115101  0.429882   10000037        0
1400       10000038-TST-MR             10136074 -3.203970   10000038        0
1550       10000041-TST-MR             10057787  3.891856   10000041        0
1600       10000042-TST-MR             10214239  3.405312   10000042        0
1650       10000043-TST-MR             10175740 -1.162515   10000043        0
1700       10000044-TST-MR             10040019  1.874710   10000044        0
1900       10000050-TST-MR             10098513 -4.581791   10000050        0
2200       10000055-TST-MR             10184410  2.901667   10000055        0
2250       10000056-TST-MR             10040841  3.504693   10000056        0
2400       10000060-TST-MR             13012970 -8.502919   10000060        0
2450        10000061-TST-M             10193219 -1.741851   10000061        0
2500       10000063-TST-MR             10007006  2.275031   10000063        0
2950       10000074-TST-MR             10017941 -2.872044   10000074        0
3000       10000078-TST-MR             10146908 -2.836562   10000078        0
3100       10000081-TST-MR             10185020  3.108315   10000081        0
3150       10000082-TST-MR             13012970 -8.698351   10000082        0
3200       10000083-TST-MR             10110513  2.192449   10000083        0
3250       10000084-TST-MR             10192527  3.831806   10000084        0
3350        10000088-TST-M             12197456 -8.369011   10000088        0
3450       10000091-TST-MR             10036041  4.444302   10000091        0
...                    ...                  ...       ...        ...      ...
13344400   13013076-TST-MR             12190895 -9.285024   13013076        0
13344450   13013077-TST-MR             12210812  2.696823   13013077        0
13344500   13013078-TST-MR             13005138  3.733712   13013078        0
13344700   13013081-TST-MR             12116360  4.016418   13013081        0
13344750   13013082-TST-MR             12190724  2.261543   13013082        0
13345250   13013093-TST-MR             13007719  2.729289   13013093        0
13345300   13013094-TST-MR             12083250 -1.319029   13013094        0
13345550   13013098-TST-MR             12200055 -0.879852   13013098        0
13345600   13013100-TST-MR             12157965 -2.533208   13013100        0
13345650   13013102-TST-MR             12224905 -5.418000   13013102        0
13345700   13013103-TST-MR             13006932  2.835353   13013103        0
13345850   13013107-TST-MR             12127640 -3.001480   13013107        0
13346000   13013115-TST-MR             13005074 -2.989171   13013115        0
13346050    13013116-TST-M             12105383  4.095299   13013116        0
13346350    15000601-TST-M             13012970 -8.502919   15000601        0
13346400   15000801-TST-MR             12170250 -8.315911   15000801        0
13346450   15000901-TST-MR             13012970 -8.502919   15000901        0
13346550   15001301-TST-MR             11008337  3.108315   15001301        0
13346700   15001501-TST-MR             12127195 -3.793163   15001501        0
13346850   15001903-TST-MR             15001902 -1.761391   15001903        0
13346950   15003201-TST-MR             13010083 -8.469808   15003201        0
13347000   15003301-TST-MR             13002874 -4.526188   15003301        0
13347150   15004501-TST-MR             13010816 -8.662835   15004501        0
13347200   15005002-TST-MR             15005001 -2.649079   15005002        0
13347250   15005003-TST-MR             12122083 -2.074060   15005003        0
13347300    15005004-TST-M             12122083 -4.622233   15005004        0
13347350   15005201-TST-MR             11003591 -3.608876   15005201        0
13347400   15005401-TST-MR             13012970 -8.582948   15005401        0
13347600   15006601-TST-MR             12153758 -8.665527   15006601        0
13347700   15006801-TST-MR             13012970 -8.688200   15006801        0

[118566 rows x 5 columns]

In [22]:
# Rows di only_test che hanno il primo score > 0 : 33822 / 118566
sub_only_test.drop_duplicates('queried_record_id')[sub_only_test.score > 0].shape

c:\users\blueace17\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.

(33822, 5)

In [62]:
# Quanto è alto lo scores di questi elementi?
print(f'Max only_test score is {sub_only_test.score.max()} at index {sub_only_test.score.idxmax()}')
print(f'Max only_test score is {sub_only_test.score.min()} at index {sub_only_test.score.idxmin()}')

Max only_test score is 7.503930692616692 at index 12619750
Max only_test score is -18.063428064017355 at index 5837848

In [63]:
sub_only_test.loc[12619750]

queried_record_id      12216798-TST-MR
predicted_linked_id           12216879
score                          7.50393
linked_id                     12216798
correct                              0
Name: 12619750, dtype: object

In [64]:
test[test.record_id == '12216798-TST-MR']

,record_id,name,type,address,phone,email,modification,split_name,linked_id
15184,12216798-TST-MR,PRIMI LIMITED,officer,Suite 13; First Floor; Oliaji Trade Centre Cen...,3.968024e+09,NaN,move unique,"[12216798, TST, MR]",12216798

In [67]:
train[train.linked_id == 12216879]

,record_id,name,type,address,phone,email,modification,linked_id
532062,12216879,Primi Limited,officer,Suite 13; First Floor; Oliaji Trade Centre; Fr...,3.968024e+09,NaN,original,12216879

In [ ]:
# NON HA SENSO!

In [68]:
# Rows di only_test che hanno il primo score > 0 : 33822 / 118566
sub_only_test.drop_duplicates('queried_record_id')[sub_only_test.score > 0].shape

c:\users\blueace17\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.

(33822, 5)

In [23]:
# Rows di only_test che hanno il primo score < 0 :  84744 / 118566
sub_only_test.drop_duplicates('queried_record_id')[sub_only_test.score < 0].shape

c:\users\blueace17\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.

(84744, 5)

In [73]:
# Rows di tutto il test che hanno primo scores < 0: 85973 / 266955
sub.drop_duplicates('queried_record_id')[sub.score < 0].shape

c:\users\blueace17\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.

(85973, 5)

In [25]:
# Rows di tutto il test che hanno primo scores > 0: 180982 / 266955
sub.drop_duplicates('queried_record_id', keep='first')[sub.score > 0].shape

c:\users\blueace17\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.

(180982, 5)

## ==> Preso solo lo score più alto per ogni gruppo, su 266955 predizioni, in tutto il test ci sono 85973 scores minori di zero di cui 84744 sono di quelli che non hanno riferimenti nel train (only_test)

In [75]:
# TODO analizzare quali sono e come sono fatti gli scores del test che hanno riferimento nel train, dunque i 85973 - 84744 = 1229
# restanti

In [131]:
from scipy import *
from scipy.sparse import *
# Check sullo scores relativo alla similarità 
sim_name = load_npz('../jaccard_tfidf_name_original.npz')
sim_email = load_npz('../jaccard_tfidf_email_original.npz')
sim_phone = load_npz('../jaccard_tfidf_phone_original.npz')
sim_address = load_npz('../jaccard_tfidf_address_original.npz')
hybrid = sim_name + 0.05 * sim_email + 0.2 * sim_phone + 0.1 * sim_address

In [18]:
neg_df = sub.drop_duplicates('queried_record_id')[(sub.score < 0) & (~sub.linked_id.isin(only_test))]
neg_df

c:\users\blueace17\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.

,queried_record_id,predicted_linked_id,score,linked_id,correct
23600,10000699-T0-TST-M,10084056,-3.008590,10000699,0
23650,10000699-T1-TST-M,10084998,-5.385835,10000699,0
45400,10001313-T1-TST-M,13012883,-8.734113,10001313,0
58500,10001680-T0-TST-M,13012970,-8.502919,10001680,0
63350,10001804-T1-TST-M,12147569,-3.959800,10001804,0
68100,10001933-M2-TST-CP,10001933,-0.170020,10001933,1
76600,10002180-T1-TST-M,10136340,-3.904034,10002180,0
89150,10002543-T1-TST-M,10002543,-0.510937,10002543,1
90950,10002602-T3-TST-M,13012970,-8.698351,10002602,0
92850,10002648-T1-TST-M,12033147,-2.167972,10002648,0
127850,10003673-T1-TST-M,13012970,-8.698351,10003673,0
129450,10003714-T1-TST-M,13012990,-8.706783,10003714,0
144950,10004168-T2-TST-M,13012970,-8.502919,10004168,0
146050,10004191-T0-TST-M,10004191,-1.249682,10004191,1
148050,10004254-T1,10004254,-0.628934,10004254,1
148200,10004254-T4,13012970,-8.502919,10004254,0
152700,10004384-T1-TST-M,13012970,-8.502919,10004384,0
189800,10005425-T4-TST-M,10017189,-5.297769,10005425,0
196150,10005607-T0-TST-M,13012970,-8.502919,10005607,0
213150,10006146-M1-TST-M,10006146,-0.125062,10006146,1
223550,10006466-NV0-TST-M,10006466,-0.063002,10006466,1
284250,10008137-T3-TST-M,10012201,-1.579986,10008137,0
322500,10009241-NV0-TST-M,10114884,-0.019895,10009241,0
322900,10009249-T2-TST-M,13012970,-8.502919,10009249,0
328900,10009416-TST-M,10158535,-0.131678,10009416,0
331050,10009486-M0-TST-CP,10009486,-0.152019,10009486,1
343900,10009866-T3-TST-M,13012970,-8.582948,10009866,0
352400,10010136-T0-TST-M,13012970,-8.502919,10010136,0
354850,10010195-T4,13012970,-8.502919,10010195,0
358000,10010295-T4-TST-M,13012970,-8.582948,10010295,0
...,...,...,...,...,...
12982550,13002566-M0-TST-M,13002566,-0.105249,13002566,1
13014550,13003474-M0-TST-M,13003474,-0.828221,13003474,1
13014600,13003474-M1-TST-M,13003474,-0.828221,13003474,1
13015800,13003502-T3,10081967,-5.191590,13003502,0
13024450,13003766-M1-TST-CP,13003766,-0.091233,13003766,1
13035300,13004104-T2-TST-M,13012890,-8.451253,13004104,0
13049400,13004486-T2-TST-M,13012894,-8.451253,13004486,0
13058850,13004741-M1-TST-M,12186039,-0.074033,13004741,0
13066300,13004921-NV2-TST-M,13004921,-0.339705,13004921,1
13071650,13005065-NV1-TST-M,12138710,-0.689974,13005065,0
13081850,13005363-T0-TST-M,13013036,-8.298692,13005363,0
13136800,13006973-M0-TST-CP,12143201,-0.177236,13006973,0
13141000,13007091-M1-TST-CP,13007091,-0.093491,13007091,1
13147100,13007261-M2-TST-CP,13007261,-0.044638,13007261,1
13147700,13007278-M0-TST-CP,13007278,-0.177808,13007278,1
13182950,13008290-NV1-TST-M,12206434,-0.128623,13008290,0
13207750,13009028-M1-TST-CP,13009028,-0.311503,13009028,1
13210450,13009112-M1-TST-M,13009112,-0.040408,13009112,1
13210900,13009122-M0-TST-CP,13009122,-0.312655,13009122,1
13229800,13009650-NV0-TST-M,13009650,-0.285165,13009650,1
13230950,13009689-NV2-TST-M,13009689,-0.256879,13009689,1
13248100,13010179-T0,13013030,-0.393329,13010179,0
13248150,13010179-T1,13013030,-0.393329,13010179,0
13249700,13010215-NV2,12041856,-0.329647,13010215,0
13250650,13010247-M0-TST-M,12207939,-0.191755,13010247,0
13255300,13010379-M1-TST-CP,12150869,-0.350785,13010379,0
13272950,13010936-M1,12135468,-0.343525,13010936,0
13280950,13011168-M0-TST-M,12124254,-0.174266,13011168,0
13286400,13011333-T0-TST-M,13012895,-1.976821,13011333,0
13316150,13012236-M1,13012236,-0.296094,13012236,1

In [ ]:
10009416-TST-M

In [19]:
# Numero di quelli che azzecchiamo tra quelli che hanno il primo scores negativo e hanno riferimento nel train: 338/1229
neg_df.correct.sum()

338

In [44]:
# Check di come sono fatti quelli che sbagliamo
test[test.record_id == '10000699-T0-TST-M']

,record_id,name,type,address,phone,email,modification,split_name,linked_id
472,10000699-T0-TST-M,CALICz LIMIqED,entity,NaN,NaN,consulting@protonmail.co.uk,move row,"[10000699, T0, TST, M]",10000699

In [45]:
# Our prediction
train[train.linked_id == 10084056]

,record_id,name,type,address,phone,email,modification,linked_id
149186,10084056,JARA LIMITED,entity,NaN,NaN,NaN,original,10084056
149187,10084056-M0,JARA LIMITED,entity,NaN,NaN,NaN,missing,10084056
149188,10084056-NV0,JARA LIMITED,entity,NaN,3.986306e+09,NaN,new_value,10084056
149189,10084056-NV1,JARA LIMITED,entity,C-106; 393 Emirates Hill First; PO Box 213384;...,NaN,NaN,new_value,10084056
149190,10084056-T1,JARA LIMITED,entity,NaN,NaN,NaN,typo,10084056
149191,10084056-T2,JAlg LIMIqED,entity,NaN,NaN,NaN,typo,10084056
149192,10084056-T3,JARA LIMITED,entity,NaN,NaN,NaN,typo,10084056

In [46]:
# Correct Answer
train[train.linked_id == 10000699] # COM'E' POSSIBILE CHE NON LO BECCHI?

,record_id,name,type,address,phone,email,modification,linked_id
1242,10000699,CALICO LIMITED,entity,NaN,NaN,consulting@protonmail.co.uk,original,10000699

In [124]:
hybrid[472, 149191] # Scores

0.15991257

In [125]:
hybrid[472, 1242] # Com'è possibile?

0.3474137

In [73]:
sorted(hybrid[472].data)[::-1][:50]

[0.36820403,
 0.36494386,
 0.3456618,
 0.32734066,
 0.32544965,
 0.31982514,
 0.31665355,
 0.3131016,
 0.31063476,
 0.308229,
 0.30356756,
 0.3030669,
 0.30168438,
 0.30077326,
 0.3,
 0.3,
 0.3,
 0.3,
 0.3,
 0.3,
 0.3,
 0.3,
 0.3,
 0.3,
 0.3,
 0.3,
 0.3,
 0.3,
 0.3,
 0.3,
 0.3,
 0.3,
 0.3,
 0.3,
 0.3,
 0.3,
 0.3,
 0.3,
 0.3,
 0.3,
 0.3,
 0.3,
 0.3,
 0.3,
 0.3,
 0.3,
 0.3,
 0.3,
 0.3,
 0.3]

In [76]:
print(sim_name[472, 149191])
print(sim_name[472, 1242])

0.31982514
0.22961001

In [121]:
sim_name_cos = load_npz('../similarity_cosine_complete_name.npz')

In [122]:
print(sim_name_cos[472, 149191])
print(sim_name_cos[472, 1242])

0.0
0.9130434

In [ ]:
sim_email[]

In [79]:
# Secondo Esempio  --> Ci deve essere un problema nella similarità poiché la risposta giusta non compare tra le top50
test[test.record_id == '10000699-T1-TST-M']

,record_id,name,type,address,phone,email,modification,split_name,linked_id
473,10000699-T1-TST-M,CALICw LIMITxD,entity,NaN,NaN,cptsulting@protonmail.co.uk,move row,"[10000699, T1, TST, M]",10000699

In [80]:
train[train.linked_id == 10084998]

,record_id,name,type,address,phone,email,modification,linked_id
150864,10084998,SEARA LIMITED,entity,NaN,4.411365e+11,NaN,original,10084998
150865,10084998-T0,SEARAzLIMIqED,entity,NaN,4.511362e+11,NaN,typo,10084998
150866,10084998-T1,SEARA LIMITED,entity,NaN,4.411363e+11,NaN,typo,10084998
150867,10084998-T2,SExRA LIMITED,entity,NaN,4.411365e+11,NaN,typo,10084998
150868,10084998-T3,SEisA LIMITxD,entity,NaN,8.401365e+11,NaN,typo,10084998

In [81]:
# Terzo Esempio
test[test.record_id == '10001313-T1-TST-M']

,record_id,name,type,address,phone,email,modification,split_name,linked_id
908,10001313-T1-TST-M,Investors (Nzmznees) Ltd.,entity,NaN,NaN,NaN,move row,"[10001313, T1, TST, M]",10001313

In [82]:
train[train.linked_id == 13012883]

,record_id,name,type,address,phone,email,modification,linked_id
690953,13012883,Mr. André MARTINEZ,officer,SEN MINES MBODIENNE / KM 10 ROUTE DE JOAL / MB...,NaN,MrAndreMARTINEZ@aol.com,original,13012883
690954,13012883-M0,Mr. André MARTINEZ,officer,NaN,NaN,NaN,missing,13012883
690955,13012883-NV0,Mr. André MARTINEZ,officer,SEN MINES MBODIENNE / KM 10 ROUTE DE JOAL / MB...,NaN,NaN,new_value,13012883
690956,13012883-NV1,Mr. André MARTINEZ,officer,"CRA. 67 NO. 180-24 CASA 2, BOGOTA COLOMBIA",NaN,MrAndreMARTINEZ@aol.com,new_value,13012883

In [83]:
# Correct Answer
train[train.linked_id == 10001313]

,record_id,name,type,address,phone,email,modification,linked_id
2387,10001313-T0,Investors (Nominees) Ltd.,entity,NaN,NaN,NaN,typo,10001313
2388,10001313-T2,envestors (Nominees) Ltd.,entity,NaN,NaN,NaN,typo,10001313

In [91]:
print(hybrid[908, 690954])
print(hybrid[908, 2387])

0.35
0.3290047

## Guardiamo quelle di only_test che hanno primo score > 0: perché è > 0?

In [164]:
sub_ot_gt_0 = sub_only_test.drop_duplicates('queried_record_id')[sub_only_test.score > 0]

c:\users\blueace17\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.

In [165]:
sub_ot_gt_0

         queried_record_id  predicted_linked_id     score  linked_id  correct
50          10000008-TST-M             10043172  1.437203   10000008        0
600        10000024-TST-MR             10100649  3.504693   10000024        0
650        10000025-TST-MR             10038568  4.337165   10000025        0
900        10000030-TST-MR             10037339  3.991637   10000030        0
1350       10000037-TST-MR             10115101  0.429882   10000037        0
1550       10000041-TST-MR             10057787  3.891856   10000041        0
1600       10000042-TST-MR             10214239  3.405312   10000042        0
1700       10000044-TST-MR             10040019  1.874710   10000044        0
2200       10000055-TST-MR             10184410  2.901667   10000055        0
2250       10000056-TST-MR             10040841  3.504693   10000056        0
2500       10000063-TST-MR             10007006  2.275031   10000063        0
3100       10000081-TST-MR             10185020  3.108315   10000081        0
3200       10000083-TST-MR             10110513  2.192449   10000083        0
3250       10000084-TST-MR             10192527  3.831806   10000084        0
3450       10000091-TST-MR             10036041  4.444302   10000091        0
3650       10000100-TST-MR             10031861  1.318137   10000100        0
3800       10000104-TST-MR             10192467  2.939688   10000104        0
3850       10000107-TST-MR             12172848  3.257900   10000107        0
4050       10000118-TST-MR             10042720  3.350419   10000118        0
4100       10000120-TST-MR             10045927  1.444711   10000120        0
4650        10000138-TST-M             10176683  2.216351   10000138        0
5050       10000147-TST-MR             10036957  3.486097   10000147        0
5700        10000165-TST-M             10190536  3.108315   10000165        0
6100       10000179-TST-MR             10064271  0.749149   10000179        0
6650        10000206-TST-M             10003665  1.571624   10000206        0
7450       10000224-TST-MR             10023958  0.134197   10000224        0
9600       10000284-TST-MR             10127753  3.770020   10000284        0
9650       10000286-TST-MR             10026141  1.702716   10000286        0
12200      10000351-TST-MR             10147412  2.099432   10000351        0
12250      10000352-TST-MR             10121492  2.646359   10000352        0
...                    ...                  ...       ...        ...      ...
13340200   13012953-TST-MR             12169754  4.565292   13012953        0
13340450   13012957-TST-MR             12185323  3.493692   13012957        0
13340600   13012962-TST-MR             12173944  0.012599   13012962        0
13340900   13012967-TST-MR             12100915  4.197231   13012967        0
13341000   13012973-TST-MR             13012669  3.022071   13012973        0
13341300   13012981-TST-MR             13005798  0.986118   13012981        0
13341400   13012983-TST-MR             12121727  0.424187   13012983        0
13341550   13012987-TST-MR             12185060  2.093474   13012987        0
13341800   13012994-TST-MR             12177912  1.380329   13012994        0
13341900   13012999-TST-MR             12212144  1.808504   13012999        0
13342150   13013006-TST-MR             12167031  3.967308   13013006        0
13342250   13013010-TST-MR             12188831  3.830843   13013010        0
13343150   13013032-TST-MR             12180761  3.830843   13013032        0
13343250   13013038-TST-MR             12188392  0.375521   13013038        0
13343600   13013049-TST-MR             13000581  0.071313   13013049        0
13343650   13013050-TST-MR             12201534  2.808470   13013050        0
13343800    13013052-TST-M             12139143  3.154800   13013052        0
13343850   13013054-TST-MR             12095379  1.570797   13013054        0
13344050   13013061-TST-MR             13002261  2.923809   13013061        0
13344100   13013065-TST-MR             12203116  3.551692   13013065        0
13344150   13013067-TST-MR             12141181  3.927479   13013067        0
13344300   13013074-TST-MR             13006489  2.863179   13013074        0
13344450   13013077-TST-MR             12210812  2.696823   13013077        0
13344500   13013078-TST-MR             13005138  3.733712   13013078        0
13344700   13013081-TST-MR             12116360  4.016418   13013081        0
13344750   13013082-TST-MR             12190724  2.261543   13013082        0
13345250   13013093-TST-MR             13007719  2.729289   13013093        0
13345700   13013103-TST-MR             13006932  2.835353   13013103        0
13346050    13013116-TST-M             12105383  4.095299   13013116        0
13346550   15001301-TST-MR             11008337  3.108315   15001301        0

[33822 rows x 5 columns]

In [ ]:
# Molti di questi hanno il nome moolto simile se non identico, però in tutti gli altri campi hanno NaN oppure valori completamente
# differenti. Per tutti quelli che hanno nome molto simile ma il resto diverso o Nan dovremmo gestirli a parte, anche per 
# capire se questi hanno riferimenti nel test o no. Oppure possiamo semplicemente estrarre quelli che appunto sono
# con nome uguale o molto simile e tutti gli altri NaN e dire che per questi è difficile avere una predizione corretta
# poiché le informazioni sono poche. Nel caso in cui invece il nome è uguale o molto simile e ci sono anche altri campi, ma 
# sono tutti diversi, allora anche in questo caso possiamo dire poco e nulla (guardare similarità degli altri campi con Jaro-Winkler)

In [193]:
df_test[df_test.record_id == '10000044-TST-MR']

,record_id,name,type,address,phone,email,modification
34,10000044-TST-MR,GOLDEN NET INTERNATIONAL LIMITED,entity,AKMJ CONSULTING SERVICES LIMITED 20/F.; BANGKO...,NaN,help@zoho.cz,move unique

In [194]:
train[train.linked_id == 10040019]

,record_id,name,type,address,phone,email,modification,linked_id
71551,10040019,golden net international limited,entity,NaN,4.950848e+10,info@GOLDEN.NET.INTERNATIONAL.LIMITED.ch,original,10040019
71552,10040019-NV0,golden net international limited,entity,44 Esplanade; St. Helier; Jersey; C.I,4.950848e+10,info@GOLDEN.NET.INTERNATIONAL.LIMITED.ch,new_value,10040019
71553,10040019-NV1,golden net international limited,entity,FLAT D; 15/F.; BLOCK 1; RONSDALE GARDEN; 25 TA...,1.850736e+10,info@GOLDEN.NET.INTERNATIONAL.LIMITED.ch,new_value,10040019
71554,10040019-NV2,golden net international limited,entity,NaN,4.950848e+10,support@gmail.com,new_value,10040019

In [174]:
train.name = train.name.str.lower()

In [176]:
train.name = train.name.fillna("")

In [178]:
train[train.name.str.contains('git co')]

,record_id,name,type,address,phone,email,modification,linked_id
68952,10038568,git co inc.,entity,NaN,NaN,NaN,original,10038568

In [179]:
train[train.linked_id == 10038568]

,record_id,name,type,address,phone,email,modification,linked_id
68952,10038568,git co inc.,entity,NaN,NaN,NaN,original,10038568

In [ ]:
# Stesso problema di prima: c'è un chiaro riferimento nel train ma non viene beccato

In [ ]:
# TODO guardare quanti ne sbagliamo (o azzecchiamo) con scores < 0

# Check doppioni nel test 
## Potremmo pensare di fare una similarità test-test per riconoscere quelli simili.

In [93]:
# TODO controllare se ci sono doppioni nel test, nel senso che nel test ci potrebbero essere due record che si 
# riferiscono alla stesse entità

In [46]:
test[test.linked_id.isin(only_test)].drop_duplicates('linked_id').shape # 118566 - 118112 = 434 duplicati del solo test

(118112, 9)

In [55]:
# estraimo solo le rows che hanno duplicati in only_test
mask = (test.linked_id.isin(only_test)) & (test.duplicated(subset=['linked_id'], keep=False))
test[mask].sort_values(by='record_id')

,record_id,name,type,address,phone,email,modification,split_name,linked_id
160982,10000500-T0-TST-M,EAST ASIA PALM hO.c LTD,entity,NaN,4.419548e+11,NaN,move row,"[10000500, T0, TST, M]",10000500
169604,10000500-TST-M,"EAST ASIA PALM CO., LTD",entity,NaN,4.419598e+11,NaN,move row,"[10000500, TST, M]",10000500
154178,10001224-M0-TST-M,VICTORY SECRET LTD.,entity,NaN,1.900123e+10,support@icloud.gov,move row,"[10001224, M0, TST, M]",10001224
110407,10001224-M1-TST-M,VICTORY SECRET LTD.,entity,NaN,NaN,NaN,move row,"[10001224, M1, TST, M]",10001224
142016,10001224-TST-M,VICTORY SECRET LTD.,entity,NaN,1.900123e+10,support@icloud.gov,move row,"[10001224, TST, M]",10001224
113182,10002261-NV0-TST-M,"LONGKOU FANLIN NODULAR CAST IRON PIPE CO.,LTD.",entity,6310 WATERBURY RD NANAIMO BC V9V 1M3 CANADA,NaN,NaN,move row,"[10002261, NV0, TST, M]",10002261
155911,10002261-TST-M,"LONGKOU FANLIN NODULAR CAST IRON PIPE CO.,LTD.",entity,NaN,4.107031e+12,NaN,move row,"[10002261, TST, M]",10002261
155413,10002752-NV0-TST-M,WALBRAY TRADING LTD.,entity,NaN,NaN,NaN,move row,"[10002752, NV0, TST, M]",10002752
137941,10002752-TST-M,WALBRAY TRADING LTD.,entity,NaN,NaN,NaN,move row,"[10002752, TST, M]",10002752
138922,10003124-M0-TST-M,MANDELBAUM LTD. INC.,entity,NaN,NaN,NaN,move row,"[10003124, M0, TST, M]",10003124
131337,10003124-TST-M,MANDELBAUM LTD. INC.,entity,NaN,1.356913e+10,NaN,move row,"[10003124, TST, M]",10003124
168884,10003732-NV0-TST-M,PROFIT SMART ENTERPRISES LTD.,entity,NaN,NaN,inquires@PROFIT.SMART.ENTERPRISES.LTD.com,move row,"[10003732, NV0, TST, M]",10003732
152426,10003732-TST-M,PROFIT SMART ENTERPRISES LTD.,entity,NaN,3.943087e+09,help@zoho.com,move row,"[10003732, TST, M]",10003732
151911,10005571-NV0-TST-M,ENPREX S.A.,entity,Spartakovskaya Street 6-8; Moscow; Russia,4.149003e+12,NaN,move row,"[10005571, NV0, TST, M]",10005571
134758,10005571-TST-M,ENPREX S.A.,entity,NaN,4.149003e+12,NaN,move row,"[10005571, TST, M]",10005571
160428,10005601-M0-TST-M,Neotecmedical Inc.,entity,Neotecmedical Inc. 520 S. 7TH STREET SUITE C L...,1.937160e+10,NaN,move row,"[10005601, M0, TST, M]",10005601
161381,10005601-T0-TST-M,Neotecmedical Inc.,entity,Neotecmedical Inc. 520 S. 7TH STREET SUITE C L...,1.937160e+10,sales@yahoo.ch,move row,"[10005601, T0, TST, M]",10005601
170219,10005601-TST-M,Neotecmedical Inc.,entity,Neotecmedical Inc. 520 S. 7TH STREET SUITE C L...,1.937160e+10,sales@yahoo.ch,move row,"[10005601, TST, M]",10005601
106557,10005733-NV0-TST-M,LIKOU INC.,entity,NaN,NaN,NaN,move row,"[10005733, NV0, TST, M]",10005733
148960,10005733-TST-M,LIKOU INC.,entity,NaN,3.980124e+09,NaN,move row,"[10005733, TST, M]",10005733
133609,10006451-NV0-TST-M,MAYFIELD TRADING LTD.,entity,NaN,NaN,NaN,move row,"[10006451, NV0, TST, M]",10006451
112224,10006451-TST-M,MAYFIELD TRADING LTD.,entity,NaN,4.201098e+11,NaN,move row,"[10006451, TST, M]",10006451
149457,10006767-M0-TST-M,PRIVA FINANCE S.A.,entity,NaN,NaN,NaN,move row,"[10006767, M0, TST, M]",10006767
127748,10006767-TST-M,PRIVA FINANCE S.A.,entity,NaN,4.202333e+11,PRIVAFINANCESA@yahoo.ch,move row,"[10006767, TST, M]",10006767
122640,10008908-T0-TST-M,WILDPARK HOLDING INC.,entity,STANDARD wHARTERED BANK (SiITZERLAND) SA CASE ...,NaN,NaN,move row,"[10008908, T0, TST, M]",10008908
111020,10008908-T1-TST-M,WILDPARK oOLDING INC.,entity,STANDARD CHARTERED BANK (SWITZERLAND) SA CASE ...,NaN,NaN,move row,"[10008908, T1, TST, M]",10008908
165721,10008908-TST-M,WILDPARK HOLDING INC.,entity,STANDARD CHARTERED BANK (SWITZERLAND) SA CASE ...,NaN,NaN,move row,"[10008908, TST, M]",10008908
159870,10009498-M0-TST-M,REIGHTON EQUITIES INC.,entity,NaN,NaN,NaN,move row,"[10009498, M0, TST, M]",10009498
136814,10009498-TST-M,REIGHTON EQUITIES INC.,entity,NaN,NaN,NaN,move row,"[10009498, TST, M]",10009498
167112,10010194-NV0-TST-M,CARDER INC.,entity,UB ECUADOR HOLDINGS; LLC 520 S. 7TH STREET SU...,NaN,NaN,move row,"[10010194, NV0, TST, M]",10010194
...,...,...,...,...,...,...,...,...,...
113998,12219159-TST-M,Tuscan Crest Limited,officer,"Trident Chambers PO Box 146 Road Town, Tortola...",3.323567e+11,NaN,move row,"[12219159, TST, M]",12219159
124600,12219625-M0-TST-M,Waldemar WITT,officer,NaN,NaN,WaldemarWITT@yahoo.de,move row,"[12219625, M0, TST, M]",12219625
172186,12219625-M1-TST-M,Waldemar WITT,officer,NaN,NaN,NaN,move row,"[12219625, M1, TST, M]",12219625
120359,12219625-TST-M,Waldemar WITT,officer,U1. MRAMORNAYA 14-134 116142 PODOLSK RUSSIA,NaN,WaldemarWITT@yahoo.de,move row,"[12219625, TST, M]",12219625
129550,12219679-NV0-TST-M,PEAK ENTERPRISES LIMITED,officer,57.594.426/0001-38; Alameda Araguaia; 3718; 1°...,4.453421e+11,NaN,move row,"[12219679, NV0, TST, M]",12219679
110858,12219679-TST-M,PEAK ENTERPRISES LIMITED,officer,TOP FLOOR; 14 ATHOL STREET; DOUGLAS; ISLE OF MAN,4.453421e+11,NaN,move row,"[12219679, TST, M]",12219679
160231,12221232-NV0-TST-M,PASAWEE LIMITED,officer,UNIT 1605-6; 16TH FLOOR; INFINITUS PLAZA; 199 ...,3.975432e+09,NaN,move row,"[12221232, NV0, TST, M]",12221232
180027,12221232-NV1-TST-M,PASAWEE LIMITED,officer,UNIT 1605-6; 16TH FLOOR; INFINITUS PLAZA; 199 ...,NaN,NaN,move row,"[12221232, NV1, TST, M]",12221232
164349,12221232-TST-M,PASAWEE LIMITED,officer,UNIT 1605-6; 16TH FLOOR; INFINITUS PLAZA; 199 ...,NaN,NaN,move row,"[12221232, TST, M]",12221232
162645,13000820-T0-TST-M,TEREZIA aIqLAY,officer,11 AVENUE PRINCESSE GRACE; MC 98 g00; MONACO,NaN,TEREZIqFINLAb@yahoo.de,move row,"[13000820, T0, TST, M]",13000820
125102,13000820-TST-M,TEREZIA FINLAY,officer,11 AVENUE PRINCESSE GRACE; MC 98 000; MONACO,NaN,TEREZIAFINLAY@yahoo.de,move row,"[13000820, TST, M]",13000820
160870,13001111-M0-TST-M,Rafi Elimelech,officer,NaN,4.201910e+11,NaN,move row,"[13001111, M0, TST, M]",13001111
116716,13001111-M1-TST-M,Rafi Elimelech,officer,"HaSahlav 102, Ramat Poleg - Israel",NaN,NaN,move row,"[13001111, M1, TST, M]",13001111
132608,13001111-TST-M,Rafi Elimelech,officer,"HaSahlav 102, Ramat Poleg - Israel",4.201910e+11,NaN,move row,"[13001111, TST, M]",13001111
154243,13002187-NV0-TST-M,Mrs. Zhanna Vdovina,officer,Apt 5 Gazovaya St 1a St Petesburg Russia,NaN,NaN,move row,"[13002187, NV0, TST, M]",13002187
163310,13002187-NV1-TST-M,Mrs. Zhanna Vdovina,officer,Apt 5 Gazovaya St 1a St Petesburg Russia,1.825716e+10,NaN,move row,"[13002187, NV1, TST, M]",13002187
112340,13002187-TST-M,Mrs. Zhanna Vdovina,officer,Apt 5 Gazovaya St 1a St Petesburg Russia,4.205860e+11,NaN,move row,"[13002187, TST, M]",13002187
158178,13004163-T0-TST-M,Ching Yu NG,officer,15/f EffectuallBdgo Henjessey Road; Wanchai; H...,4.920932e+10,NaN,move row,"[13004163, T0, TST, M]",13004163
158293,13004163-TST-M,Ching Yu NG,officer,15/f Effectual Bdg; Hennessey Road; Wanchai; H...,4.920922e+10,NaN,move row,"[13004163, TST, M]",13004163
180723,13006059-M0-TST-M,Carlos Rodrigo Figueiredo Lopes,officer,Rua do Castelo 156; 2240-334 Ferreira do Zezer...,NaN,NaN,move row,"[13006059, M0, TST, M]",13006059
159504,13006059-TST-M,Carlos Rodrigo Figueiredo Lopes,officer,Rua do Castelo 156; 2240-334 Ferreira do Zezer...,4.103285e+12,CarlosRodrigoFigueiredoLopes@gmail.co.uk,move row,"[13006059, TST, M]",13006059
109093,13006633-NV0-TST-M,JUAN PABLO CARVAJAL,officer,1ST FLOOR; 17 BOND STREET; ST HELEIR; JERSEY; ...,NaN,JUANPABLOCARVAJAL@yahoo.co.uk,move row,"[13006633, NV0, TST, M]",13006633
128572,13006633-TST-M,JUAN PABLO CARVAJAL,officer,Bethania Neighborhood; El Dorado Boulevard; Mi...,NaN,JUANPABLOCARVAJAL@yahoo.co.uk,move row,"[13006633, TST, M]",13006633
170128,13007078-NV0-TST-M,Raja Munahi ALBQAMI,officer,21 Alshenifi Drive; Riyadh 11683; Saudi Arabia,3.328548e+11,NaN,move row,"[13007078, NV0, TST, M]",13007078
153516,13007078-TST-M,Raja Munahi ALBQAMI,officer,21 Alshenifi Drive; Riyadh 11683; Saudi Arabia,3.328548e+11,NaN,move row,"[13007078, TST, M]",13007078
145502,13008702-NV0-TST-M,CITIC LIMITED,officer,32nd Floor; CITIC Tower; 1 Tim Mei Avenue; Cen...,1.257814e+10,NaN,move row,"[13008702, NV0, TST, M]",13008702
106174,13008702-NV1-TST-M,CITIC LIMITED,officer,RM 1203; NO 120; FENGYANGLI; SHUINAN; PENGJIAN...,3.994038e+09,NaN,move row,"[13008702, NV1, TST, M]",13008702
154820,13008702-TST-M,CITIC LIMITED,officer,32nd Floor; CITIC Tower; 1 Tim Mei Avenue; Cen...,3.994038e+09,NaN,move row,"[13008702, TST, M]",13008702
168901,13009786-M0-TST-M,ABERDEEN FOUNDATION,officer,NaN,NaN,NaN,move row,"[13009786, M0, TST, M]",13009786
121621,13009786-TST-M,ABERDEEN FOUNDATION,officer,Mossfon Bdlg; 54th Street; Panama; Rep. of Panama,4.200674e+11,NaN,move row,"[13009786, TST, M]",13009786

In [53]:
# Numero di duplicati in tutto il test?
mask = test.duplicated(subset=['linked_id'], keep='first')
test[mask].shape

(46540, 9)

In [ ]:
# TODO per il classificatore possiamo pensare a contare i campi che sono identici per vedere se sono presenti o no nel train

In [56]:
# TODO per cercare di individuare quelle che non hanno un corrispettivo nel train
# potremmo svalutare quei record che hanno un scores alto su più record_id ma questi record_id si riferiscono a linked_id diversi
"""
Per esempio se ho un caso di questo tipo
queried   linked   score
100       10029    4.356
100       10898    4.356
Allora può voler dire che due record_id del train sono molto simili al queried_record_id, il ché ci può stare ma anche no se 
ci sono davvero tanti scores alti con linked_id diversi per uno stesso queried: infatti potrebbe essere un caso in cui per esempio
il nome sia simile a molti elementi del train e gli altri campi del queried (address, phone, email) sono NaN
"""

'\nPer esempio se ho un caso di questo tipo\nqueried   linked   score\n100       10029    4.356\n100       10898    4.356\nAllora può voler dire che due record_id del train sono molto simili al queried_record_id, il ché ci può stare ma anche no se \nci sono davvero tanti scores alti con linked_id diversi per uno stesso queried: infatti potrebbe essere un caso in cui per esempio\nil nome sia simile a molti elementi del train e gli altri campi del queried (address, phone, email) sono NaN\n'

In [147]:
def n_different_linked_at_k(ordered_linked_id):
    res = np.empty(len(ordered_linked_id))
    for i in range(len(ordered_linked_id)):
        res[i] = set(ordered_linked_id[i][:10])
    return res

In [ ]:
# TODO guardare quanti ne sbagliamo (o azzecchiamo) con scores < 0 e quanti di questi sono solo nel only_test

In [ ]:
# TODO aggiungere le jaro_winkler anche per le altre colonne

In [9]:
# TODO per le queries per le quali siamo sicuri di raccomandare roba giusta, raccomandiamo solo quello. Per le altre raccomandiamo
# le top10

In [94]:
s

,queried_record_id,rec_pred,ordered_linked,ordered_scores,ordered_record
0,10000003-TST-MR,"[(10010930, -9.257270041531807, '10010930'), (...","[10127532, 10127532, 10127532, 10127532, 10127...","[-9.16486731510361, -9.16486731510361, -9.1648...","[10127532-M1, 10127532, 10127532-M0, 10127532-..."
1,10000008-TST-M,"[(10043172, 1.4372028433655306, '10043172-NV0'...","[10043172, 10043172, 10043172, 10107096, 10135...","[1.4372028433655306, 1.4372028433655306, 1.437...","[10043172-NV0, 10043172-M2, 10043172, 10107096..."
2,10000010-TST-CP,"[(10000010, 7.540006760334157, '10000010'), (1...","[10000010, 10192342, 12194552, 12194552, 12194...","[7.540006760334157, -4.190882268753726, -5.701...","[10000010, 10192342, 12194552-T1, 12194552, 12..."
3,10000013-TST-MR,"[(10153043, -3.3628909944191347, '10153043'), ...","[10153043, 10154534, 10147826, 10147826, 10147...","[-3.3628909944191347, -3.7838719061451003, -4....","[10153043, 10154534, 10147826, 10147826-NV0, 1..."
4,10000016-TST-MR,"[(10147072, -2.6520293768791405, '10147072-T0'...","[10147072, 10147072, 10104833, 10012410, 10113...","[-2.6520293768791405, -2.6520293768791405, -3....","[10147072-T0, 10147072, 10104833, 10012410, 10..."
5,10000017-TST-MR,"[(10094323, -3.073918357969311, '10094323-T0')...","[10155088, 10155088, 10155088, 10062221, 10062...","[-2.4603870175722458, -2.4603870175722458, -2....","[10155088, 10155088-M1, 10155088-M2, 10062221-..."
6,10000018-T4-TST-CP,"[(10000018, 7.498662877065813, '10000018-T4'),...","[10000018, 10000018, 10000018, 10000018, 10000...","[7.7508457993581725, 7.498662877065813, 7.3780...","[10000018-T0, 10000018-T4, 10000018-T3, 100000..."
7,10000018-TST-M,"[(10000018, 7.498662877065813, '10000018-T1'),...","[10000018, 10000018, 10000018, 10000018, 10000...","[8.031932312272719, 7.498662877065813, 7.37804...","[10000018-T0, 10000018-T1, 10000018-T3, 100000..."
8,10000020-NV0-TST-CP,"[(10000020, 3.303681326474439, '10000020'), (1...","[10000020, 10000020, 10000020, 10151492, 10094...","[3.303681326474439, 3.303681326474439, 3.30368...","[10000020, 10000020-NV0, 10000020-NV2, 1015149..."
9,10000020-NV1-TST-M,"[(10000020, 6.9544746513158575, '10000020'), (...","[10000020, 10000020, 10000020, 10151492, 10094...","[6.9544746513158575, 3.1177701468306704, 3.117...","[10000020, 10000020-NV0, 10000020-NV2, 1015149..."
10,10000022-TST-CP,"[(10000022, 7.816988049961335, '10000022'), (1...","[10000022, 10213858, 10213858, 10184573, 10046...","[7.816988049961335, -2.615097078753, -2.615097...","[10000022, 10213858-T0, 10213858, 10184573, 10..."
11,10000023-NV2-TST-CP,"[(10000023, 6.610937892873162, '10000023'), (1...","[10000023, 10000023, 10000023, 10000023, 10000...","[6.610937892873162, 6.610937892873162, 6.61093...","[10000023, 10000023-M1, 10000023-NV1, 10000023..."
12,10000024-TST-MR,"[(10100649, 3.5046931753835646, '10100649'), (...","[10100649, 10100649, 10214082, 10214082, 10214...","[3.5046931753835646, -0.36343866436934824, -5....","[10100649, 10100649-T0, 10214082-NV1, 10214082..."
13,10000025-TST-MR,"[(10038568, 4.337164684617, '10038568'), (1221...","[10038568, 12015628, 13012970, 13012990, 13012...","[4.337164684617, -8.403803345687871, -9.177581...","[10038568, 12015628, 13012970-M0, 13012990-M0,..."
14,10000027-M0-TST-M,"[(10000027, 7.2813890966503765, '10000027'), (...","[10000027, 10000027, 10000027, 10199071, 10199...","[7.2813890966503765, 7.2813890966503765, 6.601...","[10000027, 10000027-T2, 10000027-T3, 10199071-..."
15,10000027-T0-TST-M,"[(10000027, 7.2813890966503765, '10000027'), (...","[10000027, 10000027, 10000027, 10199071, 10199...","[7.2813890966503765, 7.2813890966503765, 6.601...","[10000027, 10000027-T2, 10000027-T3, 10199071-..."
16,10000027-T1-TST-M,"[(10000027, 7.2813890966503765, '10000027'), (...","[10000027, 10000027, 10000027, 10199071, 10199...","[7.2813890966503765, 7.2813890966503765, 6.693...","[10000027, 10000027-T2, 10000027-T3, 10199071-..."
17,10000028-TST-MR,"[(10132222, -9.818708384647271, '10132222'), (...","[10021933, 10021933, 10021933, 10093718, 10190...","[-7.976158046209574, -7.976158046209574, -7.97...","[10021933-M0, 10021933-NV0, 10021933, 10093718..."
18,10000030-TST-MR,"[(10037339, 3.9916365963611327, '10037339'), (...","[10037339, 10037339, 10108191, 10108191, 10034...","[3.9916365963611327, 0.8684033700316135, -0.37...","[10037339, 10037339-T0, 10108191, 10108191-NV0..."
19,10000031-M2-TST-M,"[(10000031, 1.021607162411545, '10000031'), (1...","[10000031, 10000031, 10000031, 10000031, 10000...","[1.021607162411545, 1.021607162411545, 1.02160...","[10000031, 10000031-M0, 10000031-M1, 10000031-..."
20,10000032-T0-TST-CP,"[(10000032, 6.806167281324907, '10000032-T0'),...","[10000032, 10000032, 10000032, 10000032, 10133...","[6.806167281324907, 5.736340495161974, -1.4163...","[10000032-T0, 10000032, 10000032-M1, 10000032-..."
21,10000032-T1-TST-M,"[(10000032, 6.571180986169107, '10000032'), (1...","[10000032, 10000032, 10000032, 10037597, 10037...","[6.571180986169107, 2.0311736912373277, 2.0311...","[10000032, 10000032-M0, 10000032-M1, 10037597,..."
22,10000034-TST-M,"[(10071366, -1.3599937789113583, '10071366'), ...","[10213815, 10213815, 10208443, 10071366, 10071...","[-0.28949473720108776, -0.28949473720108776, -...","[10213815, 10213815-T1, 10208443, 10071366, 10..."
23,10000036-NV0-TST-M,"[(10000036, 7.357723325322819, '10000036-T0'),...","[10000036, 10000036, 10184295, 10184295, 10184...","[7.357723325322819, 7.357723325322819, 0.40880...","[10000036-T0, 10000036-T2, 10184295-M1, 101842..."
24,10000036-NV1-TST-M,"[(10000036, 7.286054820342851, '10000036-T0'),...","[10000036, 10000036, 10184295, 10184295, 10184...","[7.286054820342851, 7.286054820342851, -0.5562...","[10000036-T0, 10000036-T2, 10184295, 10184295-..."
25,10000036-T0-TST-CP,"[(10000036, 7.357723325322819, '10000036-T0'),...","[10000036, 10000036, 10184295, 10184295, 10184...","[7.357723325322819, 7.357723325322819, 0.40880...","[10000036-T0, 10000036-T2, 10184295-M1, 101842..."
26,10000036-TST-M,"[(10000036, 7.357723325322819, '10000036-T0'),...","[10000036, 10000036, 10184295, 10184295, 10184...","[7.357723325322819, 7.357723325322819, 0.40880...","[10000036-T0, 10000036-T2, 10184295-M1, 101842..."
27,10000037-TST-MR,"[(10045833, -8.879981752592654, '10045833'), (...","[10115101, 10120582, 10115101, 10115101, 10097...","[0.42988207128793793, 0.22143225130650612, -1....","[10115101-T4, 10120582, 10115101, 10115101-T1,..."
28,10000038-TST-MR,"[(10136074, -3.2039696461266924, '10136074-NV0...","[10136074, 10136074, 10136074, 10136074, 10047...","[-3.2039696461266924, -3.2039696461266924, -3....","[10136074-NV0, 10136074-NV2, 10136074, 1013607..."
29,10000039-TST-CP,"[(10000039, 7.3122601183258675, '10000039'), (...","[10000039, 10000039, 10000039, 10000039, 12103...","[7.3122601183258675, 7.3122601183258675, 5.748...","[10000039, 10000039-T2, 10000039-T1, 10000039-..."
...,...,...,...,...,...
266925,13013118-TST-M,"[(13013118, 1.5793532925379852, '13013118-M0')...","[13013118, 13013118, 13012970, 13013008, 13012...","[1.5793532925379852, 1.5793532925379852, -8.99...","[13013118-M0, 13013118-NV0, 13012970-M0, 13013..."
266926,13013119-NV0-TST-CP,"[(13013119, 6.280596372077049, '13013119-NV0')...","[13013119, 13013119, 13013119, 12119080, 12119...","[6.280596372077049, 2.6715084897515835, 1.0587...","[13013119-NV0, 13013119, 13013119-NV1, 1211908..."
266927,15000601-TST-M,"[(15007401, -9.015842090645792, '15007401-M0')...","[13012970, 13013008, 13012990, 13012883, 13012...","[-8.502919062017646, -8.550898205156232, -8.72...","[13012970-M0, 13013008-M0, 13012990-M0, 130128..."
266928,15000801-TST-MR,"[(12160217, -9.107455931931765, '12160217'), (...","[12170250, 12170250, 12170250, 12211310, 12211...","[-8.315910657575868, -8.315910657575868, -8.31...","[12170250-T0, 12170250, 12170250-T3, 12211310,..."
266929,15000901-TST-MR,"[(15007401, -9.015842090645792, '15007401-M0')...","[13012970, 13013008, 13012990, 13012883, 13012...","[-8.502919062017646, -8.550898205156232, -8.72...","[13012970-M0, 13013008-M0, 13012990-M0, 130128..."
266930,15001201-NV0,"[(15001201, 3.486057713983367, '15001201'), (1...","[15001201, 12172071, 12223857, 13005835, 13001...","[3.486057713983367, -9.177803972359037, -9.177...","[15001201, 12172071-T0, 12223857, 13005835, 13..."
266931,15001301-TST-MR,"[(11008337, 3.108315427552664, '11008337'), (1...","[11008337, 12223335, 12098992, 12098992, 12098...","[3.108315427552664, -8.944724511174797, -8.953...","[11008337, 12223335-NV0, 12098992-T2, 12098992..."
266932,15001401-M0-TST-CP,"[(15001401, 1.073936271568702, '15001401-M2'),...","[15001401, 15001401, 15001401, 15001401, 12146...","[1.073936271568702, 1.073936271568702, 1.07393...","[15001401-M2, 15001401-M1, 15001401-M0, 150014..."
266933,15001401-M2-TST-CP,"[(15001401, 1.073936271568702, '15001401-M2'),...","[15001401, 15001401, 15001401, 15001401, 12146...","[1.073936271568702, 1.073936271568702, 1.07393...","[15001401-M2, 15001401-M1, 15001401-M0, 150014..."
266934,15001501-TST-MR,"[(12127195, -3.7931629136357308, '12127195'), ...","[12127195, 12218955, 12218955, 12218955, 12218...","[-3.7931629136357308, -4.6209148006731855, -4....","[12127195, 12218955-T2, 12218955-T1, 12218955-..."
266935,15001601-T3-TST-CP,"[(15001601, 7.466391189801397, '15001601-T3'),...","[15001601, 15001601, 15001601, 15001601, 15001...","[7.466391189801397, 6.730525470129731, 6.54421...","[15001601-T3, 15001601-T1, 15001601-T0, 150016..."
266936,15001801-T0-TST-CP,"[(15001801, 6.875714061206527, '15001801'), (1...","[15001801, 15001801, 15001801, 15001801, 12100...","[6.875714061206527, 6.875714061206527, 6.87571...","[15001801, 15001801-M0, 15001801-M1, 15001801-..."
266937,15001903-TST-MR,"[(15001902, -1.7613907534122795, '15001902'), ...","[15001902, 12167028, 12128125, 12121833, 12099...","[-1.7613907534122795, -8.2811005795159, -8.286...","[15001902, 12167028, 12128125, 12121833-NV0, 1..."
266938,15002501-M0-TST-M,"[(15002501, 3.2124274583113333, '15002501'), (...","[15002501, 13012970, 13013008, 13012990, 13012...","[3.2124274583113333, -8.992301271551884, -9.04...","[15002501, 13012970-M0, 13013008-M0, 13012990-..."
266939,15003201-TST-MR,"[(13010083, -8.720605842392274, '13010083'), (...","[13010083, 12086914, 12141685, 12129683, 12197...","[-8.469807953172287, -8.469807953172287, -8.54...","[13010083-T1, 12086914-T2, 12141685, 12129683,..."
266940,15003301-TST-MR,"[(12064635, -5.717136831089519, '12064635'), (...","[13002874, 13002874, 13002874, 13000481, 13000...","[-4.526188239770021, -4.526188239770021, -4.52...","[13002874-T3, 13002874, 13002874-T4, 13000481-..."
266941,15004001-T0-TST-CP,"[(15004001, 6.589366858894488, '15004001-T0'),...","[15004001, 15004001, 15004001, 15004001, 15004...","[6.589366858894488, 6.589366858894488, 6.58936...","[15004001-T0, 15004001-T2, 15004001-M0, 150040..."
266942,15004001-T3-TST-M,"[(15004001, 5.284533012935136, '15004001-M0'),...","[15004001, 15004001, 15004001, 15004001, 15004...","[5.284533012935136, 5.284533012935136, 5.28453...","[15004001-M0, 15004001-T0, 15004001-T2, 150040..."
266943,15004501-TST-MR,"[(13010816, -8.662835125783134, '13010816'), (...","[13010816, 13010816, 12176384, 12176384, 12176...","[-8.662835125783134, -8.662835125783134, -8.74...","[13010816, 13010816-T1, 12176384-M0, 12176384-..."
266944,15005002-TST-MR,"[(15005001, -2.649078876842355, '15005001-T0')...","[15005001, 15005001, 13012970, 13013008, 13012...","[-2.649078876842355, -2.649078876842355, -8.58...","[15005001-T0, 15005001, 13012970-M0, 13013008-..."
266945,15005003-TST-MR,"[(13007239, -8.961372763501547, '13007239'), (...","[12122083, 12122083, 12122083, 12200274, 12131...","[-2.074059655096109, -2.074059655096109, -2.07...","[12122083-NV0, 12122083-NV1, 12122083, 1220027..."
266946,15005004-TST-M,"[(12122083, -4.6222325875799815, '12122083'), ...","[12122083, 12122083, 12122083, 12200274, 12131...","[-4.6222325875799815, -4.6222325875799815, -4....","[12122083, 12122083-NV0, 12122083-NV1, 1220027..."
266947,15005201-TST-MR,"[(13006838, -4.154421507721986, '13006838'), (...","[11003591, 13006838, 12133298, 12133298, 12133...","[-3.6088763568827313, -4.154421507721986, -5.1...","[11003591, 13006838, 12133298-M1, 12133298, 12..."
266948,15005401-TST-MR,"[(12183230, -9.260644266394058, '12183230-M0')...","[13012970, 13013008, 13012990, 13012883, 13012...","[-8.582948427365226, -8.630927570503811, -8.80...","[13012970-M0, 13013008-M0, 13012990-M0, 130128..."
266949,15005501-TST-M,"[(15005501, 6.661652513823077, '15005501-T2'),...","[15005501, 15005501, 15005501, 15005501, 15005...","[6.661652513823077, 6.661652513823077, 6.66165...","[15005501-T2, 15005501-T4, 15005501-T0, 150055..."
266950,15005801-T0-TST-M,"[(15005801, 2.4939280292831105, '15005801'), (...","[15005801, 13012990, 13012861, 13012821, 13012...","[2.4939280292831105, -8.706783415183724, -8.77...","[15005801, 13012990-M0, 13012861-M2, 13012821-..."
266951,15005801-T1-TST-M,"[(15005801, 1.95007556792964, '15005801'), (12...","[15005801, 13012970, 13012990, 13013008, 12155...","[1.95007556792964, -9.187733113850484, -9.1961...","[15005801, 13012970-M0, 13012990-M0, 13013008-..."
266952,15006601-TST-MR,"[(12153758, -8.665527227751145, '12153758'), (...","[12153758, 13012990, 13012861, 13012821, 13012...","[-8.665527227751145, -8.706783415183724, -8.77...","[12153758, 13012990-M0, 13012861-M2, 13012821-..."
266953,15006701-TST-CP,"[(15006701, 7.501240700219417, '15006701'), (1...","[15006701, 12190659, 12190659, 12190659, 12190...","[7.501240700219417, -9.220973696417577, -9.220...","[15006701, 12190659-NV1, 12190659-NV2, 1219065..."
266954,15006801-TST-MR,"[(15007401, -9.192189550049576, '15007401-M0')...","[13012970, 13013008, 13012990, 13012883, 13012...","[-8.688199544850056, -8.736178687988641, -8.90...","[13012970-M0, 13013008-M0, 13012990-M0, 130128..."

In [95]:
restricted_pred = []
max_delta = 2.0
for (q, sc, rec) in tqdm(zip(s.queried_record_id, s.ordered_scores, s.ordered_record)):
    for x in range(len(sc)):
        if x == 0:
            restricted_pred.append((q, sc[x], rec[x]))
        else:
            if x >= 10:
                continue
            elif sc[0] - sc[x] < max_delta:
                restricted_pred.append((q, sc[x], rec[x]))
            else:
                continue

HBox(children=(IntProgress(value=1, bar_style='info', max=1), HTML(value='')))

In [29]:
restricted_df = pd.DataFrame(restricted_pred, columns=['queried_record_id', 'scores', 'predicted_record_id'])

In [30]:
restricted_df

         queried_record_id    scores predicted_record_id
0          10000003-TST-MR -9.164867         10127532-M1
1          10000003-TST-MR -9.164867            10127532
2          10000003-TST-MR -9.164867         10127532-M0
3          10000003-TST-MR -9.164867        10127532-NV2
4          10000003-TST-MR -9.164867         10127532-M2
5          10000003-TST-MR -9.164867        10127532-NV1
6          10000003-TST-MR -9.164867        10127532-NV0
7          10000003-TST-MR -9.164867         10144478-M2
8          10000003-TST-MR -9.164867         10144478-M1
9          10000003-TST-MR -9.164867         10144478-M0
10          10000008-TST-M  1.437203        10043172-NV0
11          10000008-TST-M  1.437203         10043172-M2
12          10000008-TST-M  1.437203            10043172
13         10000010-TST-CP  7.540007            10000010
14         10000013-TST-MR -3.362891            10153043
15         10000013-TST-MR -3.783872            10154534
16         10000013-TST-MR -4.565637            10147826
17         10000013-TST-MR -4.565637        10147826-NV0
18         10000013-TST-MR -4.565637        10147826-NV1
19         10000013-TST-MR -4.565637         10147826-T0
20         10000016-TST-MR -2.652029         10147072-T0
21         10000016-TST-MR -2.652029            10147072
22         10000016-TST-MR -3.122327            10104833
23         10000016-TST-MR -3.242855            10012410
24         10000016-TST-MR -4.496450            10113928
25         10000017-TST-MR -2.460387            10155088
26         10000017-TST-MR -2.460387         10155088-M1
27         10000017-TST-MR -2.460387         10155088-M2
28         10000017-TST-MR -3.036808         10062221-M1
29         10000017-TST-MR -3.036808         10062221-M0
...                    ...       ...                 ...
1225345    15005401-TST-MR -8.877019         13013019-M0
1225346    15005401-TST-MR -8.903018         13012895-M0
1225347     15005501-TST-M  6.661653         15005501-T2
1225348     15005501-TST-M  6.661653         15005501-T4
1225349     15005501-TST-M  6.661653         15005501-T0
1225350     15005501-TST-M  5.895679         15005501-T1
1225351     15005501-TST-M  4.767933         15005501-T3
1225352  15005801-T0-TST-M  2.493928            15005801
1225353  15005801-T1-TST-M  1.950076            15005801
1225354    15006601-TST-MR -8.665527            12153758
1225355    15006601-TST-MR -8.706783         13012990-M0
1225356    15006601-TST-MR -8.779901         13012861-M2
1225357    15006601-TST-MR -8.917624         13012821-M2
1225358    15006601-TST-MR -8.917624         13012895-M0
1225359    15006601-TST-MR -8.944080         13012832-M0
1225360    15006601-TST-MR -8.984977         13013051-M0
1225361    15006601-TST-MR -8.984977         13013044-M1
1225362    15006601-TST-MR -8.984977         13013044-M0
1225363    15006601-TST-MR -8.984977         13012818-M1
1225364    15006701-TST-CP  7.501241            15006701
1225365    15006801-TST-MR -8.688200         13012970-M0
1225366    15006801-TST-MR -8.736179         13013008-M0
1225367    15006801-TST-MR -8.905711         13012990-M0
1225368    15006801-TST-MR -8.919393         13012883-M0
1225369    15006801-TST-MR -8.982270         13012963-M0
1225370    15006801-TST-MR -8.982270         13013044-M1
1225371    15006801-TST-MR -8.982270         13013002-M1
1225372    15006801-TST-MR -8.982270         13013019-M1
1225373    15006801-TST-MR -8.982270         13013019-M0
1225374    15006801-TST-MR -9.008269         13012895-M0

[1225375 rows x 3 columns]

In [31]:
restricted_df[['queried_record_id', 'predicted_record_id']].to_csv("restricted_df.csv", index=False)
# Così facciamo 0.980730268432966

In [85]:
# Sub in cui non si raccomandano quelli che hanno uno scores minore di zero (a quelli si rende nel campo 'predicted_record_id'
#  lo stesso valore del rispettivo 'queried_record_id')
new_sub = []
for (q, s, r) in tqdm(zip(s.queried_record_id, s.ordered_scores, s.ordered_record)):
    if s[0] < 0:
        new_sub.append((q, s, [q]))
    else:
        new_sub.append((q, s, r))

new_s = pd.DataFrame(new_sub, columns=['queried_record_id', 'scores', 'predicted_record_id'])

new_s.to_csv("lgb_sub_record_greater_than_0.csv", index=False)

HBox(children=(IntProgress(value=1, bar_style='info', max=1), HTML(value='')))

In [98]:
s[['queried_record_id', 'ordered_scores', 'ordered_record']].to_csv("lgb_sub_record_id.csv", index=False)

In [100]:
# Precision su quelle che non hanno riferimento nel train: guardiamo quante volte raccomandiamo il record_id = queried_record_id
# su quante volte andrebbe raccomandato veramente
only_test_df = test[test.linked_id.isin(only_test)]

In [108]:
less_than_0_sub = sub.drop_duplicates('queried_record_id',keep='first')[sub.score < 0]

c:\users\blueace17\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.

In [111]:
less_than_0_sub

         queried_record_id  predicted_linked_id     score  linked_id  correct
0          10000003-TST-MR             10127532 -9.164867   10000003        0
150        10000013-TST-MR             10153043 -3.362891   10000013        0
200        10000016-TST-MR             10147072 -2.652029   10000016        0
250        10000017-TST-MR             10155088 -2.460387   10000017        0
850        10000028-TST-MR             10021933 -7.976158   10000028        0
1100        10000034-TST-M             10213815 -0.289495   10000034        0
1400       10000038-TST-MR             10136074 -3.203970   10000038        0
1650       10000043-TST-MR             10175740 -1.162515   10000043        0
1900       10000050-TST-MR             10098513 -4.581791   10000050        0
2400       10000060-TST-MR             13012970 -8.502919   10000060        0
2450        10000061-TST-M             10193219 -1.741851   10000061        0
2950       10000074-TST-MR             10017941 -2.872044   10000074        0
3000       10000078-TST-MR             10146908 -2.836562   10000078        0
3150       10000082-TST-MR             13012970 -8.698351   10000082        0
3350        10000088-TST-M             12197456 -8.369011   10000088        0
3500       10000093-TST-MR             10110560 -7.624671   10000093        0
3550       10000094-TST-MR             12098613 -2.149365   10000094        0
3600       10000097-TST-MR             10043831 -6.875988   10000097        0
3950       10000116-TST-MR             10090634 -0.964378   10000116        0
4400       10000128-TST-MR             10198311 -5.477823   10000128        0
4450       10000130-TST-MR             10153163 -7.772795   10000130        0
4550       10000136-TST-MR             10150687 -3.346604   10000136        0
4700       10000139-TST-MR             12176389 -0.779368   10000139        0
4850       10000141-TST-MR             10018118 -2.585412   10000141        0
5000       10000146-TST-MR             10135751 -4.078904   10000146        0
5100       10000148-TST-MR             10043782 -0.435653   10000148        0
5150       10000149-TST-MR             13006660 -8.335253   10000149        0
5200       10000150-TST-MR             10043440 -2.772048   10000150        0
5250       10000154-TST-MR             10029683 -1.960947   10000154        0
5300       10000155-TST-MR             10028165 -8.720606   10000155        0
...                    ...                  ...       ...        ...      ...
13341850   13012997-TST-MR             12194668 -9.001648   13012997        0
13341950   13013001-TST-MR             12142099 -1.386961   13013001        0
13342350   13013013-TST-MR             12140795 -1.795941   13013013        0
13342750   13013020-TST-MR             12197217 -1.727472   13013020        0
13342900   13013024-TST-MR             10004295 -8.492361   13013024        0
13343350   13013042-TST-MR             12139581 -8.412884   13013042        0
13344000   13013059-TST-MR             12221106 -0.342171   13013059        0
13344350   13013075-TST-MR             13009737 -3.462076   13013075        0
13344400   13013076-TST-MR             12190895 -9.285024   13013076        0
13345300   13013094-TST-MR             12083250 -1.319029   13013094        0
13345550   13013098-TST-MR             12200055 -0.879852   13013098        0
13345600   13013100-TST-MR             12157965 -2.533208   13013100        0
13345650   13013102-TST-MR             12224905 -5.418000   13013102        0
13345850   13013107-TST-MR             12127640 -3.001480   13013107        0
13346000   13013115-TST-MR             13005074 -2.989171   13013115        0
13346350    15000601-TST-M             13012970 -8.502919   15000601        0
13346400   15000801-TST-MR             12170250 -8.315911   15000801        0
13346450   15000901-TST-MR             13012970 -8.502919   15000901        0
13346700   15001501-TST-MR             12127195 -3.793163   15001501        0
13346850   15001903-TST-MR             15001902 -1.761391   15001903        0
13346950   15003201-TST-MR             13010083 -8.469808   15003201        0
13347000   15003301-TST-MR             13002874 -4.526188   15003301        0
13347150   15004501-TST-MR             13010816 -8.662835   15004501        0
13347200   15005002-TST-MR             15005001 -2.649079   15005002        0
13347250   15005003-TST-MR             12122083 -2.074060   15005003        0
13347300    15005004-TST-M             12122083 -4.622233   15005004        0
13347350   15005201-TST-MR             11003591 -3.608876   15005201        0
13347400   15005401-TST-MR             13012970 -8.582948   15005401        0
13347600   15006601-TST-MR             12153758 -8.665527   15006601        0
13347700   15006801-TST-MR             13012970 -8.688200   15006801        0

[85973 rows x 5 columns]

In [112]:
only_test_df = only_test_df.merge(less_than_0_sub[['queried_record_id', 'score']], how='left', left_on='record_id', right_on='queried_record_id')

In [115]:
only_test_df

,record_id,name,type,address,phone,email,modification,split_name,linked_id,queried_record_id,score
0,10000003-TST-MR,"HOTFOCUS CO., LTD.",entity,NaN,4.401574e+11,consulting@outlook.ch,move unique,"[10000003, TST, MR]",10000003,10000003-TST-MR,-9.164867
1,10000008-TST-M,BONUS TRADE LIMITED,entity,NaN,NaN,help@gmail.gov,move row,"[10000008, TST, M]",10000008,NaN,NaN
2,10000013-TST-MR,VICTORY GROUP LIMITED,entity,NaN,1.949506e+10,NaN,move unique,"[10000013, TST, MR]",10000013,10000013-TST-MR,-3.362891
3,10000016-TST-MR,"NINGBO RAPID INTERNATIONAL TRADING CO., LTD.",entity,NaN,4.446512e+11,info@outlook.cz,move unique,"[10000016, TST, MR]",10000016,10000016-TST-MR,-2.652029
4,10000017-TST-MR,ANGELIKA INTERNATIONAL LTD.,entity,NaN,NaN,NaN,move unique,"[10000017, TST, MR]",10000017,10000017-TST-MR,-2.460387
5,10000024-TST-MR,LAKE STREET INVESTMENTS LTD.,entity,NaN,4.174193e+12,NaN,move unique,"[10000024, TST, MR]",10000024,NaN,NaN
6,10000025-TST-MR,GIT CO INC.,entity,NaN,NaN,NaN,move unique,"[10000025, TST, MR]",10000025,NaN,NaN
7,10000028-TST-MR,WINESELECTION S.A.,entity,NaN,3.959136e+09,WINESELECTIONSA@hotmail.de,move unique,"[10000028, TST, MR]",10000028,10000028-TST-MR,-7.976158
8,10000030-TST-MR,KIND INTERNATIONAL INC.,entity,NaN,4.209494e+11,NaN,move unique,"[10000030, TST, MR]",10000030,NaN,NaN
9,10000034-TST-M,Alvear Investments Limited,entity,NaN,4.208877e+11,NaN,move row,"[10000034, TST, M]",10000034,10000034-TST-M,-0.289495
10,10000037-TST-MR,PARKDALE HOLDINGS LTD.,entity,NaN,3.970247e+09,support@PARKDALE.HOLDINGS.LTD.it,move unique,"[10000037, TST, MR]",10000037,NaN,NaN
11,10000038-TST-MR,SADDLEVILLE CORPORATION,entity,NaN,3.378238e+11,NaN,move unique,"[10000038, TST, MR]",10000038,10000038-TST-MR,-3.203970
12,10000041-TST-MR,LONSDALE LIMITED,entity,NaN,4.995296e+10,NaN,move unique,"[10000041, TST, MR]",10000041,NaN,NaN
13,10000042-TST-MR,GARIBALDI S.A.,entity,NaN,3.387621e+11,NaN,move unique,"[10000042, TST, MR]",10000042,NaN,NaN
14,10000043-TST-MR,DAFORD INTERNATIONAL CORP.,entity,NaN,1.319877e+10,NaN,move unique,"[10000043, TST, MR]",10000043,10000043-TST-MR,-1.162515
15,10000044-TST-MR,GOLDEN NET INTERNATIONAL LIMITED,entity,AKMJ CONSULTING SERVICES LIMITED 20/F.; BANGKO...,NaN,help@zoho.cz,move unique,"[10000044, TST, MR]",10000044,NaN,NaN
16,10000050-TST-MR,UNIVERSAL RESOURCES LIMITED,entity,NaN,NaN,NaN,move unique,"[10000050, TST, MR]",10000050,10000050-TST-MR,-4.581791
17,10000055-TST-MR,SEG MECHANICAL LTD.,entity,EUROFIN SERVICES S.A. P.O.BOX 6003 LAUSANNE 1...,3.318115e+11,NaN,move unique,"[10000055, TST, MR]",10000055,NaN,NaN
18,10000056-TST-MR,"SUCCESSFUL CENTURY CO., LTD.",entity,NaN,1.480370e+10,NaN,move unique,"[10000056, TST, MR]",10000056,NaN,NaN
19,10000060-TST-MR,World Entertainment Phuket Ltd.,entity,NaN,NaN,NaN,move unique,"[10000060, TST, MR]",10000060,10000060-TST-MR,-8.502919
20,10000061-TST-M,RED ROSE INC.,entity,NaN,NaN,info@RED.ROSE.INC.it,move row,"[10000061, TST, M]",10000061,10000061-TST-M,-1.741851
21,10000063-TST-MR,SEACLIFF INVESTMENTS LIMITED,entity,NaN,NaN,NaN,move unique,"[10000063, TST, MR]",10000063,NaN,NaN
22,10000074-TST-MR,YELLOW SUN LTD.,entity,NaN,NaN,NaN,move unique,"[10000074, TST, MR]",10000074,10000074-TST-MR,-2.872044
23,10000078-TST-MR,GOLDENFULL ENTERPRISE LTD.,entity,NaN,NaN,support@gmail.gov,move unique,"[10000078, TST, MR]",10000078,10000078-TST-MR,-2.836562
24,10000081-TST-MR,LIBERTY CAPITAL INC.,entity,NaN,4.209123e+11,NaN,move unique,"[10000081, TST, MR]",10000081,NaN,NaN
25,10000082-TST-MR,Coral Palms Holdings Ltd.,entity,NaN,NaN,inquires@Coral.Palms.Holdings.Ltd.cz,move unique,"[10000082, TST, MR]",10000082,10000082-TST-MR,-8.698351
26,10000083-TST-MR,Island Dawn Holdings Ltd.,entity,NaN,4.178144e+12,NaN,move unique,"[10000083, TST, MR]",10000083,NaN,NaN
27,10000084-TST-MR,CLARE WORLDWIDE LTD.,entity,NaN,1.826049e+10,NaN,move unique,"[10000084, TST, MR]",10000084,NaN,NaN
28,10000088-TST-M,MAXPRO UT WORLD PTY. LTD.,entity,NaN,4.975543e+10,NaN,move row,"[10000088, TST, M]",10000088,10000088-TST-M,-8.369011
29,10000091-TST-MR,IEP S.A.,entity,ANDBANC GRUP AGRICOL REIG C/ MANUEL CERQUEDA ...,4.105798e+12,NaN,move unique,"[10000091, TST, MR]",10000091,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
118536,13013076-TST-MR,Nabil Khalid Abdullah Al Dabal,officer,NaN,3.994038e+09,NabilKhalidAbdullahAlDabal@protonmail.gov,move unique,"[13013076, TST, MR]",13013076,13013076-TST-MR,-9.285024
118537,13013077-TST-MR,TONG GUAN QI,officer,ROOM 508; BUILDING 51; FENGHUANG XINCUN; ZHONG...,3.300276e+11,TONGGUANQI@gmail.com,move unique,"[13013077, TST, MR]",13013077,NaN,NaN
118538,13013078-TST-MR,VICTOR RAUL ARENAS ASTETE,officer,Jr. Los Virreyes 304; Opto. 101; Urb. Las Loma...,4.202649e+11,VICTORRAULARENASASTETE@outlook.it,move unique,"[13013078, TST, MR]",13013078,NaN,NaN
118539,13013081-TST-MR,Raed Dheyaa Jaafar Al-Musawi,officer,4 Flemming Lodge; Admiral Walk; Carlton Gate; ...,NaN,help@hotmail.it,move unique,"[13013081, TST, MR]",13013081,NaN,NaN
118540,13013082-TST-MR,YU TSUNG CHIN WILLIAM,officer,Flat C; 4/F; Block 2; The Arcadia; 8 Forfar Ro...,4.932032e+10,NaN,move unique,"[13013082, TST, MR]",13013082,NaN,NaN
118541,13013093-TST-MR,MR. IBRAHIM KÖLÜK,officer,Istanbul Caddesi No : 78/2 Yesilköy; Istanbul;...,4.418304e+11,IBRAHIMKOLUK@hotmail.it,move unique,"[13013093, TST, MR]",13013093,NaN,NaN
118542,13013094-TST-MR,HUANG WEI GUO,officer,P.O. BOX 13873 WELLINGTON NEW ZEALAND,4.980180e+10,NaN,move unique,"[13013094, TST, MR]",13013094,13013094-TST-MR,-1.319029
118543,13013098-TST-MR,Rana El-Chemaitelly,officer,Ras El-Nabae; abdul Hafez Al-Shaar street; Al-...,3.349535e+11,NaN,move unique,"[13013098, TST, MR]",13013098,13013098-TST-MR,-0.879852
118544,13013100-TST-MR,MILOS TRACIK,officer,NaN,3.354227e+11,NaN,move unique,"[13013100, TST, MR]",13013100,13013100-TST-MR,-2.533208
118545,13013102-TST-MR,Franco CANZI,officer,"7 avenue Saint Roman, Monaco",4.978946e+10,contact@Franco.CANZI.gov,move unique,"[13013102, TST, MR]",13013102,13013102-TST-MR,-5.418000
118546,13013103-TST-MR,John Marshall,officer,Flat 1 Chateau de la Mer; Havre Des Pas; St. H...,4.452872e+11,NaN,move unique,"[13013103, TST, MR]",13013103,NaN,NaN
118547,13013107-TST-MR,Nikolay AMBROSOV,officer,NaN,1.640529e+10,NikolayAMBROSOV@aol.ch,move unique,"[13013107, TST, MR]",13013107,13013107-TST-MR,-3.001480
118548,13013115-TST-MR,"MR. LEUNG KA YUEN, LAWRENCE",officer,52 LA SALLE ROAD; KOWLOON; HONG KONG,1.739295e+10,NaN,move unique,"[13013115, TST, MR]",13013115,13013115-TST-MR,-2.989171
118549,13013116-TST-M,LI LAN HUA,officer,21 ZU; WENHUA SHEQU; ANMIN STREET; LONGJING; J...,3.391758e+11,LANHUA@gmail.gov,move row,"[13013116, TST, M]",13013116,NaN,NaN
118550,15000601-TST-M,Pilar de Borbón,officer,NaN,NaN,NaN,move row,"[15000601, TST, M]",15000601,15000601-TST-M,-8.502919
118551,15000801-TST-MR,Bruno Jean-Richard Itoua,officer,NaN,4.405693e+11,NaN,move unique,"[15000801, TST, MR]",15000801,15000801-TST-MR,-8.315911
118552,15000901-TST-MR,Micaela Domecq Solís-Beaumont,officer,NaN,NaN,NaN,move unique,"[15000901, TST, MR]",15000901,15000901-TST-MR,-8.502919
118553,15001301-TST-MR,John Addo Kufuor,officer,NaN,3.335382e+11,NaN,move unique,"[15001301, TST, MR]",15001301,NaN,NaN
118554,15001501-TST-MR,Mamadie Toure,officer,NaN,4.425446e+11,MamadieToure@icloud.it,move unique,"[15001501, TST, MR]",15001501,15001501-TST-MR,-3.793163
118555,15001903-TST-MR,Hussain Nawaz Sharif,officer,NaN,3.991790e+09,help@hotmail.de,move unique,"[15001903, TST, MR]",15001903,15001903-TST-MR,-1.761391
118556,15003201-TST-MR,Víctor Cruz Weffer,officer,NaN,1.702037e+10,VictorCruzWeffer@gmail.gov,move unique,"[15003201, TST, MR]",15003201,15003201-TST-MR,-8.469808
118557,15003301-TST-MR,Pedro Delgado,officer,NaN,3.326740e+11,PedroDelgado@icloud.co.uk,move unique,"[15003301, TST, MR]",15003301,15003301-TST-MR,-4.526188
118558,15004501-TST-MR,King Salman bin Abdulaziz bin Abdulrahman Al Saud,officer,NaN,3.341554e+11,NaN,move unique,"[15004501, TST, MR]",15004501,15004501-TST-MR,-8.662835
118559,15005002-TST-MR,Leyla Aliyeva,officer,NaN,NaN,NaN,move unique,"[15005002, TST, MR]",15005002,15005002-TST-MR,-2.649079
118560,15005003-TST-MR,Arzu Aliyeva,officer,NaN,3.319085e+11,NaN,move unique,"[15005003, TST, MR]",15005003,15005003-TST-MR,-2.074060
118561,15005004-TST-M,Heydar Aliyev,officer,NaN,4.201462e+11,HeydarAliyev@hotmail.co.uk,move row,"[15005004, TST, M]",15005004,15005004-TST-M,-4.622233
118562,15005201-TST-MR,Konrad Mizzi,officer,NaN,4.993561e+10,NaN,move unique,"[15005201, TST, MR]",15005201,15005201-TST-MR,-3.608876
118563,15005401-TST-MR,Mamadou Pouye,officer,NaN,NaN,NaN,move unique,"[15005401, TST, MR]",15005401,15005401-TST-MR,-8.582948
118564,15006601-TST-MR,Bjarni Benediktsson,officer,NaN,NaN,BjarniBenediktsson@aol.gov,move unique,"[15006601, TST, MR]",15006601,15006601-TST-MR,-8.665527
118565,15006801-TST-MR,James Ibori,officer,NaN,NaN,NaN,move unique,"[15006801, TST, MR]",15006801,15006801-TST-MR,-8.688200

In [119]:
only_test_df[~only_test_df.queried_record_id.isna()].shape

(84744, 11)

In [120]:
# Predicendo come only_test quelle rows che dalla nostra sub hanno come scores più grande un valore negativo, ne becchiamo un 71%
84744 / only_test_df.shape[0]

0.7147411568240474